// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Account.pb.h"

@implementation AccountRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [AccountRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface MAccount ()
@property (retain) NSString* id;
@property (retain) NSString* verify;
@property int32_t type;
@property int32_t inited;
@end

@implementation MAccount

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value {
  hasId_ = !!_value;
}
@synthesize id;
- (BOOL) hasVerify {
  return !!hasVerify_;
}
- (void) setHasVerify:(BOOL) _value {
  hasVerify_ = !!_value;
}
@synthesize verify;
- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) _value {
  hasType_ = !!_value;
}
@synthesize type;
- (BOOL) hasInited {
  return !!hasInited_;
}
- (void) setHasInited:(BOOL) _value {
  hasInited_ = !!_value;
}
@synthesize inited;
- (void) dealloc {
  self.id = nil;
  self.verify = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = @"";
    self.verify = @"";
    self.type = 0;
    self.inited = 0;
  }
  return self;
}
static MAccount* defaultMAccountInstance = nil;
+ (void) initialize {
  if (self == [MAccount class]) {
    defaultMAccountInstance = [[MAccount alloc] init];
  }
}
+ (MAccount*) defaultInstance {
  return defaultMAccountInstance;
}
- (MAccount*) defaultInstance {
  return defaultMAccountInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeString:1 value:self.id];
  }
  if (self.hasVerify) {
    [output writeString:2 value:self.verify];
  }
  if (self.hasType) {
    [output writeInt32:3 value:self.type];
  }
  if (self.hasInited) {
    [output writeInt32:4 value:self.inited];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasId) {
    size += computeStringSize(1, self.id);
  }
  if (self.hasVerify) {
    size += computeStringSize(2, self.verify);
  }
  if (self.hasType) {
    size += computeInt32Size(3, self.type);
  }
  if (self.hasInited) {
    size += computeInt32Size(4, self.inited);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MAccount*) parseFromData:(NSData*) data {
  return (MAccount*)[[[MAccount builder] mergeFromData:data] build];
}
+ (MAccount*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MAccount*)[[[MAccount builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MAccount*) parseFromInputStream:(NSInputStream*) input {
  return (MAccount*)[[[MAccount builder] mergeFromInputStream:input] build];
}
+ (MAccount*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MAccount*)[[[MAccount builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MAccount*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MAccount*)[[[MAccount builder] mergeFromCodedInputStream:input] build];
}
+ (MAccount*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MAccount*)[[[MAccount builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MAccount_Builder*) builder {
  return [[[MAccount_Builder alloc] init] autorelease];
}
+ (MAccount_Builder*) builderWithPrototype:(MAccount*) prototype {
  return [[MAccount builder] mergeFrom:prototype];
}
- (MAccount_Builder*) builder {
  return [MAccount builder];
}
@end

@interface MAccount_Builder()
@property (retain) MAccount* protobufBuilderResult;
@end

@implementation MAccount_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MAccount alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MAccount_Builder*) clear {
  self.protobufBuilderResult = [[[MAccount alloc] init] autorelease];
  return self;
}
- (MAccount_Builder*) clone {
  return [MAccount builderWithPrototype:protobufBuilderResult];
}
- (MAccount*) defaultInstance {
  return [MAccount defaultInstance];
}
- (MAccount*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MAccount*) buildPartial {
  MAccount* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MAccount_Builder*) mergeFrom:(MAccount*) other {
  if (other == [MAccount defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasVerify) {
    [self setVerify:other.verify];
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  if (other.hasInited) {
    [self setInited:other.inited];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MAccount_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MAccount_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setId:[input readString]];
        break;
      }
      case 18: {
        [self setVerify:[input readString]];
        break;
      }
      case 24: {
        [self setType:[input readInt32]];
        break;
      }
      case 32: {
        [self setInited:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return protobufBuilderResult.hasId;
}
- (NSString*) id {
  return protobufBuilderResult.id;
}
- (MAccount_Builder*) setId:(NSString*) _value {
  protobufBuilderResult.hasId = YES;
  protobufBuilderResult.id = _value;
  return self;
}
- (MAccount_Builder*) clearId {
  protobufBuilderResult.hasId = NO;
  protobufBuilderResult.id = @"";
  return self;
}
- (BOOL) hasVerify {
  return protobufBuilderResult.hasVerify;
}
- (NSString*) verify {
  return protobufBuilderResult.verify;
}
- (MAccount_Builder*) setVerify:(NSString*) _value {
  protobufBuilderResult.hasVerify = YES;
  protobufBuilderResult.verify = _value;
  return self;
}
- (MAccount_Builder*) clearVerify {
  protobufBuilderResult.hasVerify = NO;
  protobufBuilderResult.verify = @"";
  return self;
}
- (BOOL) hasType {
  return protobufBuilderResult.hasType;
}
- (int32_t) type {
  return protobufBuilderResult.type;
}
- (MAccount_Builder*) setType:(int32_t) _value {
  protobufBuilderResult.hasType = YES;
  protobufBuilderResult.type = _value;
  return self;
}
- (MAccount_Builder*) clearType {
  protobufBuilderResult.hasType = NO;
  protobufBuilderResult.type = 0;
  return self;
}
- (BOOL) hasInited {
  return protobufBuilderResult.hasInited;
}
- (int32_t) inited {
  return protobufBuilderResult.inited;
}
- (MAccount_Builder*) setInited:(int32_t) _value {
  protobufBuilderResult.hasInited = YES;
  protobufBuilderResult.inited = _value;
  return self;
}
- (MAccount_Builder*) clearInited {
  protobufBuilderResult.hasInited = NO;
  protobufBuilderResult.inited = 0;
  return self;
}
@end

@interface MMe ()
@property (retain) NSString* id;
@property (retain) NSString* account;
@property int32_t sex;
@property (retain) NSString* nickname;
@property int32_t credits;
@property (retain) NSString* stb;
@property int32_t isVerify;
@property (retain) NSString* location;
@end

@implementation MMe

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value {
  hasId_ = !!_value;
}
@synthesize id;
- (BOOL) hasAccount {
  return !!hasAccount_;
}
- (void) setHasAccount:(BOOL) _value {
  hasAccount_ = !!_value;
}
@synthesize account;
- (BOOL) hasSex {
  return !!hasSex_;
}
- (void) setHasSex:(BOOL) _value {
  hasSex_ = !!_value;
}
@synthesize sex;
- (BOOL) hasNickname {
  return !!hasNickname_;
}
- (void) setHasNickname:(BOOL) _value {
  hasNickname_ = !!_value;
}
@synthesize nickname;
- (BOOL) hasCredits {
  return !!hasCredits_;
}
- (void) setHasCredits:(BOOL) _value {
  hasCredits_ = !!_value;
}
@synthesize credits;
- (BOOL) hasStb {
  return !!hasStb_;
}
- (void) setHasStb:(BOOL) _value {
  hasStb_ = !!_value;
}
@synthesize stb;
- (BOOL) hasIsVerify {
  return !!hasIsVerify_;
}
- (void) setHasIsVerify:(BOOL) _value {
  hasIsVerify_ = !!_value;
}
@synthesize isVerify;
- (BOOL) hasLocation {
  return !!hasLocation_;
}
- (void) setHasLocation:(BOOL) _value {
  hasLocation_ = !!_value;
}
@synthesize location;
- (void) dealloc {
  self.id = nil;
  self.account = nil;
  self.nickname = nil;
  self.stb = nil;
  self.location = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = @"";
    self.account = @"";
    self.sex = 0;
    self.nickname = @"";
    self.credits = 0;
    self.stb = @"";
    self.isVerify = 0;
    self.location = @"";
  }
  return self;
}
static MMe* defaultMMeInstance = nil;
+ (void) initialize {
  if (self == [MMe class]) {
    defaultMMeInstance = [[MMe alloc] init];
  }
}
+ (MMe*) defaultInstance {
  return defaultMMeInstance;
}
- (MMe*) defaultInstance {
  return defaultMMeInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeString:1 value:self.id];
  }
  if (self.hasAccount) {
    [output writeString:2 value:self.account];
  }
  if (self.hasSex) {
    [output writeInt32:3 value:self.sex];
  }
  if (self.hasNickname) {
    [output writeString:4 value:self.nickname];
  }
  if (self.hasCredits) {
    [output writeInt32:5 value:self.credits];
  }
  if (self.hasStb) {
    [output writeString:6 value:self.stb];
  }
  if (self.hasIsVerify) {
    [output writeInt32:7 value:self.isVerify];
  }
  if (self.hasLocation) {
    [output writeString:8 value:self.location];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasId) {
    size += computeStringSize(1, self.id);
  }
  if (self.hasAccount) {
    size += computeStringSize(2, self.account);
  }
  if (self.hasSex) {
    size += computeInt32Size(3, self.sex);
  }
  if (self.hasNickname) {
    size += computeStringSize(4, self.nickname);
  }
  if (self.hasCredits) {
    size += computeInt32Size(5, self.credits);
  }
  if (self.hasStb) {
    size += computeStringSize(6, self.stb);
  }
  if (self.hasIsVerify) {
    size += computeInt32Size(7, self.isVerify);
  }
  if (self.hasLocation) {
    size += computeStringSize(8, self.location);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MMe*) parseFromData:(NSData*) data {
  return (MMe*)[[[MMe builder] mergeFromData:data] build];
}
+ (MMe*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MMe*)[[[MMe builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MMe*) parseFromInputStream:(NSInputStream*) input {
  return (MMe*)[[[MMe builder] mergeFromInputStream:input] build];
}
+ (MMe*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MMe*)[[[MMe builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MMe*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MMe*)[[[MMe builder] mergeFromCodedInputStream:input] build];
}
+ (MMe*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MMe*)[[[MMe builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MMe_Builder*) builder {
  return [[[MMe_Builder alloc] init] autorelease];
}
+ (MMe_Builder*) builderWithPrototype:(MMe*) prototype {
  return [[MMe builder] mergeFrom:prototype];
}
- (MMe_Builder*) builder {
  return [MMe builder];
}
@end

@interface MMe_Builder()
@property (retain) MMe* protobufBuilderResult;
@end

@implementation MMe_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MMe alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MMe_Builder*) clear {
  self.protobufBuilderResult = [[[MMe alloc] init] autorelease];
  return self;
}
- (MMe_Builder*) clone {
  return [MMe builderWithPrototype:protobufBuilderResult];
}
- (MMe*) defaultInstance {
  return [MMe defaultInstance];
}
- (MMe*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MMe*) buildPartial {
  MMe* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MMe_Builder*) mergeFrom:(MMe*) other {
  if (other == [MMe defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasAccount) {
    [self setAccount:other.account];
  }
  if (other.hasSex) {
    [self setSex:other.sex];
  }
  if (other.hasNickname) {
    [self setNickname:other.nickname];
  }
  if (other.hasCredits) {
    [self setCredits:other.credits];
  }
  if (other.hasStb) {
    [self setStb:other.stb];
  }
  if (other.hasIsVerify) {
    [self setIsVerify:other.isVerify];
  }
  if (other.hasLocation) {
    [self setLocation:other.location];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MMe_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MMe_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setId:[input readString]];
        break;
      }
      case 18: {
        [self setAccount:[input readString]];
        break;
      }
      case 24: {
        [self setSex:[input readInt32]];
        break;
      }
      case 34: {
        [self setNickname:[input readString]];
        break;
      }
      case 40: {
        [self setCredits:[input readInt32]];
        break;
      }
      case 50: {
        [self setStb:[input readString]];
        break;
      }
      case 56: {
        [self setIsVerify:[input readInt32]];
        break;
      }
      case 66: {
        [self setLocation:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return protobufBuilderResult.hasId;
}
- (NSString*) id {
  return protobufBuilderResult.id;
}
- (MMe_Builder*) setId:(NSString*) _value {
  protobufBuilderResult.hasId = YES;
  protobufBuilderResult.id = _value;
  return self;
}
- (MMe_Builder*) clearId {
  protobufBuilderResult.hasId = NO;
  protobufBuilderResult.id = @"";
  return self;
}
- (BOOL) hasAccount {
  return protobufBuilderResult.hasAccount;
}
- (NSString*) account {
  return protobufBuilderResult.account;
}
- (MMe_Builder*) setAccount:(NSString*) _value {
  protobufBuilderResult.hasAccount = YES;
  protobufBuilderResult.account = _value;
  return self;
}
- (MMe_Builder*) clearAccount {
  protobufBuilderResult.hasAccount = NO;
  protobufBuilderResult.account = @"";
  return self;
}
- (BOOL) hasSex {
  return protobufBuilderResult.hasSex;
}
- (int32_t) sex {
  return protobufBuilderResult.sex;
}
- (MMe_Builder*) setSex:(int32_t) _value {
  protobufBuilderResult.hasSex = YES;
  protobufBuilderResult.sex = _value;
  return self;
}
- (MMe_Builder*) clearSex {
  protobufBuilderResult.hasSex = NO;
  protobufBuilderResult.sex = 0;
  return self;
}
- (BOOL) hasNickname {
  return protobufBuilderResult.hasNickname;
}
- (NSString*) nickname {
  return protobufBuilderResult.nickname;
}
- (MMe_Builder*) setNickname:(NSString*) _value {
  protobufBuilderResult.hasNickname = YES;
  protobufBuilderResult.nickname = _value;
  return self;
}
- (MMe_Builder*) clearNickname {
  protobufBuilderResult.hasNickname = NO;
  protobufBuilderResult.nickname = @"";
  return self;
}
- (BOOL) hasCredits {
  return protobufBuilderResult.hasCredits;
}
- (int32_t) credits {
  return protobufBuilderResult.credits;
}
- (MMe_Builder*) setCredits:(int32_t) _value {
  protobufBuilderResult.hasCredits = YES;
  protobufBuilderResult.credits = _value;
  return self;
}
- (MMe_Builder*) clearCredits {
  protobufBuilderResult.hasCredits = NO;
  protobufBuilderResult.credits = 0;
  return self;
}
- (BOOL) hasStb {
  return protobufBuilderResult.hasStb;
}
- (NSString*) stb {
  return protobufBuilderResult.stb;
}
- (MMe_Builder*) setStb:(NSString*) _value {
  protobufBuilderResult.hasStb = YES;
  protobufBuilderResult.stb = _value;
  return self;
}
- (MMe_Builder*) clearStb {
  protobufBuilderResult.hasStb = NO;
  protobufBuilderResult.stb = @"";
  return self;
}
- (BOOL) hasIsVerify {
  return protobufBuilderResult.hasIsVerify;
}
- (int32_t) isVerify {
  return protobufBuilderResult.isVerify;
}
- (MMe_Builder*) setIsVerify:(int32_t) _value {
  protobufBuilderResult.hasIsVerify = YES;
  protobufBuilderResult.isVerify = _value;
  return self;
}
- (MMe_Builder*) clearIsVerify {
  protobufBuilderResult.hasIsVerify = NO;
  protobufBuilderResult.isVerify = 0;
  return self;
}
- (BOOL) hasLocation {
  return protobufBuilderResult.hasLocation;
}
- (NSString*) location {
  return protobufBuilderResult.location;
}
- (MMe_Builder*) setLocation:(NSString*) _value {
  protobufBuilderResult.hasLocation = YES;
  protobufBuilderResult.location = _value;
  return self;
}
- (MMe_Builder*) clearLocation {
  protobufBuilderResult.hasLocation = NO;
  protobufBuilderResult.location = @"";
  return self;
}
@end

