// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class MMarket;
@class MMarketAct;
@class MMarketActList;
@class MMarketActList_Builder;
@class MMarketAct_Builder;
@class MMarketGoods;
@class MMarketGoodsList;
@class MMarketGoodsList_Builder;
@class MMarketGoods_Builder;
@class MMarketList;
@class MMarketList_Builder;
@class MMarketType;
@class MMarketTypeList;
@class MMarketTypeList_Builder;
@class MMarketType_Builder;
@class MMarket_Builder;

@interface MarketRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MMarketType : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  BOOL hasImg_:1;
  NSString* id;
  NSString* name;
  NSString* img;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasImg;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* img;

+ (MMarketType*) defaultInstance;
- (MMarketType*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMarketType_Builder*) builder;
+ (MMarketType_Builder*) builder;
+ (MMarketType_Builder*) builderWithPrototype:(MMarketType*) prototype;

+ (MMarketType*) parseFromData:(NSData*) data;
+ (MMarketType*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketType*) parseFromInputStream:(NSInputStream*) input;
+ (MMarketType*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketType*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMarketType*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMarketType_Builder : PBGeneratedMessage_Builder {
@private
  MMarketType* protobufBuilderResult;
}

- (MMarketType*) defaultInstance;

- (MMarketType_Builder*) clear;
- (MMarketType_Builder*) clone;

- (MMarketType*) build;
- (MMarketType*) buildPartial;

- (MMarketType_Builder*) mergeFrom:(MMarketType*) other;
- (MMarketType_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMarketType_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MMarketType_Builder*) setId:(NSString*) _value;
- (MMarketType_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (MMarketType_Builder*) setName:(NSString*) _value;
- (MMarketType_Builder*) clearName;

- (BOOL) hasImg;
- (NSString*) img;
- (MMarketType_Builder*) setImg:(NSString*) _value;
- (MMarketType_Builder*) clearImg;
@end

@interface MMarketTypeList : PBGeneratedMessage {
@private
  NSMutableArray* mutableListList;
}
- (NSArray*) listList;
- (MMarketType*) listAtIndex:(int32_t) index;

+ (MMarketTypeList*) defaultInstance;
- (MMarketTypeList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMarketTypeList_Builder*) builder;
+ (MMarketTypeList_Builder*) builder;
+ (MMarketTypeList_Builder*) builderWithPrototype:(MMarketTypeList*) prototype;

+ (MMarketTypeList*) parseFromData:(NSData*) data;
+ (MMarketTypeList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketTypeList*) parseFromInputStream:(NSInputStream*) input;
+ (MMarketTypeList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketTypeList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMarketTypeList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMarketTypeList_Builder : PBGeneratedMessage_Builder {
@private
  MMarketTypeList* protobufBuilderResult;
}

- (MMarketTypeList*) defaultInstance;

- (MMarketTypeList_Builder*) clear;
- (MMarketTypeList_Builder*) clone;

- (MMarketTypeList*) build;
- (MMarketTypeList*) buildPartial;

- (MMarketTypeList_Builder*) mergeFrom:(MMarketTypeList*) other;
- (MMarketTypeList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMarketTypeList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) listList;
- (MMarketType*) listAtIndex:(int32_t) index;
- (MMarketTypeList_Builder*) replaceListAtIndex:(int32_t) index with:(MMarketType*) _value;
- (MMarketTypeList_Builder*) addList:(MMarketType*) _value;
- (MMarketTypeList_Builder*) addAllList:(NSArray*) values;
- (MMarketTypeList_Builder*) clearListList;
@end

@interface MMarketGoods : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasName_:1;
  BOOL hasImg_:1;
  BOOL hasPrice_:1;
  NSString* id;
  NSString* name;
  NSString* img;
  NSString* price;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasImg;
- (BOOL) hasPrice;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* name;
@property (readonly, retain) NSString* img;
@property (readonly, retain) NSString* price;

+ (MMarketGoods*) defaultInstance;
- (MMarketGoods*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMarketGoods_Builder*) builder;
+ (MMarketGoods_Builder*) builder;
+ (MMarketGoods_Builder*) builderWithPrototype:(MMarketGoods*) prototype;

+ (MMarketGoods*) parseFromData:(NSData*) data;
+ (MMarketGoods*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketGoods*) parseFromInputStream:(NSInputStream*) input;
+ (MMarketGoods*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketGoods*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMarketGoods*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMarketGoods_Builder : PBGeneratedMessage_Builder {
@private
  MMarketGoods* protobufBuilderResult;
}

- (MMarketGoods*) defaultInstance;

- (MMarketGoods_Builder*) clear;
- (MMarketGoods_Builder*) clone;

- (MMarketGoods*) build;
- (MMarketGoods*) buildPartial;

- (MMarketGoods_Builder*) mergeFrom:(MMarketGoods*) other;
- (MMarketGoods_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMarketGoods_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MMarketGoods_Builder*) setId:(NSString*) _value;
- (MMarketGoods_Builder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (MMarketGoods_Builder*) setName:(NSString*) _value;
- (MMarketGoods_Builder*) clearName;

- (BOOL) hasImg;
- (NSString*) img;
- (MMarketGoods_Builder*) setImg:(NSString*) _value;
- (MMarketGoods_Builder*) clearImg;

- (BOOL) hasPrice;
- (NSString*) price;
- (MMarketGoods_Builder*) setPrice:(NSString*) _value;
- (MMarketGoods_Builder*) clearPrice;
@end

@interface MMarketGoodsList : PBGeneratedMessage {
@private
  NSMutableArray* mutableListList;
}
- (NSArray*) listList;
- (MMarketGoods*) listAtIndex:(int32_t) index;

+ (MMarketGoodsList*) defaultInstance;
- (MMarketGoodsList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMarketGoodsList_Builder*) builder;
+ (MMarketGoodsList_Builder*) builder;
+ (MMarketGoodsList_Builder*) builderWithPrototype:(MMarketGoodsList*) prototype;

+ (MMarketGoodsList*) parseFromData:(NSData*) data;
+ (MMarketGoodsList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketGoodsList*) parseFromInputStream:(NSInputStream*) input;
+ (MMarketGoodsList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketGoodsList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMarketGoodsList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMarketGoodsList_Builder : PBGeneratedMessage_Builder {
@private
  MMarketGoodsList* protobufBuilderResult;
}

- (MMarketGoodsList*) defaultInstance;

- (MMarketGoodsList_Builder*) clear;
- (MMarketGoodsList_Builder*) clone;

- (MMarketGoodsList*) build;
- (MMarketGoodsList*) buildPartial;

- (MMarketGoodsList_Builder*) mergeFrom:(MMarketGoodsList*) other;
- (MMarketGoodsList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMarketGoodsList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) listList;
- (MMarketGoods*) listAtIndex:(int32_t) index;
- (MMarketGoodsList_Builder*) replaceListAtIndex:(int32_t) index with:(MMarketGoods*) _value;
- (MMarketGoodsList_Builder*) addList:(MMarketGoods*) _value;
- (MMarketGoodsList_Builder*) addAllList:(NSArray*) values;
- (MMarketGoodsList_Builder*) clearListList;
@end

@interface MMarketAct : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasTitle_:1;
  BOOL hasImg_:1;
  BOOL hasTime_:1;
  BOOL hasUrl_:1;
  NSString* id;
  NSString* title;
  NSString* img;
  NSString* time;
  NSString* url;
}
- (BOOL) hasId;
- (BOOL) hasTitle;
- (BOOL) hasImg;
- (BOOL) hasTime;
- (BOOL) hasUrl;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* title;
@property (readonly, retain) NSString* img;
@property (readonly, retain) NSString* time;
@property (readonly, retain) NSString* url;

+ (MMarketAct*) defaultInstance;
- (MMarketAct*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMarketAct_Builder*) builder;
+ (MMarketAct_Builder*) builder;
+ (MMarketAct_Builder*) builderWithPrototype:(MMarketAct*) prototype;

+ (MMarketAct*) parseFromData:(NSData*) data;
+ (MMarketAct*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketAct*) parseFromInputStream:(NSInputStream*) input;
+ (MMarketAct*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketAct*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMarketAct*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMarketAct_Builder : PBGeneratedMessage_Builder {
@private
  MMarketAct* protobufBuilderResult;
}

- (MMarketAct*) defaultInstance;

- (MMarketAct_Builder*) clear;
- (MMarketAct_Builder*) clone;

- (MMarketAct*) build;
- (MMarketAct*) buildPartial;

- (MMarketAct_Builder*) mergeFrom:(MMarketAct*) other;
- (MMarketAct_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMarketAct_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MMarketAct_Builder*) setId:(NSString*) _value;
- (MMarketAct_Builder*) clearId;

- (BOOL) hasTitle;
- (NSString*) title;
- (MMarketAct_Builder*) setTitle:(NSString*) _value;
- (MMarketAct_Builder*) clearTitle;

- (BOOL) hasImg;
- (NSString*) img;
- (MMarketAct_Builder*) setImg:(NSString*) _value;
- (MMarketAct_Builder*) clearImg;

- (BOOL) hasTime;
- (NSString*) time;
- (MMarketAct_Builder*) setTime:(NSString*) _value;
- (MMarketAct_Builder*) clearTime;

- (BOOL) hasUrl;
- (NSString*) url;
- (MMarketAct_Builder*) setUrl:(NSString*) _value;
- (MMarketAct_Builder*) clearUrl;
@end

@interface MMarketActList : PBGeneratedMessage {
@private
  NSMutableArray* mutableListList;
}
- (NSArray*) listList;
- (MMarketAct*) listAtIndex:(int32_t) index;

+ (MMarketActList*) defaultInstance;
- (MMarketActList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMarketActList_Builder*) builder;
+ (MMarketActList_Builder*) builder;
+ (MMarketActList_Builder*) builderWithPrototype:(MMarketActList*) prototype;

+ (MMarketActList*) parseFromData:(NSData*) data;
+ (MMarketActList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketActList*) parseFromInputStream:(NSInputStream*) input;
+ (MMarketActList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketActList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMarketActList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMarketActList_Builder : PBGeneratedMessage_Builder {
@private
  MMarketActList* protobufBuilderResult;
}

- (MMarketActList*) defaultInstance;

- (MMarketActList_Builder*) clear;
- (MMarketActList_Builder*) clone;

- (MMarketActList*) build;
- (MMarketActList*) buildPartial;

- (MMarketActList_Builder*) mergeFrom:(MMarketActList*) other;
- (MMarketActList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMarketActList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) listList;
- (MMarketAct*) listAtIndex:(int32_t) index;
- (MMarketActList_Builder*) replaceListAtIndex:(int32_t) index with:(MMarketAct*) _value;
- (MMarketActList_Builder*) addList:(MMarketAct*) _value;
- (MMarketActList_Builder*) addAllList:(NSArray*) values;
- (MMarketActList_Builder*) clearListList;
@end

@interface MMarket : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasTitle_:1;
  BOOL hasDistance_:1;
  NSString* id;
  NSString* title;
  NSString* distance;
}
- (BOOL) hasId;
- (BOOL) hasTitle;
- (BOOL) hasDistance;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* title;
@property (readonly, retain) NSString* distance;

+ (MMarket*) defaultInstance;
- (MMarket*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMarket_Builder*) builder;
+ (MMarket_Builder*) builder;
+ (MMarket_Builder*) builderWithPrototype:(MMarket*) prototype;

+ (MMarket*) parseFromData:(NSData*) data;
+ (MMarket*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarket*) parseFromInputStream:(NSInputStream*) input;
+ (MMarket*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarket*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMarket*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMarket_Builder : PBGeneratedMessage_Builder {
@private
  MMarket* protobufBuilderResult;
}

- (MMarket*) defaultInstance;

- (MMarket_Builder*) clear;
- (MMarket_Builder*) clone;

- (MMarket*) build;
- (MMarket*) buildPartial;

- (MMarket_Builder*) mergeFrom:(MMarket*) other;
- (MMarket_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMarket_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MMarket_Builder*) setId:(NSString*) _value;
- (MMarket_Builder*) clearId;

- (BOOL) hasTitle;
- (NSString*) title;
- (MMarket_Builder*) setTitle:(NSString*) _value;
- (MMarket_Builder*) clearTitle;

- (BOOL) hasDistance;
- (NSString*) distance;
- (MMarket_Builder*) setDistance:(NSString*) _value;
- (MMarket_Builder*) clearDistance;
@end

@interface MMarketList : PBGeneratedMessage {
@private
  NSMutableArray* mutableListList;
}
- (NSArray*) listList;
- (MMarket*) listAtIndex:(int32_t) index;

+ (MMarketList*) defaultInstance;
- (MMarketList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMarketList_Builder*) builder;
+ (MMarketList_Builder*) builder;
+ (MMarketList_Builder*) builderWithPrototype:(MMarketList*) prototype;

+ (MMarketList*) parseFromData:(NSData*) data;
+ (MMarketList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketList*) parseFromInputStream:(NSInputStream*) input;
+ (MMarketList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarketList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMarketList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMarketList_Builder : PBGeneratedMessage_Builder {
@private
  MMarketList* protobufBuilderResult;
}

- (MMarketList*) defaultInstance;

- (MMarketList_Builder*) clear;
- (MMarketList_Builder*) clone;

- (MMarketList*) build;
- (MMarketList*) buildPartial;

- (MMarketList_Builder*) mergeFrom:(MMarketList*) other;
- (MMarketList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMarketList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) listList;
- (MMarket*) listAtIndex:(int32_t) index;
- (MMarketList_Builder*) replaceListAtIndex:(int32_t) index with:(MMarket*) _value;
- (MMarketList_Builder*) addList:(MMarket*) _value;
- (MMarketList_Builder*) addAllList:(NSArray*) values;
- (MMarketList_Builder*) clearListList;
@end

