// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class MCreditsLog;
@class MCreditsLogList;
@class MCreditsLogList_Builder;
@class MCreditsLog_Builder;

@interface MyRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MCreditsLog : PBGeneratedMessage {
@private
  BOOL hasType_:1;
  BOOL hasId_:1;
  BOOL hasItem_:1;
  BOOL hasInfo_:1;
  BOOL hasNum_:1;
  BOOL hasTime_:1;
  int32_t type;
  NSString* id;
  NSString* item;
  NSString* info;
  NSString* num;
  NSString* time;
}
- (BOOL) hasId;
- (BOOL) hasType;
- (BOOL) hasItem;
- (BOOL) hasInfo;
- (BOOL) hasNum;
- (BOOL) hasTime;
@property (readonly, retain) NSString* id;
@property (readonly) int32_t type;
@property (readonly, retain) NSString* item;
@property (readonly, retain) NSString* info;
@property (readonly, retain) NSString* num;
@property (readonly, retain) NSString* time;

+ (MCreditsLog*) defaultInstance;
- (MCreditsLog*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MCreditsLog_Builder*) builder;
+ (MCreditsLog_Builder*) builder;
+ (MCreditsLog_Builder*) builderWithPrototype:(MCreditsLog*) prototype;

+ (MCreditsLog*) parseFromData:(NSData*) data;
+ (MCreditsLog*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MCreditsLog*) parseFromInputStream:(NSInputStream*) input;
+ (MCreditsLog*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MCreditsLog*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MCreditsLog*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MCreditsLog_Builder : PBGeneratedMessage_Builder {
@private
  MCreditsLog* protobufBuilderResult;
}

- (MCreditsLog*) defaultInstance;

- (MCreditsLog_Builder*) clear;
- (MCreditsLog_Builder*) clone;

- (MCreditsLog*) build;
- (MCreditsLog*) buildPartial;

- (MCreditsLog_Builder*) mergeFrom:(MCreditsLog*) other;
- (MCreditsLog_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MCreditsLog_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MCreditsLog_Builder*) setId:(NSString*) _value;
- (MCreditsLog_Builder*) clearId;

- (BOOL) hasType;
- (int32_t) type;
- (MCreditsLog_Builder*) setType:(int32_t) _value;
- (MCreditsLog_Builder*) clearType;

- (BOOL) hasItem;
- (NSString*) item;
- (MCreditsLog_Builder*) setItem:(NSString*) _value;
- (MCreditsLog_Builder*) clearItem;

- (BOOL) hasInfo;
- (NSString*) info;
- (MCreditsLog_Builder*) setInfo:(NSString*) _value;
- (MCreditsLog_Builder*) clearInfo;

- (BOOL) hasNum;
- (NSString*) num;
- (MCreditsLog_Builder*) setNum:(NSString*) _value;
- (MCreditsLog_Builder*) clearNum;

- (BOOL) hasTime;
- (NSString*) time;
- (MCreditsLog_Builder*) setTime:(NSString*) _value;
- (MCreditsLog_Builder*) clearTime;
@end

@interface MCreditsLogList : PBGeneratedMessage {
@private
  NSMutableArray* mutableListList;
}
- (NSArray*) listList;
- (MCreditsLog*) listAtIndex:(int32_t) index;

+ (MCreditsLogList*) defaultInstance;
- (MCreditsLogList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MCreditsLogList_Builder*) builder;
+ (MCreditsLogList_Builder*) builder;
+ (MCreditsLogList_Builder*) builderWithPrototype:(MCreditsLogList*) prototype;

+ (MCreditsLogList*) parseFromData:(NSData*) data;
+ (MCreditsLogList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MCreditsLogList*) parseFromInputStream:(NSInputStream*) input;
+ (MCreditsLogList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MCreditsLogList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MCreditsLogList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MCreditsLogList_Builder : PBGeneratedMessage_Builder {
@private
  MCreditsLogList* protobufBuilderResult;
}

- (MCreditsLogList*) defaultInstance;

- (MCreditsLogList_Builder*) clear;
- (MCreditsLogList_Builder*) clone;

- (MCreditsLogList*) build;
- (MCreditsLogList*) buildPartial;

- (MCreditsLogList_Builder*) mergeFrom:(MCreditsLogList*) other;
- (MCreditsLogList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MCreditsLogList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) listList;
- (MCreditsLog*) listAtIndex:(int32_t) index;
- (MCreditsLogList_Builder*) replaceListAtIndex:(int32_t) index with:(MCreditsLog*) _value;
- (MCreditsLogList_Builder*) addList:(MCreditsLog*) _value;
- (MCreditsLogList_Builder*) addAllList:(NSArray*) values;
- (MCreditsLogList_Builder*) clearListList;
@end

