// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "Order.pb.h"

@implementation OrderRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [OrderRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface MPay ()
@property (retain) NSString* id;
@property (retain) NSString* code;
@property int32_t payType;
@property (retain) NSString* name;
@property (retain) NSString* price;
@property int32_t num;
@property (retain) NSString* total;
@property (retain) NSString* stbTotal;
@property (retain) NSString* payStoreTotal;
@property (retain) NSString* stb;
@property int32_t type;
@end

@implementation MPay

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value {
  hasId_ = !!_value;
}
@synthesize id;
- (BOOL) hasCode {
  return !!hasCode_;
}
- (void) setHasCode:(BOOL) _value {
  hasCode_ = !!_value;
}
@synthesize code;
- (BOOL) hasPayType {
  return !!hasPayType_;
}
- (void) setHasPayType:(BOOL) _value {
  hasPayType_ = !!_value;
}
@synthesize payType;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) _value {
  hasName_ = !!_value;
}
@synthesize name;
- (BOOL) hasPrice {
  return !!hasPrice_;
}
- (void) setHasPrice:(BOOL) _value {
  hasPrice_ = !!_value;
}
@synthesize price;
- (BOOL) hasNum {
  return !!hasNum_;
}
- (void) setHasNum:(BOOL) _value {
  hasNum_ = !!_value;
}
@synthesize num;
- (BOOL) hasTotal {
  return !!hasTotal_;
}
- (void) setHasTotal:(BOOL) _value {
  hasTotal_ = !!_value;
}
@synthesize total;
- (BOOL) hasStbTotal {
  return !!hasStbTotal_;
}
- (void) setHasStbTotal:(BOOL) _value {
  hasStbTotal_ = !!_value;
}
@synthesize stbTotal;
- (BOOL) hasPayStoreTotal {
  return !!hasPayStoreTotal_;
}
- (void) setHasPayStoreTotal:(BOOL) _value {
  hasPayStoreTotal_ = !!_value;
}
@synthesize payStoreTotal;
- (BOOL) hasStb {
  return !!hasStb_;
}
- (void) setHasStb:(BOOL) _value {
  hasStb_ = !!_value;
}
@synthesize stb;
- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) _value {
  hasType_ = !!_value;
}
@synthesize type;
- (void) dealloc {
  self.id = nil;
  self.code = nil;
  self.name = nil;
  self.price = nil;
  self.total = nil;
  self.stbTotal = nil;
  self.payStoreTotal = nil;
  self.stb = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = @"";
    self.code = @"";
    self.payType = 0;
    self.name = @"";
    self.price = @"";
    self.num = 0;
    self.total = @"";
    self.stbTotal = @"";
    self.payStoreTotal = @"";
    self.stb = @"";
    self.type = 0;
  }
  return self;
}
static MPay* defaultMPayInstance = nil;
+ (void) initialize {
  if (self == [MPay class]) {
    defaultMPayInstance = [[MPay alloc] init];
  }
}
+ (MPay*) defaultInstance {
  return defaultMPayInstance;
}
- (MPay*) defaultInstance {
  return defaultMPayInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeString:1 value:self.id];
  }
  if (self.hasCode) {
    [output writeString:2 value:self.code];
  }
  if (self.hasPayType) {
    [output writeInt32:3 value:self.payType];
  }
  if (self.hasName) {
    [output writeString:4 value:self.name];
  }
  if (self.hasPrice) {
    [output writeString:5 value:self.price];
  }
  if (self.hasNum) {
    [output writeInt32:6 value:self.num];
  }
  if (self.hasTotal) {
    [output writeString:7 value:self.total];
  }
  if (self.hasStbTotal) {
    [output writeString:8 value:self.stbTotal];
  }
  if (self.hasPayStoreTotal) {
    [output writeString:9 value:self.payStoreTotal];
  }
  if (self.hasStb) {
    [output writeString:10 value:self.stb];
  }
  if (self.hasType) {
    [output writeInt32:11 value:self.type];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasId) {
    size += computeStringSize(1, self.id);
  }
  if (self.hasCode) {
    size += computeStringSize(2, self.code);
  }
  if (self.hasPayType) {
    size += computeInt32Size(3, self.payType);
  }
  if (self.hasName) {
    size += computeStringSize(4, self.name);
  }
  if (self.hasPrice) {
    size += computeStringSize(5, self.price);
  }
  if (self.hasNum) {
    size += computeInt32Size(6, self.num);
  }
  if (self.hasTotal) {
    size += computeStringSize(7, self.total);
  }
  if (self.hasStbTotal) {
    size += computeStringSize(8, self.stbTotal);
  }
  if (self.hasPayStoreTotal) {
    size += computeStringSize(9, self.payStoreTotal);
  }
  if (self.hasStb) {
    size += computeStringSize(10, self.stb);
  }
  if (self.hasType) {
    size += computeInt32Size(11, self.type);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MPay*) parseFromData:(NSData*) data {
  return (MPay*)[[[MPay builder] mergeFromData:data] build];
}
+ (MPay*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MPay*)[[[MPay builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MPay*) parseFromInputStream:(NSInputStream*) input {
  return (MPay*)[[[MPay builder] mergeFromInputStream:input] build];
}
+ (MPay*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MPay*)[[[MPay builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MPay*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MPay*)[[[MPay builder] mergeFromCodedInputStream:input] build];
}
+ (MPay*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MPay*)[[[MPay builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MPay_Builder*) builder {
  return [[[MPay_Builder alloc] init] autorelease];
}
+ (MPay_Builder*) builderWithPrototype:(MPay*) prototype {
  return [[MPay builder] mergeFrom:prototype];
}
- (MPay_Builder*) builder {
  return [MPay builder];
}
@end

@interface MPay_Builder()
@property (retain) MPay* protobufBuilderResult;
@end

@implementation MPay_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MPay alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MPay_Builder*) clear {
  self.protobufBuilderResult = [[[MPay alloc] init] autorelease];
  return self;
}
- (MPay_Builder*) clone {
  return [MPay builderWithPrototype:protobufBuilderResult];
}
- (MPay*) defaultInstance {
  return [MPay defaultInstance];
}
- (MPay*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MPay*) buildPartial {
  MPay* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MPay_Builder*) mergeFrom:(MPay*) other {
  if (other == [MPay defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasCode) {
    [self setCode:other.code];
  }
  if (other.hasPayType) {
    [self setPayType:other.payType];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasPrice) {
    [self setPrice:other.price];
  }
  if (other.hasNum) {
    [self setNum:other.num];
  }
  if (other.hasTotal) {
    [self setTotal:other.total];
  }
  if (other.hasStbTotal) {
    [self setStbTotal:other.stbTotal];
  }
  if (other.hasPayStoreTotal) {
    [self setPayStoreTotal:other.payStoreTotal];
  }
  if (other.hasStb) {
    [self setStb:other.stb];
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MPay_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MPay_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setId:[input readString]];
        break;
      }
      case 18: {
        [self setCode:[input readString]];
        break;
      }
      case 24: {
        [self setPayType:[input readInt32]];
        break;
      }
      case 34: {
        [self setName:[input readString]];
        break;
      }
      case 42: {
        [self setPrice:[input readString]];
        break;
      }
      case 48: {
        [self setNum:[input readInt32]];
        break;
      }
      case 58: {
        [self setTotal:[input readString]];
        break;
      }
      case 66: {
        [self setStbTotal:[input readString]];
        break;
      }
      case 74: {
        [self setPayStoreTotal:[input readString]];
        break;
      }
      case 82: {
        [self setStb:[input readString]];
        break;
      }
      case 88: {
        [self setType:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return protobufBuilderResult.hasId;
}
- (NSString*) id {
  return protobufBuilderResult.id;
}
- (MPay_Builder*) setId:(NSString*) _value {
  protobufBuilderResult.hasId = YES;
  protobufBuilderResult.id = _value;
  return self;
}
- (MPay_Builder*) clearId {
  protobufBuilderResult.hasId = NO;
  protobufBuilderResult.id = @"";
  return self;
}
- (BOOL) hasCode {
  return protobufBuilderResult.hasCode;
}
- (NSString*) code {
  return protobufBuilderResult.code;
}
- (MPay_Builder*) setCode:(NSString*) _value {
  protobufBuilderResult.hasCode = YES;
  protobufBuilderResult.code = _value;
  return self;
}
- (MPay_Builder*) clearCode {
  protobufBuilderResult.hasCode = NO;
  protobufBuilderResult.code = @"";
  return self;
}
- (BOOL) hasPayType {
  return protobufBuilderResult.hasPayType;
}
- (int32_t) payType {
  return protobufBuilderResult.payType;
}
- (MPay_Builder*) setPayType:(int32_t) _value {
  protobufBuilderResult.hasPayType = YES;
  protobufBuilderResult.payType = _value;
  return self;
}
- (MPay_Builder*) clearPayType {
  protobufBuilderResult.hasPayType = NO;
  protobufBuilderResult.payType = 0;
  return self;
}
- (BOOL) hasName {
  return protobufBuilderResult.hasName;
}
- (NSString*) name {
  return protobufBuilderResult.name;
}
- (MPay_Builder*) setName:(NSString*) _value {
  protobufBuilderResult.hasName = YES;
  protobufBuilderResult.name = _value;
  return self;
}
- (MPay_Builder*) clearName {
  protobufBuilderResult.hasName = NO;
  protobufBuilderResult.name = @"";
  return self;
}
- (BOOL) hasPrice {
  return protobufBuilderResult.hasPrice;
}
- (NSString*) price {
  return protobufBuilderResult.price;
}
- (MPay_Builder*) setPrice:(NSString*) _value {
  protobufBuilderResult.hasPrice = YES;
  protobufBuilderResult.price = _value;
  return self;
}
- (MPay_Builder*) clearPrice {
  protobufBuilderResult.hasPrice = NO;
  protobufBuilderResult.price = @"";
  return self;
}
- (BOOL) hasNum {
  return protobufBuilderResult.hasNum;
}
- (int32_t) num {
  return protobufBuilderResult.num;
}
- (MPay_Builder*) setNum:(int32_t) _value {
  protobufBuilderResult.hasNum = YES;
  protobufBuilderResult.num = _value;
  return self;
}
- (MPay_Builder*) clearNum {
  protobufBuilderResult.hasNum = NO;
  protobufBuilderResult.num = 0;
  return self;
}
- (BOOL) hasTotal {
  return protobufBuilderResult.hasTotal;
}
- (NSString*) total {
  return protobufBuilderResult.total;
}
- (MPay_Builder*) setTotal:(NSString*) _value {
  protobufBuilderResult.hasTotal = YES;
  protobufBuilderResult.total = _value;
  return self;
}
- (MPay_Builder*) clearTotal {
  protobufBuilderResult.hasTotal = NO;
  protobufBuilderResult.total = @"";
  return self;
}
- (BOOL) hasStbTotal {
  return protobufBuilderResult.hasStbTotal;
}
- (NSString*) stbTotal {
  return protobufBuilderResult.stbTotal;
}
- (MPay_Builder*) setStbTotal:(NSString*) _value {
  protobufBuilderResult.hasStbTotal = YES;
  protobufBuilderResult.stbTotal = _value;
  return self;
}
- (MPay_Builder*) clearStbTotal {
  protobufBuilderResult.hasStbTotal = NO;
  protobufBuilderResult.stbTotal = @"";
  return self;
}
- (BOOL) hasPayStoreTotal {
  return protobufBuilderResult.hasPayStoreTotal;
}
- (NSString*) payStoreTotal {
  return protobufBuilderResult.payStoreTotal;
}
- (MPay_Builder*) setPayStoreTotal:(NSString*) _value {
  protobufBuilderResult.hasPayStoreTotal = YES;
  protobufBuilderResult.payStoreTotal = _value;
  return self;
}
- (MPay_Builder*) clearPayStoreTotal {
  protobufBuilderResult.hasPayStoreTotal = NO;
  protobufBuilderResult.payStoreTotal = @"";
  return self;
}
- (BOOL) hasStb {
  return protobufBuilderResult.hasStb;
}
- (NSString*) stb {
  return protobufBuilderResult.stb;
}
- (MPay_Builder*) setStb:(NSString*) _value {
  protobufBuilderResult.hasStb = YES;
  protobufBuilderResult.stb = _value;
  return self;
}
- (MPay_Builder*) clearStb {
  protobufBuilderResult.hasStb = NO;
  protobufBuilderResult.stb = @"";
  return self;
}
- (BOOL) hasType {
  return protobufBuilderResult.hasType;
}
- (int32_t) type {
  return protobufBuilderResult.type;
}
- (MPay_Builder*) setType:(int32_t) _value {
  protobufBuilderResult.hasType = YES;
  protobufBuilderResult.type = _value;
  return self;
}
- (MPay_Builder*) clearType {
  protobufBuilderResult.hasType = NO;
  protobufBuilderResult.type = 0;
  return self;
}
@end

@interface MOrderMini ()
@property (retain) NSString* id;
@property int32_t payType;
@property (retain) NSString* goodsId;
@property (retain) NSString* name;
@property (retain) NSString* img;
@property int32_t num;
@property (retain) NSString* total;
@property int32_t state;
@property int32_t type;
@end

@implementation MOrderMini

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value {
  hasId_ = !!_value;
}
@synthesize id;
- (BOOL) hasPayType {
  return !!hasPayType_;
}
- (void) setHasPayType:(BOOL) _value {
  hasPayType_ = !!_value;
}
@synthesize payType;
- (BOOL) hasGoodsId {
  return !!hasGoodsId_;
}
- (void) setHasGoodsId:(BOOL) _value {
  hasGoodsId_ = !!_value;
}
@synthesize goodsId;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) _value {
  hasName_ = !!_value;
}
@synthesize name;
- (BOOL) hasImg {
  return !!hasImg_;
}
- (void) setHasImg:(BOOL) _value {
  hasImg_ = !!_value;
}
@synthesize img;
- (BOOL) hasNum {
  return !!hasNum_;
}
- (void) setHasNum:(BOOL) _value {
  hasNum_ = !!_value;
}
@synthesize num;
- (BOOL) hasTotal {
  return !!hasTotal_;
}
- (void) setHasTotal:(BOOL) _value {
  hasTotal_ = !!_value;
}
@synthesize total;
- (BOOL) hasState {
  return !!hasState_;
}
- (void) setHasState:(BOOL) _value {
  hasState_ = !!_value;
}
@synthesize state;
- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) _value {
  hasType_ = !!_value;
}
@synthesize type;
- (void) dealloc {
  self.id = nil;
  self.goodsId = nil;
  self.name = nil;
  self.img = nil;
  self.total = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = @"";
    self.payType = 0;
    self.goodsId = @"";
    self.name = @"";
    self.img = @"";
    self.num = 0;
    self.total = @"";
    self.state = 0;
    self.type = 0;
  }
  return self;
}
static MOrderMini* defaultMOrderMiniInstance = nil;
+ (void) initialize {
  if (self == [MOrderMini class]) {
    defaultMOrderMiniInstance = [[MOrderMini alloc] init];
  }
}
+ (MOrderMini*) defaultInstance {
  return defaultMOrderMiniInstance;
}
- (MOrderMini*) defaultInstance {
  return defaultMOrderMiniInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeString:1 value:self.id];
  }
  if (self.hasPayType) {
    [output writeInt32:2 value:self.payType];
  }
  if (self.hasGoodsId) {
    [output writeString:3 value:self.goodsId];
  }
  if (self.hasName) {
    [output writeString:4 value:self.name];
  }
  if (self.hasImg) {
    [output writeString:5 value:self.img];
  }
  if (self.hasNum) {
    [output writeInt32:6 value:self.num];
  }
  if (self.hasTotal) {
    [output writeString:7 value:self.total];
  }
  if (self.hasState) {
    [output writeInt32:8 value:self.state];
  }
  if (self.hasType) {
    [output writeInt32:9 value:self.type];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasId) {
    size += computeStringSize(1, self.id);
  }
  if (self.hasPayType) {
    size += computeInt32Size(2, self.payType);
  }
  if (self.hasGoodsId) {
    size += computeStringSize(3, self.goodsId);
  }
  if (self.hasName) {
    size += computeStringSize(4, self.name);
  }
  if (self.hasImg) {
    size += computeStringSize(5, self.img);
  }
  if (self.hasNum) {
    size += computeInt32Size(6, self.num);
  }
  if (self.hasTotal) {
    size += computeStringSize(7, self.total);
  }
  if (self.hasState) {
    size += computeInt32Size(8, self.state);
  }
  if (self.hasType) {
    size += computeInt32Size(9, self.type);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MOrderMini*) parseFromData:(NSData*) data {
  return (MOrderMini*)[[[MOrderMini builder] mergeFromData:data] build];
}
+ (MOrderMini*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MOrderMini*)[[[MOrderMini builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MOrderMini*) parseFromInputStream:(NSInputStream*) input {
  return (MOrderMini*)[[[MOrderMini builder] mergeFromInputStream:input] build];
}
+ (MOrderMini*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MOrderMini*)[[[MOrderMini builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MOrderMini*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MOrderMini*)[[[MOrderMini builder] mergeFromCodedInputStream:input] build];
}
+ (MOrderMini*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MOrderMini*)[[[MOrderMini builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MOrderMini_Builder*) builder {
  return [[[MOrderMini_Builder alloc] init] autorelease];
}
+ (MOrderMini_Builder*) builderWithPrototype:(MOrderMini*) prototype {
  return [[MOrderMini builder] mergeFrom:prototype];
}
- (MOrderMini_Builder*) builder {
  return [MOrderMini builder];
}
@end

@interface MOrderMini_Builder()
@property (retain) MOrderMini* protobufBuilderResult;
@end

@implementation MOrderMini_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MOrderMini alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MOrderMini_Builder*) clear {
  self.protobufBuilderResult = [[[MOrderMini alloc] init] autorelease];
  return self;
}
- (MOrderMini_Builder*) clone {
  return [MOrderMini builderWithPrototype:protobufBuilderResult];
}
- (MOrderMini*) defaultInstance {
  return [MOrderMini defaultInstance];
}
- (MOrderMini*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MOrderMini*) buildPartial {
  MOrderMini* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MOrderMini_Builder*) mergeFrom:(MOrderMini*) other {
  if (other == [MOrderMini defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasPayType) {
    [self setPayType:other.payType];
  }
  if (other.hasGoodsId) {
    [self setGoodsId:other.goodsId];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasImg) {
    [self setImg:other.img];
  }
  if (other.hasNum) {
    [self setNum:other.num];
  }
  if (other.hasTotal) {
    [self setTotal:other.total];
  }
  if (other.hasState) {
    [self setState:other.state];
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MOrderMini_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MOrderMini_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setId:[input readString]];
        break;
      }
      case 16: {
        [self setPayType:[input readInt32]];
        break;
      }
      case 26: {
        [self setGoodsId:[input readString]];
        break;
      }
      case 34: {
        [self setName:[input readString]];
        break;
      }
      case 42: {
        [self setImg:[input readString]];
        break;
      }
      case 48: {
        [self setNum:[input readInt32]];
        break;
      }
      case 58: {
        [self setTotal:[input readString]];
        break;
      }
      case 64: {
        [self setState:[input readInt32]];
        break;
      }
      case 72: {
        [self setType:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return protobufBuilderResult.hasId;
}
- (NSString*) id {
  return protobufBuilderResult.id;
}
- (MOrderMini_Builder*) setId:(NSString*) _value {
  protobufBuilderResult.hasId = YES;
  protobufBuilderResult.id = _value;
  return self;
}
- (MOrderMini_Builder*) clearId {
  protobufBuilderResult.hasId = NO;
  protobufBuilderResult.id = @"";
  return self;
}
- (BOOL) hasPayType {
  return protobufBuilderResult.hasPayType;
}
- (int32_t) payType {
  return protobufBuilderResult.payType;
}
- (MOrderMini_Builder*) setPayType:(int32_t) _value {
  protobufBuilderResult.hasPayType = YES;
  protobufBuilderResult.payType = _value;
  return self;
}
- (MOrderMini_Builder*) clearPayType {
  protobufBuilderResult.hasPayType = NO;
  protobufBuilderResult.payType = 0;
  return self;
}
- (BOOL) hasGoodsId {
  return protobufBuilderResult.hasGoodsId;
}
- (NSString*) goodsId {
  return protobufBuilderResult.goodsId;
}
- (MOrderMini_Builder*) setGoodsId:(NSString*) _value {
  protobufBuilderResult.hasGoodsId = YES;
  protobufBuilderResult.goodsId = _value;
  return self;
}
- (MOrderMini_Builder*) clearGoodsId {
  protobufBuilderResult.hasGoodsId = NO;
  protobufBuilderResult.goodsId = @"";
  return self;
}
- (BOOL) hasName {
  return protobufBuilderResult.hasName;
}
- (NSString*) name {
  return protobufBuilderResult.name;
}
- (MOrderMini_Builder*) setName:(NSString*) _value {
  protobufBuilderResult.hasName = YES;
  protobufBuilderResult.name = _value;
  return self;
}
- (MOrderMini_Builder*) clearName {
  protobufBuilderResult.hasName = NO;
  protobufBuilderResult.name = @"";
  return self;
}
- (BOOL) hasImg {
  return protobufBuilderResult.hasImg;
}
- (NSString*) img {
  return protobufBuilderResult.img;
}
- (MOrderMini_Builder*) setImg:(NSString*) _value {
  protobufBuilderResult.hasImg = YES;
  protobufBuilderResult.img = _value;
  return self;
}
- (MOrderMini_Builder*) clearImg {
  protobufBuilderResult.hasImg = NO;
  protobufBuilderResult.img = @"";
  return self;
}
- (BOOL) hasNum {
  return protobufBuilderResult.hasNum;
}
- (int32_t) num {
  return protobufBuilderResult.num;
}
- (MOrderMini_Builder*) setNum:(int32_t) _value {
  protobufBuilderResult.hasNum = YES;
  protobufBuilderResult.num = _value;
  return self;
}
- (MOrderMini_Builder*) clearNum {
  protobufBuilderResult.hasNum = NO;
  protobufBuilderResult.num = 0;
  return self;
}
- (BOOL) hasTotal {
  return protobufBuilderResult.hasTotal;
}
- (NSString*) total {
  return protobufBuilderResult.total;
}
- (MOrderMini_Builder*) setTotal:(NSString*) _value {
  protobufBuilderResult.hasTotal = YES;
  protobufBuilderResult.total = _value;
  return self;
}
- (MOrderMini_Builder*) clearTotal {
  protobufBuilderResult.hasTotal = NO;
  protobufBuilderResult.total = @"";
  return self;
}
- (BOOL) hasState {
  return protobufBuilderResult.hasState;
}
- (int32_t) state {
  return protobufBuilderResult.state;
}
- (MOrderMini_Builder*) setState:(int32_t) _value {
  protobufBuilderResult.hasState = YES;
  protobufBuilderResult.state = _value;
  return self;
}
- (MOrderMini_Builder*) clearState {
  protobufBuilderResult.hasState = NO;
  protobufBuilderResult.state = 0;
  return self;
}
- (BOOL) hasType {
  return protobufBuilderResult.hasType;
}
- (int32_t) type {
  return protobufBuilderResult.type;
}
- (MOrderMini_Builder*) setType:(int32_t) _value {
  protobufBuilderResult.hasType = YES;
  protobufBuilderResult.type = _value;
  return self;
}
- (MOrderMini_Builder*) clearType {
  protobufBuilderResult.hasType = NO;
  protobufBuilderResult.type = 0;
  return self;
}
@end

@interface MOrderMiniList ()
@property (retain) NSMutableArray* mutableListList;
@end

@implementation MOrderMiniList

@synthesize mutableListList;
- (void) dealloc {
  self.mutableListList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static MOrderMiniList* defaultMOrderMiniListInstance = nil;
+ (void) initialize {
  if (self == [MOrderMiniList class]) {
    defaultMOrderMiniListInstance = [[MOrderMiniList alloc] init];
  }
}
+ (MOrderMiniList*) defaultInstance {
  return defaultMOrderMiniListInstance;
}
- (MOrderMiniList*) defaultInstance {
  return defaultMOrderMiniListInstance;
}
- (NSArray*) listList {
  return mutableListList;
}
- (MOrderMini*) listAtIndex:(int32_t) index {
  id _value = [mutableListList objectAtIndex:index];
  return _value;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (MOrderMini* element in self.listList) {
    [output writeMessage:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  for (MOrderMini* element in self.listList) {
    size += computeMessageSize(1, element);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MOrderMiniList*) parseFromData:(NSData*) data {
  return (MOrderMiniList*)[[[MOrderMiniList builder] mergeFromData:data] build];
}
+ (MOrderMiniList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MOrderMiniList*)[[[MOrderMiniList builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MOrderMiniList*) parseFromInputStream:(NSInputStream*) input {
  return (MOrderMiniList*)[[[MOrderMiniList builder] mergeFromInputStream:input] build];
}
+ (MOrderMiniList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MOrderMiniList*)[[[MOrderMiniList builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MOrderMiniList*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MOrderMiniList*)[[[MOrderMiniList builder] mergeFromCodedInputStream:input] build];
}
+ (MOrderMiniList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MOrderMiniList*)[[[MOrderMiniList builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MOrderMiniList_Builder*) builder {
  return [[[MOrderMiniList_Builder alloc] init] autorelease];
}
+ (MOrderMiniList_Builder*) builderWithPrototype:(MOrderMiniList*) prototype {
  return [[MOrderMiniList builder] mergeFrom:prototype];
}
- (MOrderMiniList_Builder*) builder {
  return [MOrderMiniList builder];
}
@end

@interface MOrderMiniList_Builder()
@property (retain) MOrderMiniList* protobufBuilderResult;
@end

@implementation MOrderMiniList_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MOrderMiniList alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MOrderMiniList_Builder*) clear {
  self.protobufBuilderResult = [[[MOrderMiniList alloc] init] autorelease];
  return self;
}
- (MOrderMiniList_Builder*) clone {
  return [MOrderMiniList builderWithPrototype:protobufBuilderResult];
}
- (MOrderMiniList*) defaultInstance {
  return [MOrderMiniList defaultInstance];
}
- (MOrderMiniList*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MOrderMiniList*) buildPartial {
  MOrderMiniList* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MOrderMiniList_Builder*) mergeFrom:(MOrderMiniList*) other {
  if (other == [MOrderMiniList defaultInstance]) {
    return self;
  }
  if (other.mutableListList.count > 0) {
    if (protobufBuilderResult.mutableListList == nil) {
      protobufBuilderResult.mutableListList = [NSMutableArray array];
    }
    [protobufBuilderResult.mutableListList addObjectsFromArray:other.mutableListList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MOrderMiniList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MOrderMiniList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        MOrderMini_Builder* subBuilder = [MOrderMini builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addList:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSArray*) listList {
  if (protobufBuilderResult.mutableListList == nil) { return [NSArray array]; }
  return protobufBuilderResult.mutableListList;
}
- (MOrderMini*) listAtIndex:(int32_t) index {
  return [protobufBuilderResult listAtIndex:index];
}
- (MOrderMiniList_Builder*) replaceListAtIndex:(int32_t) index with:(MOrderMini*) _value {
  [protobufBuilderResult.mutableListList replaceObjectAtIndex:index withObject:_value];
  return self;
}
- (MOrderMiniList_Builder*) addAllList:(NSArray*) values {
  if (protobufBuilderResult.mutableListList == nil) {
    protobufBuilderResult.mutableListList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableListList addObjectsFromArray:values];
  return self;
}
- (MOrderMiniList_Builder*) clearListList {
  protobufBuilderResult.mutableListList = nil;
  return self;
}
- (MOrderMiniList_Builder*) addList:(MOrderMini*) _value {
  if (protobufBuilderResult.mutableListList == nil) {
    protobufBuilderResult.mutableListList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableListList addObject:_value];
  return self;
}
@end

@interface MOrder ()
@property (retain) NSString* id;
@property (retain) NSString* code;
@property int32_t state;
@property int32_t payType;
@property int32_t type;
@property (retain) NSString* goodsId;
@property (retain) NSString* name;
@property (retain) NSString* info;
@property (retain) NSString* price;
@property (retain) NSString* img;
@property int32_t num;
@property (retain) NSString* commentId;
@property (retain) NSString* commentStars;
@property (retain) NSString* deadline;
@property (retain) NSMutableArray* mutableTicketsList;
@property (retain) NSString* combo;
@property (retain) NSString* detailUrl;
@property (retain) NSString* payTime;
@property (retain) NSString* payTotal;
@property (retain) NSString* stbTotal;
@property (retain) NSString* storeTotal;
@end

@implementation MOrder

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value {
  hasId_ = !!_value;
}
@synthesize id;
- (BOOL) hasCode {
  return !!hasCode_;
}
- (void) setHasCode:(BOOL) _value {
  hasCode_ = !!_value;
}
@synthesize code;
- (BOOL) hasState {
  return !!hasState_;
}
- (void) setHasState:(BOOL) _value {
  hasState_ = !!_value;
}
@synthesize state;
- (BOOL) hasPayType {
  return !!hasPayType_;
}
- (void) setHasPayType:(BOOL) _value {
  hasPayType_ = !!_value;
}
@synthesize payType;
- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) _value {
  hasType_ = !!_value;
}
@synthesize type;
- (BOOL) hasGoodsId {
  return !!hasGoodsId_;
}
- (void) setHasGoodsId:(BOOL) _value {
  hasGoodsId_ = !!_value;
}
@synthesize goodsId;
- (BOOL) hasName {
  return !!hasName_;
}
- (void) setHasName:(BOOL) _value {
  hasName_ = !!_value;
}
@synthesize name;
- (BOOL) hasInfo {
  return !!hasInfo_;
}
- (void) setHasInfo:(BOOL) _value {
  hasInfo_ = !!_value;
}
@synthesize info;
- (BOOL) hasPrice {
  return !!hasPrice_;
}
- (void) setHasPrice:(BOOL) _value {
  hasPrice_ = !!_value;
}
@synthesize price;
- (BOOL) hasImg {
  return !!hasImg_;
}
- (void) setHasImg:(BOOL) _value {
  hasImg_ = !!_value;
}
@synthesize img;
- (BOOL) hasNum {
  return !!hasNum_;
}
- (void) setHasNum:(BOOL) _value {
  hasNum_ = !!_value;
}
@synthesize num;
- (BOOL) hasCommentId {
  return !!hasCommentId_;
}
- (void) setHasCommentId:(BOOL) _value {
  hasCommentId_ = !!_value;
}
@synthesize commentId;
- (BOOL) hasCommentStars {
  return !!hasCommentStars_;
}
- (void) setHasCommentStars:(BOOL) _value {
  hasCommentStars_ = !!_value;
}
@synthesize commentStars;
- (BOOL) hasDeadline {
  return !!hasDeadline_;
}
- (void) setHasDeadline:(BOOL) _value {
  hasDeadline_ = !!_value;
}
@synthesize deadline;
@synthesize mutableTicketsList;
- (BOOL) hasCombo {
  return !!hasCombo_;
}
- (void) setHasCombo:(BOOL) _value {
  hasCombo_ = !!_value;
}
@synthesize combo;
- (BOOL) hasDetailUrl {
  return !!hasDetailUrl_;
}
- (void) setHasDetailUrl:(BOOL) _value {
  hasDetailUrl_ = !!_value;
}
@synthesize detailUrl;
- (BOOL) hasPayTime {
  return !!hasPayTime_;
}
- (void) setHasPayTime:(BOOL) _value {
  hasPayTime_ = !!_value;
}
@synthesize payTime;
- (BOOL) hasPayTotal {
  return !!hasPayTotal_;
}
- (void) setHasPayTotal:(BOOL) _value {
  hasPayTotal_ = !!_value;
}
@synthesize payTotal;
- (BOOL) hasStbTotal {
  return !!hasStbTotal_;
}
- (void) setHasStbTotal:(BOOL) _value {
  hasStbTotal_ = !!_value;
}
@synthesize stbTotal;
- (BOOL) hasStoreTotal {
  return !!hasStoreTotal_;
}
- (void) setHasStoreTotal:(BOOL) _value {
  hasStoreTotal_ = !!_value;
}
@synthesize storeTotal;
- (void) dealloc {
  self.id = nil;
  self.code = nil;
  self.goodsId = nil;
  self.name = nil;
  self.info = nil;
  self.price = nil;
  self.img = nil;
  self.commentId = nil;
  self.commentStars = nil;
  self.deadline = nil;
  self.mutableTicketsList = nil;
  self.combo = nil;
  self.detailUrl = nil;
  self.payTime = nil;
  self.payTotal = nil;
  self.stbTotal = nil;
  self.storeTotal = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = @"";
    self.code = @"";
    self.state = 0;
    self.payType = 0;
    self.type = 0;
    self.goodsId = @"";
    self.name = @"";
    self.info = @"";
    self.price = @"";
    self.img = @"";
    self.num = 0;
    self.commentId = @"";
    self.commentStars = @"";
    self.deadline = @"";
    self.combo = @"";
    self.detailUrl = @"";
    self.payTime = @"";
    self.payTotal = @"";
    self.stbTotal = @"";
    self.storeTotal = @"";
  }
  return self;
}
static MOrder* defaultMOrderInstance = nil;
+ (void) initialize {
  if (self == [MOrder class]) {
    defaultMOrderInstance = [[MOrder alloc] init];
  }
}
+ (MOrder*) defaultInstance {
  return defaultMOrderInstance;
}
- (MOrder*) defaultInstance {
  return defaultMOrderInstance;
}
- (NSArray*) ticketsList {
  return mutableTicketsList;
}
- (NSString*) ticketsAtIndex:(int32_t) index {
  id _value = [mutableTicketsList objectAtIndex:index];
  return _value;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeString:1 value:self.id];
  }
  if (self.hasCode) {
    [output writeString:2 value:self.code];
  }
  if (self.hasState) {
    [output writeInt32:3 value:self.state];
  }
  if (self.hasPayType) {
    [output writeInt32:4 value:self.payType];
  }
  if (self.hasType) {
    [output writeInt32:5 value:self.type];
  }
  if (self.hasGoodsId) {
    [output writeString:6 value:self.goodsId];
  }
  if (self.hasName) {
    [output writeString:7 value:self.name];
  }
  if (self.hasInfo) {
    [output writeString:8 value:self.info];
  }
  if (self.hasPrice) {
    [output writeString:9 value:self.price];
  }
  if (self.hasImg) {
    [output writeString:10 value:self.img];
  }
  if (self.hasNum) {
    [output writeInt32:11 value:self.num];
  }
  if (self.hasCommentId) {
    [output writeString:12 value:self.commentId];
  }
  if (self.hasCommentStars) {
    [output writeString:13 value:self.commentStars];
  }
  if (self.hasDeadline) {
    [output writeString:14 value:self.deadline];
  }
  for (NSString* element in self.mutableTicketsList) {
    [output writeString:15 value:element];
  }
  if (self.hasCombo) {
    [output writeString:16 value:self.combo];
  }
  if (self.hasDetailUrl) {
    [output writeString:17 value:self.detailUrl];
  }
  if (self.hasPayTime) {
    [output writeString:18 value:self.payTime];
  }
  if (self.hasPayTotal) {
    [output writeString:19 value:self.payTotal];
  }
  if (self.hasStbTotal) {
    [output writeString:20 value:self.stbTotal];
  }
  if (self.hasStoreTotal) {
    [output writeString:21 value:self.storeTotal];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasId) {
    size += computeStringSize(1, self.id);
  }
  if (self.hasCode) {
    size += computeStringSize(2, self.code);
  }
  if (self.hasState) {
    size += computeInt32Size(3, self.state);
  }
  if (self.hasPayType) {
    size += computeInt32Size(4, self.payType);
  }
  if (self.hasType) {
    size += computeInt32Size(5, self.type);
  }
  if (self.hasGoodsId) {
    size += computeStringSize(6, self.goodsId);
  }
  if (self.hasName) {
    size += computeStringSize(7, self.name);
  }
  if (self.hasInfo) {
    size += computeStringSize(8, self.info);
  }
  if (self.hasPrice) {
    size += computeStringSize(9, self.price);
  }
  if (self.hasImg) {
    size += computeStringSize(10, self.img);
  }
  if (self.hasNum) {
    size += computeInt32Size(11, self.num);
  }
  if (self.hasCommentId) {
    size += computeStringSize(12, self.commentId);
  }
  if (self.hasCommentStars) {
    size += computeStringSize(13, self.commentStars);
  }
  if (self.hasDeadline) {
    size += computeStringSize(14, self.deadline);
  }
  {
    int32_t dataSize = 0;
    for (NSString* element in self.mutableTicketsList) {
      dataSize += computeStringSizeNoTag(element);
    }
    size += dataSize;
    size += 1 * self.mutableTicketsList.count;
  }
  if (self.hasCombo) {
    size += computeStringSize(16, self.combo);
  }
  if (self.hasDetailUrl) {
    size += computeStringSize(17, self.detailUrl);
  }
  if (self.hasPayTime) {
    size += computeStringSize(18, self.payTime);
  }
  if (self.hasPayTotal) {
    size += computeStringSize(19, self.payTotal);
  }
  if (self.hasStbTotal) {
    size += computeStringSize(20, self.stbTotal);
  }
  if (self.hasStoreTotal) {
    size += computeStringSize(21, self.storeTotal);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MOrder*) parseFromData:(NSData*) data {
  return (MOrder*)[[[MOrder builder] mergeFromData:data] build];
}
+ (MOrder*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MOrder*)[[[MOrder builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MOrder*) parseFromInputStream:(NSInputStream*) input {
  return (MOrder*)[[[MOrder builder] mergeFromInputStream:input] build];
}
+ (MOrder*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MOrder*)[[[MOrder builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MOrder*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MOrder*)[[[MOrder builder] mergeFromCodedInputStream:input] build];
}
+ (MOrder*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MOrder*)[[[MOrder builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MOrder_Builder*) builder {
  return [[[MOrder_Builder alloc] init] autorelease];
}
+ (MOrder_Builder*) builderWithPrototype:(MOrder*) prototype {
  return [[MOrder builder] mergeFrom:prototype];
}
- (MOrder_Builder*) builder {
  return [MOrder builder];
}
@end

@interface MOrder_Builder()
@property (retain) MOrder* protobufBuilderResult;
@end

@implementation MOrder_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MOrder alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MOrder_Builder*) clear {
  self.protobufBuilderResult = [[[MOrder alloc] init] autorelease];
  return self;
}
- (MOrder_Builder*) clone {
  return [MOrder builderWithPrototype:protobufBuilderResult];
}
- (MOrder*) defaultInstance {
  return [MOrder defaultInstance];
}
- (MOrder*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MOrder*) buildPartial {
  MOrder* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MOrder_Builder*) mergeFrom:(MOrder*) other {
  if (other == [MOrder defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasCode) {
    [self setCode:other.code];
  }
  if (other.hasState) {
    [self setState:other.state];
  }
  if (other.hasPayType) {
    [self setPayType:other.payType];
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  if (other.hasGoodsId) {
    [self setGoodsId:other.goodsId];
  }
  if (other.hasName) {
    [self setName:other.name];
  }
  if (other.hasInfo) {
    [self setInfo:other.info];
  }
  if (other.hasPrice) {
    [self setPrice:other.price];
  }
  if (other.hasImg) {
    [self setImg:other.img];
  }
  if (other.hasNum) {
    [self setNum:other.num];
  }
  if (other.hasCommentId) {
    [self setCommentId:other.commentId];
  }
  if (other.hasCommentStars) {
    [self setCommentStars:other.commentStars];
  }
  if (other.hasDeadline) {
    [self setDeadline:other.deadline];
  }
  if (other.mutableTicketsList.count > 0) {
    if (protobufBuilderResult.mutableTicketsList == nil) {
      protobufBuilderResult.mutableTicketsList = [NSMutableArray array];
    }
    [protobufBuilderResult.mutableTicketsList addObjectsFromArray:other.mutableTicketsList];
  }
  if (other.hasCombo) {
    [self setCombo:other.combo];
  }
  if (other.hasDetailUrl) {
    [self setDetailUrl:other.detailUrl];
  }
  if (other.hasPayTime) {
    [self setPayTime:other.payTime];
  }
  if (other.hasPayTotal) {
    [self setPayTotal:other.payTotal];
  }
  if (other.hasStbTotal) {
    [self setStbTotal:other.stbTotal];
  }
  if (other.hasStoreTotal) {
    [self setStoreTotal:other.storeTotal];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MOrder_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MOrder_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setId:[input readString]];
        break;
      }
      case 18: {
        [self setCode:[input readString]];
        break;
      }
      case 24: {
        [self setState:[input readInt32]];
        break;
      }
      case 32: {
        [self setPayType:[input readInt32]];
        break;
      }
      case 40: {
        [self setType:[input readInt32]];
        break;
      }
      case 50: {
        [self setGoodsId:[input readString]];
        break;
      }
      case 58: {
        [self setName:[input readString]];
        break;
      }
      case 66: {
        [self setInfo:[input readString]];
        break;
      }
      case 74: {
        [self setPrice:[input readString]];
        break;
      }
      case 82: {
        [self setImg:[input readString]];
        break;
      }
      case 88: {
        [self setNum:[input readInt32]];
        break;
      }
      case 98: {
        [self setCommentId:[input readString]];
        break;
      }
      case 106: {
        [self setCommentStars:[input readString]];
        break;
      }
      case 114: {
        [self setDeadline:[input readString]];
        break;
      }
      case 122: {
        [self addTickets:[input readString]];
        break;
      }
      case 130: {
        [self setCombo:[input readString]];
        break;
      }
      case 138: {
        [self setDetailUrl:[input readString]];
        break;
      }
      case 146: {
        [self setPayTime:[input readString]];
        break;
      }
      case 154: {
        [self setPayTotal:[input readString]];
        break;
      }
      case 162: {
        [self setStbTotal:[input readString]];
        break;
      }
      case 170: {
        [self setStoreTotal:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return protobufBuilderResult.hasId;
}
- (NSString*) id {
  return protobufBuilderResult.id;
}
- (MOrder_Builder*) setId:(NSString*) _value {
  protobufBuilderResult.hasId = YES;
  protobufBuilderResult.id = _value;
  return self;
}
- (MOrder_Builder*) clearId {
  protobufBuilderResult.hasId = NO;
  protobufBuilderResult.id = @"";
  return self;
}
- (BOOL) hasCode {
  return protobufBuilderResult.hasCode;
}
- (NSString*) code {
  return protobufBuilderResult.code;
}
- (MOrder_Builder*) setCode:(NSString*) _value {
  protobufBuilderResult.hasCode = YES;
  protobufBuilderResult.code = _value;
  return self;
}
- (MOrder_Builder*) clearCode {
  protobufBuilderResult.hasCode = NO;
  protobufBuilderResult.code = @"";
  return self;
}
- (BOOL) hasState {
  return protobufBuilderResult.hasState;
}
- (int32_t) state {
  return protobufBuilderResult.state;
}
- (MOrder_Builder*) setState:(int32_t) _value {
  protobufBuilderResult.hasState = YES;
  protobufBuilderResult.state = _value;
  return self;
}
- (MOrder_Builder*) clearState {
  protobufBuilderResult.hasState = NO;
  protobufBuilderResult.state = 0;
  return self;
}
- (BOOL) hasPayType {
  return protobufBuilderResult.hasPayType;
}
- (int32_t) payType {
  return protobufBuilderResult.payType;
}
- (MOrder_Builder*) setPayType:(int32_t) _value {
  protobufBuilderResult.hasPayType = YES;
  protobufBuilderResult.payType = _value;
  return self;
}
- (MOrder_Builder*) clearPayType {
  protobufBuilderResult.hasPayType = NO;
  protobufBuilderResult.payType = 0;
  return self;
}
- (BOOL) hasType {
  return protobufBuilderResult.hasType;
}
- (int32_t) type {
  return protobufBuilderResult.type;
}
- (MOrder_Builder*) setType:(int32_t) _value {
  protobufBuilderResult.hasType = YES;
  protobufBuilderResult.type = _value;
  return self;
}
- (MOrder_Builder*) clearType {
  protobufBuilderResult.hasType = NO;
  protobufBuilderResult.type = 0;
  return self;
}
- (BOOL) hasGoodsId {
  return protobufBuilderResult.hasGoodsId;
}
- (NSString*) goodsId {
  return protobufBuilderResult.goodsId;
}
- (MOrder_Builder*) setGoodsId:(NSString*) _value {
  protobufBuilderResult.hasGoodsId = YES;
  protobufBuilderResult.goodsId = _value;
  return self;
}
- (MOrder_Builder*) clearGoodsId {
  protobufBuilderResult.hasGoodsId = NO;
  protobufBuilderResult.goodsId = @"";
  return self;
}
- (BOOL) hasName {
  return protobufBuilderResult.hasName;
}
- (NSString*) name {
  return protobufBuilderResult.name;
}
- (MOrder_Builder*) setName:(NSString*) _value {
  protobufBuilderResult.hasName = YES;
  protobufBuilderResult.name = _value;
  return self;
}
- (MOrder_Builder*) clearName {
  protobufBuilderResult.hasName = NO;
  protobufBuilderResult.name = @"";
  return self;
}
- (BOOL) hasInfo {
  return protobufBuilderResult.hasInfo;
}
- (NSString*) info {
  return protobufBuilderResult.info;
}
- (MOrder_Builder*) setInfo:(NSString*) _value {
  protobufBuilderResult.hasInfo = YES;
  protobufBuilderResult.info = _value;
  return self;
}
- (MOrder_Builder*) clearInfo {
  protobufBuilderResult.hasInfo = NO;
  protobufBuilderResult.info = @"";
  return self;
}
- (BOOL) hasPrice {
  return protobufBuilderResult.hasPrice;
}
- (NSString*) price {
  return protobufBuilderResult.price;
}
- (MOrder_Builder*) setPrice:(NSString*) _value {
  protobufBuilderResult.hasPrice = YES;
  protobufBuilderResult.price = _value;
  return self;
}
- (MOrder_Builder*) clearPrice {
  protobufBuilderResult.hasPrice = NO;
  protobufBuilderResult.price = @"";
  return self;
}
- (BOOL) hasImg {
  return protobufBuilderResult.hasImg;
}
- (NSString*) img {
  return protobufBuilderResult.img;
}
- (MOrder_Builder*) setImg:(NSString*) _value {
  protobufBuilderResult.hasImg = YES;
  protobufBuilderResult.img = _value;
  return self;
}
- (MOrder_Builder*) clearImg {
  protobufBuilderResult.hasImg = NO;
  protobufBuilderResult.img = @"";
  return self;
}
- (BOOL) hasNum {
  return protobufBuilderResult.hasNum;
}
- (int32_t) num {
  return protobufBuilderResult.num;
}
- (MOrder_Builder*) setNum:(int32_t) _value {
  protobufBuilderResult.hasNum = YES;
  protobufBuilderResult.num = _value;
  return self;
}
- (MOrder_Builder*) clearNum {
  protobufBuilderResult.hasNum = NO;
  protobufBuilderResult.num = 0;
  return self;
}
- (BOOL) hasCommentId {
  return protobufBuilderResult.hasCommentId;
}
- (NSString*) commentId {
  return protobufBuilderResult.commentId;
}
- (MOrder_Builder*) setCommentId:(NSString*) _value {
  protobufBuilderResult.hasCommentId = YES;
  protobufBuilderResult.commentId = _value;
  return self;
}
- (MOrder_Builder*) clearCommentId {
  protobufBuilderResult.hasCommentId = NO;
  protobufBuilderResult.commentId = @"";
  return self;
}
- (BOOL) hasCommentStars {
  return protobufBuilderResult.hasCommentStars;
}
- (NSString*) commentStars {
  return protobufBuilderResult.commentStars;
}
- (MOrder_Builder*) setCommentStars:(NSString*) _value {
  protobufBuilderResult.hasCommentStars = YES;
  protobufBuilderResult.commentStars = _value;
  return self;
}
- (MOrder_Builder*) clearCommentStars {
  protobufBuilderResult.hasCommentStars = NO;
  protobufBuilderResult.commentStars = @"";
  return self;
}
- (BOOL) hasDeadline {
  return protobufBuilderResult.hasDeadline;
}
- (NSString*) deadline {
  return protobufBuilderResult.deadline;
}
- (MOrder_Builder*) setDeadline:(NSString*) _value {
  protobufBuilderResult.hasDeadline = YES;
  protobufBuilderResult.deadline = _value;
  return self;
}
- (MOrder_Builder*) clearDeadline {
  protobufBuilderResult.hasDeadline = NO;
  protobufBuilderResult.deadline = @"";
  return self;
}
- (NSArray*) ticketsList {
  if (protobufBuilderResult.mutableTicketsList == nil) {
    return [NSArray array];
  }
  return protobufBuilderResult.mutableTicketsList;
}
- (NSString*) ticketsAtIndex:(int32_t) index {
  return [protobufBuilderResult ticketsAtIndex:index];
}
- (MOrder_Builder*) replaceTicketsAtIndex:(int32_t) index with:(NSString*) _value {
  [protobufBuilderResult.mutableTicketsList replaceObjectAtIndex:index withObject:_value];
  return self;
}
- (MOrder_Builder*) addTickets:(NSString*) _value {
  if (protobufBuilderResult.mutableTicketsList == nil) {
    protobufBuilderResult.mutableTicketsList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableTicketsList addObject:_value];
  return self;
}
- (MOrder_Builder*) addAllTickets:(NSArray*) values {
  if (protobufBuilderResult.mutableTicketsList == nil) {
    protobufBuilderResult.mutableTicketsList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableTicketsList addObjectsFromArray:values];
  return self;
}
- (MOrder_Builder*) clearTicketsList {
  protobufBuilderResult.mutableTicketsList = nil;
  return self;
}
- (BOOL) hasCombo {
  return protobufBuilderResult.hasCombo;
}
- (NSString*) combo {
  return protobufBuilderResult.combo;
}
- (MOrder_Builder*) setCombo:(NSString*) _value {
  protobufBuilderResult.hasCombo = YES;
  protobufBuilderResult.combo = _value;
  return self;
}
- (MOrder_Builder*) clearCombo {
  protobufBuilderResult.hasCombo = NO;
  protobufBuilderResult.combo = @"";
  return self;
}
- (BOOL) hasDetailUrl {
  return protobufBuilderResult.hasDetailUrl;
}
- (NSString*) detailUrl {
  return protobufBuilderResult.detailUrl;
}
- (MOrder_Builder*) setDetailUrl:(NSString*) _value {
  protobufBuilderResult.hasDetailUrl = YES;
  protobufBuilderResult.detailUrl = _value;
  return self;
}
- (MOrder_Builder*) clearDetailUrl {
  protobufBuilderResult.hasDetailUrl = NO;
  protobufBuilderResult.detailUrl = @"";
  return self;
}
- (BOOL) hasPayTime {
  return protobufBuilderResult.hasPayTime;
}
- (NSString*) payTime {
  return protobufBuilderResult.payTime;
}
- (MOrder_Builder*) setPayTime:(NSString*) _value {
  protobufBuilderResult.hasPayTime = YES;
  protobufBuilderResult.payTime = _value;
  return self;
}
- (MOrder_Builder*) clearPayTime {
  protobufBuilderResult.hasPayTime = NO;
  protobufBuilderResult.payTime = @"";
  return self;
}
- (BOOL) hasPayTotal {
  return protobufBuilderResult.hasPayTotal;
}
- (NSString*) payTotal {
  return protobufBuilderResult.payTotal;
}
- (MOrder_Builder*) setPayTotal:(NSString*) _value {
  protobufBuilderResult.hasPayTotal = YES;
  protobufBuilderResult.payTotal = _value;
  return self;
}
- (MOrder_Builder*) clearPayTotal {
  protobufBuilderResult.hasPayTotal = NO;
  protobufBuilderResult.payTotal = @"";
  return self;
}
- (BOOL) hasStbTotal {
  return protobufBuilderResult.hasStbTotal;
}
- (NSString*) stbTotal {
  return protobufBuilderResult.stbTotal;
}
- (MOrder_Builder*) setStbTotal:(NSString*) _value {
  protobufBuilderResult.hasStbTotal = YES;
  protobufBuilderResult.stbTotal = _value;
  return self;
}
- (MOrder_Builder*) clearStbTotal {
  protobufBuilderResult.hasStbTotal = NO;
  protobufBuilderResult.stbTotal = @"";
  return self;
}
- (BOOL) hasStoreTotal {
  return protobufBuilderResult.hasStoreTotal;
}
- (NSString*) storeTotal {
  return protobufBuilderResult.storeTotal;
}
- (MOrder_Builder*) setStoreTotal:(NSString*) _value {
  protobufBuilderResult.hasStoreTotal = YES;
  protobufBuilderResult.storeTotal = _value;
  return self;
}
- (MOrder_Builder*) clearStoreTotal {
  protobufBuilderResult.hasStoreTotal = NO;
  protobufBuilderResult.storeTotal = @"";
  return self;
}
@end

