// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class MComment;
@class MCommentList;
@class MCommentList_Builder;
@class MComment_Builder;
@class MPraise;
@class MPraise_Builder;
@class MTopic;
@class MTopicList;
@class MTopicList_Builder;
@class MTopic_Builder;

@interface UserTopicRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MTopic : PBGeneratedMessage {
@private
  BOOL hasPraiseCnt_:1;
  BOOL hasCommentCnt_:1;
  BOOL hasHasPraise_:1;
  BOOL hasId_:1;
  BOOL hasUserid_:1;
  BOOL hasHeadImg_:1;
  BOOL hasContent_:1;
  BOOL hasLocation_:1;
  BOOL hasTime_:1;
  BOOL hasCreateTime_:1;
  int32_t praiseCnt;
  int32_t commentCnt;
  int32_t hasPraise;
  NSString* id;
  NSString* userid;
  NSString* headImg;
  NSString* content;
  NSString* location;
  NSString* time;
  NSString* createTime;
  NSMutableArray* mutableImgsList;
  NSMutableArray* mutableCommentsList;
  NSMutableArray* mutablePraisesList;
}
- (BOOL) hasId;
- (BOOL) hasUserid;
- (BOOL) hasHeadImg;
- (BOOL) hasContent;
- (BOOL) hasLocation;
- (BOOL) hasPraiseCnt;
- (BOOL) hasCommentCnt;
- (BOOL) hasTime;
- (BOOL) hasCreateTime;
- (BOOL) hasHasPraise;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* userid;
@property (readonly, retain) NSString* headImg;
@property (readonly, retain) NSString* content;
@property (readonly, retain) NSString* location;
@property (readonly) int32_t praiseCnt;
@property (readonly) int32_t commentCnt;
@property (readonly, retain) NSString* time;
@property (readonly, retain) NSString* createTime;
@property (readonly) int32_t hasPraise;
- (NSArray*) imgsList;
- (NSString*) imgsAtIndex:(int32_t) index;
- (NSArray*) commentsList;
- (MComment*) commentsAtIndex:(int32_t) index;
- (NSArray*) praisesList;
- (MPraise*) praisesAtIndex:(int32_t) index;

+ (MTopic*) defaultInstance;
- (MTopic*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MTopic_Builder*) builder;
+ (MTopic_Builder*) builder;
+ (MTopic_Builder*) builderWithPrototype:(MTopic*) prototype;

+ (MTopic*) parseFromData:(NSData*) data;
+ (MTopic*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MTopic*) parseFromInputStream:(NSInputStream*) input;
+ (MTopic*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MTopic*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MTopic*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MTopic_Builder : PBGeneratedMessage_Builder {
@private
  MTopic* protobufBuilderResult;
}

- (MTopic*) defaultInstance;

- (MTopic_Builder*) clear;
- (MTopic_Builder*) clone;

- (MTopic*) build;
- (MTopic*) buildPartial;

- (MTopic_Builder*) mergeFrom:(MTopic*) other;
- (MTopic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MTopic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MTopic_Builder*) setId:(NSString*) _value;
- (MTopic_Builder*) clearId;

- (BOOL) hasUserid;
- (NSString*) userid;
- (MTopic_Builder*) setUserid:(NSString*) _value;
- (MTopic_Builder*) clearUserid;

- (BOOL) hasHeadImg;
- (NSString*) headImg;
- (MTopic_Builder*) setHeadImg:(NSString*) _value;
- (MTopic_Builder*) clearHeadImg;

- (BOOL) hasContent;
- (NSString*) content;
- (MTopic_Builder*) setContent:(NSString*) _value;
- (MTopic_Builder*) clearContent;

- (NSArray*) imgsList;
- (NSString*) imgsAtIndex:(int32_t) index;
- (MTopic_Builder*) replaceImgsAtIndex:(int32_t) index with:(NSString*) _value;
- (MTopic_Builder*) addImgs:(NSString*) _value;
- (MTopic_Builder*) addAllImgs:(NSArray*) values;
- (MTopic_Builder*) clearImgsList;

- (BOOL) hasLocation;
- (NSString*) location;
- (MTopic_Builder*) setLocation:(NSString*) _value;
- (MTopic_Builder*) clearLocation;

- (BOOL) hasPraiseCnt;
- (int32_t) praiseCnt;
- (MTopic_Builder*) setPraiseCnt:(int32_t) _value;
- (MTopic_Builder*) clearPraiseCnt;

- (BOOL) hasCommentCnt;
- (int32_t) commentCnt;
- (MTopic_Builder*) setCommentCnt:(int32_t) _value;
- (MTopic_Builder*) clearCommentCnt;

- (BOOL) hasTime;
- (NSString*) time;
- (MTopic_Builder*) setTime:(NSString*) _value;
- (MTopic_Builder*) clearTime;

- (BOOL) hasCreateTime;
- (NSString*) createTime;
- (MTopic_Builder*) setCreateTime:(NSString*) _value;
- (MTopic_Builder*) clearCreateTime;

- (NSArray*) commentsList;
- (MComment*) commentsAtIndex:(int32_t) index;
- (MTopic_Builder*) replaceCommentsAtIndex:(int32_t) index with:(MComment*) _value;
- (MTopic_Builder*) addComments:(MComment*) _value;
- (MTopic_Builder*) addAllComments:(NSArray*) values;
- (MTopic_Builder*) clearCommentsList;

- (NSArray*) praisesList;
- (MPraise*) praisesAtIndex:(int32_t) index;
- (MTopic_Builder*) replacePraisesAtIndex:(int32_t) index with:(MPraise*) _value;
- (MTopic_Builder*) addPraises:(MPraise*) _value;
- (MTopic_Builder*) addAllPraises:(NSArray*) values;
- (MTopic_Builder*) clearPraisesList;

- (BOOL) hasHasPraise;
- (int32_t) hasPraise;
- (MTopic_Builder*) setHasPraise:(int32_t) _value;
- (MTopic_Builder*) clearHasPraise;
@end

@interface MTopicList : PBGeneratedMessage {
@private
  NSMutableArray* mutableListList;
}
- (NSArray*) listList;
- (MTopic*) listAtIndex:(int32_t) index;

+ (MTopicList*) defaultInstance;
- (MTopicList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MTopicList_Builder*) builder;
+ (MTopicList_Builder*) builder;
+ (MTopicList_Builder*) builderWithPrototype:(MTopicList*) prototype;

+ (MTopicList*) parseFromData:(NSData*) data;
+ (MTopicList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MTopicList*) parseFromInputStream:(NSInputStream*) input;
+ (MTopicList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MTopicList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MTopicList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MTopicList_Builder : PBGeneratedMessage_Builder {
@private
  MTopicList* protobufBuilderResult;
}

- (MTopicList*) defaultInstance;

- (MTopicList_Builder*) clear;
- (MTopicList_Builder*) clone;

- (MTopicList*) build;
- (MTopicList*) buildPartial;

- (MTopicList_Builder*) mergeFrom:(MTopicList*) other;
- (MTopicList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MTopicList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) listList;
- (MTopic*) listAtIndex:(int32_t) index;
- (MTopicList_Builder*) replaceListAtIndex:(int32_t) index with:(MTopic*) _value;
- (MTopicList_Builder*) addList:(MTopic*) _value;
- (MTopicList_Builder*) addAllList:(NSArray*) values;
- (MTopicList_Builder*) clearListList;
@end

@interface MPraise : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasUserid_:1;
  BOOL hasHeadImg_:1;
  NSString* id;
  NSString* userid;
  NSString* headImg;
}
- (BOOL) hasId;
- (BOOL) hasUserid;
- (BOOL) hasHeadImg;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* userid;
@property (readonly, retain) NSString* headImg;

+ (MPraise*) defaultInstance;
- (MPraise*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MPraise_Builder*) builder;
+ (MPraise_Builder*) builder;
+ (MPraise_Builder*) builderWithPrototype:(MPraise*) prototype;

+ (MPraise*) parseFromData:(NSData*) data;
+ (MPraise*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MPraise*) parseFromInputStream:(NSInputStream*) input;
+ (MPraise*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MPraise*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MPraise*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MPraise_Builder : PBGeneratedMessage_Builder {
@private
  MPraise* protobufBuilderResult;
}

- (MPraise*) defaultInstance;

- (MPraise_Builder*) clear;
- (MPraise_Builder*) clone;

- (MPraise*) build;
- (MPraise*) buildPartial;

- (MPraise_Builder*) mergeFrom:(MPraise*) other;
- (MPraise_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MPraise_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MPraise_Builder*) setId:(NSString*) _value;
- (MPraise_Builder*) clearId;

- (BOOL) hasUserid;
- (NSString*) userid;
- (MPraise_Builder*) setUserid:(NSString*) _value;
- (MPraise_Builder*) clearUserid;

- (BOOL) hasHeadImg;
- (NSString*) headImg;
- (MPraise_Builder*) setHeadImg:(NSString*) _value;
- (MPraise_Builder*) clearHeadImg;
@end

@interface MComment : PBGeneratedMessage {
@private
  BOOL hasId_:1;
  BOOL hasUserid_:1;
  BOOL hasHeadImg_:1;
  BOOL hasNickname_:1;
  BOOL hasTargetId_:1;
  BOOL hasTargetNickname_:1;
  BOOL hasContent_:1;
  BOOL hasTime_:1;
  BOOL hasCreateTime_:1;
  NSString* id;
  NSString* userid;
  NSString* headImg;
  NSString* nickname;
  NSString* targetId;
  NSString* targetNickname;
  NSString* content;
  NSString* time;
  NSString* createTime;
}
- (BOOL) hasId;
- (BOOL) hasUserid;
- (BOOL) hasHeadImg;
- (BOOL) hasNickname;
- (BOOL) hasTargetId;
- (BOOL) hasTargetNickname;
- (BOOL) hasContent;
- (BOOL) hasTime;
- (BOOL) hasCreateTime;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* userid;
@property (readonly, retain) NSString* headImg;
@property (readonly, retain) NSString* nickname;
@property (readonly, retain) NSString* targetId;
@property (readonly, retain) NSString* targetNickname;
@property (readonly, retain) NSString* content;
@property (readonly, retain) NSString* time;
@property (readonly, retain) NSString* createTime;

+ (MComment*) defaultInstance;
- (MComment*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MComment_Builder*) builder;
+ (MComment_Builder*) builder;
+ (MComment_Builder*) builderWithPrototype:(MComment*) prototype;

+ (MComment*) parseFromData:(NSData*) data;
+ (MComment*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MComment*) parseFromInputStream:(NSInputStream*) input;
+ (MComment*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MComment*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MComment*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MComment_Builder : PBGeneratedMessage_Builder {
@private
  MComment* protobufBuilderResult;
}

- (MComment*) defaultInstance;

- (MComment_Builder*) clear;
- (MComment_Builder*) clone;

- (MComment*) build;
- (MComment*) buildPartial;

- (MComment_Builder*) mergeFrom:(MComment*) other;
- (MComment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MComment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MComment_Builder*) setId:(NSString*) _value;
- (MComment_Builder*) clearId;

- (BOOL) hasUserid;
- (NSString*) userid;
- (MComment_Builder*) setUserid:(NSString*) _value;
- (MComment_Builder*) clearUserid;

- (BOOL) hasHeadImg;
- (NSString*) headImg;
- (MComment_Builder*) setHeadImg:(NSString*) _value;
- (MComment_Builder*) clearHeadImg;

- (BOOL) hasNickname;
- (NSString*) nickname;
- (MComment_Builder*) setNickname:(NSString*) _value;
- (MComment_Builder*) clearNickname;

- (BOOL) hasTargetId;
- (NSString*) targetId;
- (MComment_Builder*) setTargetId:(NSString*) _value;
- (MComment_Builder*) clearTargetId;

- (BOOL) hasTargetNickname;
- (NSString*) targetNickname;
- (MComment_Builder*) setTargetNickname:(NSString*) _value;
- (MComment_Builder*) clearTargetNickname;

- (BOOL) hasContent;
- (NSString*) content;
- (MComment_Builder*) setContent:(NSString*) _value;
- (MComment_Builder*) clearContent;

- (BOOL) hasTime;
- (NSString*) time;
- (MComment_Builder*) setTime:(NSString*) _value;
- (MComment_Builder*) clearTime;

- (BOOL) hasCreateTime;
- (NSString*) createTime;
- (MComment_Builder*) setCreateTime:(NSString*) _value;
- (MComment_Builder*) clearCreateTime;
@end

@interface MCommentList : PBGeneratedMessage {
@private
  NSMutableArray* mutableCommentsList;
}
- (NSArray*) commentsList;
- (MComment*) commentsAtIndex:(int32_t) index;

+ (MCommentList*) defaultInstance;
- (MCommentList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MCommentList_Builder*) builder;
+ (MCommentList_Builder*) builder;
+ (MCommentList_Builder*) builderWithPrototype:(MCommentList*) prototype;

+ (MCommentList*) parseFromData:(NSData*) data;
+ (MCommentList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MCommentList*) parseFromInputStream:(NSInputStream*) input;
+ (MCommentList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MCommentList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MCommentList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MCommentList_Builder : PBGeneratedMessage_Builder {
@private
  MCommentList* protobufBuilderResult;
}

- (MCommentList*) defaultInstance;

- (MCommentList_Builder*) clear;
- (MCommentList_Builder*) clone;

- (MCommentList*) build;
- (MCommentList*) buildPartial;

- (MCommentList_Builder*) mergeFrom:(MCommentList*) other;
- (MCommentList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MCommentList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) commentsList;
- (MComment*) commentsAtIndex:(int32_t) index;
- (MCommentList_Builder*) replaceCommentsAtIndex:(int32_t) index with:(MComment*) _value;
- (MCommentList_Builder*) addComments:(MComment*) _value;
- (MCommentList_Builder*) addAllComments:(NSArray*) values;
- (MCommentList_Builder*) clearCommentsList;
@end

