// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class MDate;
@class MDateList;
@class MDateList_Builder;
@class MDate_Builder;
@class MMarriage;
@class MMarriageMini;
@class MMarriageMiniList;
@class MMarriageMiniList_Builder;
@class MMarriageMini_Builder;
@class MMarriage_Builder;
@class MUserDatePage;
@class MUserDatePage_Builder;

@interface UserDateRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MDate : PBGeneratedMessage {
@private
  BOOL hasFriend_:1;
  BOOL hasAge_:1;
  BOOL hasHasView_:1;
  BOOL hasUserCnt_:1;
  BOOL hasOverdue_:1;
  BOOL hasId_:1;
  BOOL hasTheme_:1;
  BOOL hasContent_:1;
  BOOL hasImg_:1;
  BOOL hasTime_:1;
  BOOL hasPlace_:1;
  BOOL hasCost_:1;
  BOOL hasUserid_:1;
  BOOL hasUserImg_:1;
  BOOL hasNickname_:1;
  BOOL hasSex_:1;
  BOOL hasDistanceShow_:1;
  BOOL hasDistanceQuery_:1;
  BOOL hasCreateTimeShow_:1;
  BOOL hasCreateTimeQuery_:1;
  BOOL hasStatus_:1;
  BOOL hasViewId_:1;
  int32_t friend;
  int32_t age;
  int32_t hasView;
  int32_t userCnt;
  int32_t overdue;
  NSString* id;
  NSString* theme;
  NSString* content;
  NSString* img;
  NSString* time;
  NSString* place;
  NSString* cost;
  NSString* userid;
  NSString* userImg;
  NSString* nickname;
  NSString* sex;
  NSString* distanceShow;
  NSString* distanceQuery;
  NSString* createTimeShow;
  NSString* createTimeQuery;
  NSString* status;
  NSString* viewId;
}
- (BOOL) hasId;
- (BOOL) hasTheme;
- (BOOL) hasContent;
- (BOOL) hasImg;
- (BOOL) hasTime;
- (BOOL) hasPlace;
- (BOOL) hasCost;
- (BOOL) hasFriend;
- (BOOL) hasUserid;
- (BOOL) hasUserImg;
- (BOOL) hasNickname;
- (BOOL) hasSex;
- (BOOL) hasAge;
- (BOOL) hasDistanceShow;
- (BOOL) hasDistanceQuery;
- (BOOL) hasCreateTimeShow;
- (BOOL) hasCreateTimeQuery;
- (BOOL) hasHasView;
- (BOOL) hasUserCnt;
- (BOOL) hasOverdue;
- (BOOL) hasStatus;
- (BOOL) hasViewId;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* theme;
@property (readonly, retain) NSString* content;
@property (readonly, retain) NSString* img;
@property (readonly, retain) NSString* time;
@property (readonly, retain) NSString* place;
@property (readonly, retain) NSString* cost;
@property (readonly) int32_t friend;
@property (readonly, retain) NSString* userid;
@property (readonly, retain) NSString* userImg;
@property (readonly, retain) NSString* nickname;
@property (readonly, retain) NSString* sex;
@property (readonly) int32_t age;
@property (readonly, retain) NSString* distanceShow;
@property (readonly, retain) NSString* distanceQuery;
@property (readonly, retain) NSString* createTimeShow;
@property (readonly, retain) NSString* createTimeQuery;
@property (readonly) int32_t hasView;
@property (readonly) int32_t userCnt;
@property (readonly) int32_t overdue;
@property (readonly, retain) NSString* status;
@property (readonly, retain) NSString* viewId;

+ (MDate*) defaultInstance;
- (MDate*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MDate_Builder*) builder;
+ (MDate_Builder*) builder;
+ (MDate_Builder*) builderWithPrototype:(MDate*) prototype;

+ (MDate*) parseFromData:(NSData*) data;
+ (MDate*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MDate*) parseFromInputStream:(NSInputStream*) input;
+ (MDate*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MDate*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MDate*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MDate_Builder : PBGeneratedMessage_Builder {
@private
  MDate* protobufBuilderResult;
}

- (MDate*) defaultInstance;

- (MDate_Builder*) clear;
- (MDate_Builder*) clone;

- (MDate*) build;
- (MDate*) buildPartial;

- (MDate_Builder*) mergeFrom:(MDate*) other;
- (MDate_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MDate_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MDate_Builder*) setId:(NSString*) _value;
- (MDate_Builder*) clearId;

- (BOOL) hasTheme;
- (NSString*) theme;
- (MDate_Builder*) setTheme:(NSString*) _value;
- (MDate_Builder*) clearTheme;

- (BOOL) hasContent;
- (NSString*) content;
- (MDate_Builder*) setContent:(NSString*) _value;
- (MDate_Builder*) clearContent;

- (BOOL) hasImg;
- (NSString*) img;
- (MDate_Builder*) setImg:(NSString*) _value;
- (MDate_Builder*) clearImg;

- (BOOL) hasTime;
- (NSString*) time;
- (MDate_Builder*) setTime:(NSString*) _value;
- (MDate_Builder*) clearTime;

- (BOOL) hasPlace;
- (NSString*) place;
- (MDate_Builder*) setPlace:(NSString*) _value;
- (MDate_Builder*) clearPlace;

- (BOOL) hasCost;
- (NSString*) cost;
- (MDate_Builder*) setCost:(NSString*) _value;
- (MDate_Builder*) clearCost;

- (BOOL) hasFriend;
- (int32_t) friend;
- (MDate_Builder*) setFriend:(int32_t) _value;
- (MDate_Builder*) clearFriend;

- (BOOL) hasUserid;
- (NSString*) userid;
- (MDate_Builder*) setUserid:(NSString*) _value;
- (MDate_Builder*) clearUserid;

- (BOOL) hasUserImg;
- (NSString*) userImg;
- (MDate_Builder*) setUserImg:(NSString*) _value;
- (MDate_Builder*) clearUserImg;

- (BOOL) hasNickname;
- (NSString*) nickname;
- (MDate_Builder*) setNickname:(NSString*) _value;
- (MDate_Builder*) clearNickname;

- (BOOL) hasSex;
- (NSString*) sex;
- (MDate_Builder*) setSex:(NSString*) _value;
- (MDate_Builder*) clearSex;

- (BOOL) hasAge;
- (int32_t) age;
- (MDate_Builder*) setAge:(int32_t) _value;
- (MDate_Builder*) clearAge;

- (BOOL) hasDistanceShow;
- (NSString*) distanceShow;
- (MDate_Builder*) setDistanceShow:(NSString*) _value;
- (MDate_Builder*) clearDistanceShow;

- (BOOL) hasDistanceQuery;
- (NSString*) distanceQuery;
- (MDate_Builder*) setDistanceQuery:(NSString*) _value;
- (MDate_Builder*) clearDistanceQuery;

- (BOOL) hasCreateTimeShow;
- (NSString*) createTimeShow;
- (MDate_Builder*) setCreateTimeShow:(NSString*) _value;
- (MDate_Builder*) clearCreateTimeShow;

- (BOOL) hasCreateTimeQuery;
- (NSString*) createTimeQuery;
- (MDate_Builder*) setCreateTimeQuery:(NSString*) _value;
- (MDate_Builder*) clearCreateTimeQuery;

- (BOOL) hasHasView;
- (int32_t) hasView;
- (MDate_Builder*) setHasView:(int32_t) _value;
- (MDate_Builder*) clearHasView;

- (BOOL) hasUserCnt;
- (int32_t) userCnt;
- (MDate_Builder*) setUserCnt:(int32_t) _value;
- (MDate_Builder*) clearUserCnt;

- (BOOL) hasOverdue;
- (int32_t) overdue;
- (MDate_Builder*) setOverdue:(int32_t) _value;
- (MDate_Builder*) clearOverdue;

- (BOOL) hasStatus;
- (NSString*) status;
- (MDate_Builder*) setStatus:(NSString*) _value;
- (MDate_Builder*) clearStatus;

- (BOOL) hasViewId;
- (NSString*) viewId;
- (MDate_Builder*) setViewId:(NSString*) _value;
- (MDate_Builder*) clearViewId;
@end

@interface MDateList : PBGeneratedMessage {
@private
  NSMutableArray* mutableDateList;
}
- (NSArray*) dateList;
- (MDate*) dateAtIndex:(int32_t) index;

+ (MDateList*) defaultInstance;
- (MDateList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MDateList_Builder*) builder;
+ (MDateList_Builder*) builder;
+ (MDateList_Builder*) builderWithPrototype:(MDateList*) prototype;

+ (MDateList*) parseFromData:(NSData*) data;
+ (MDateList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MDateList*) parseFromInputStream:(NSInputStream*) input;
+ (MDateList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MDateList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MDateList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MDateList_Builder : PBGeneratedMessage_Builder {
@private
  MDateList* protobufBuilderResult;
}

- (MDateList*) defaultInstance;

- (MDateList_Builder*) clear;
- (MDateList_Builder*) clone;

- (MDateList*) build;
- (MDateList*) buildPartial;

- (MDateList_Builder*) mergeFrom:(MDateList*) other;
- (MDateList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MDateList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) dateList;
- (MDate*) dateAtIndex:(int32_t) index;
- (MDateList_Builder*) replaceDateAtIndex:(int32_t) index with:(MDate*) _value;
- (MDateList_Builder*) addDate:(MDate*) _value;
- (MDateList_Builder*) addAllDate:(NSArray*) values;
- (MDateList_Builder*) clearDateList;
@end

@interface MMarriage : PBGeneratedMessage {
@private
  BOOL hasHasView_:1;
  BOOL hasPhotoCnt_:1;
  BOOL hasAge_:1;
  BOOL hasSex_:1;
  BOOL hasWhenMarry_:1;
  BOOL hasParent_:1;
  BOOL hasOnlyChild_:1;
  BOOL hasSource_:1;
  BOOL hasLocation_:1;
  BOOL hasHeight_:1;
  BOOL hasWeight_:1;
  BOOL hasJob_:1;
  BOOL hasIncome_:1;
  BOOL hasEducation_:1;
  BOOL hasHistory_:1;
  BOOL hasMarriageHistory_:1;
  BOOL hasChild_:1;
  BOOL hasWine_:1;
  BOOL hasHealth_:1;
  BOOL hasMarriageHousing_:1;
  BOOL hasZodiac_:1;
  BOOL hasConstellation_:1;
  BOOL hasBlood_:1;
  BOOL hasNation_:1;
  BOOL hasReligion_:1;
  BOOL hasSchool_:1;
  BOOL hasDriverLicense_:1;
  BOOL hasSmoke_:1;
  BOOL hasTrait_:1;
  BOOL hasDisease_:1;
  BOOL hasSport_:1;
  BOOL hasTravel_:1;
  BOOL hasHobby_:1;
  BOOL hasHouseEquity_:1;
  BOOL hasLoan_:1;
  BOOL hasCar_:1;
  BOOL hasAsset_:1;
  BOOL hasTargetSource_:1;
  BOOL hasTargetIncome_:1;
  BOOL hasTargetEducation_:1;
  BOOL hasTargetMarriage_:1;
  BOOL hasTargetHouse_:1;
  BOOL hasTargetChild_:1;
  BOOL hasTargetZodiac_:1;
  BOOL hasTargetHeight_:1;
  BOOL hasTargetWeight_:1;
  BOOL hasDistance_:1;
  BOOL hasNickname_:1;
  BOOL hasLetter_:1;
  BOOL hasImg_:1;
  BOOL hasUserid_:1;
  BOOL hasCreateTime_:1;
  BOOL hasId_:1;
  BOOL hasViewId_:1;
  int32_t hasView;
  int32_t photoCnt;
  int32_t age;
  int32_t sex;
  NSString* whenMarry;
  NSString* parent;
  NSString* onlyChild;
  NSString* source;
  NSString* location;
  NSString* height;
  NSString* weight;
  NSString* job;
  NSString* income;
  NSString* education;
  NSString* history;
  NSString* marriageHistory;
  NSString* child;
  NSString* wine;
  NSString* health;
  NSString* marriageHousing;
  NSString* zodiac;
  NSString* constellation;
  NSString* blood;
  NSString* nation;
  NSString* religion;
  NSString* school;
  NSString* driverLicense;
  NSString* smoke;
  NSString* trait;
  NSString* disease;
  NSString* sport;
  NSString* travel;
  NSString* hobby;
  NSString* houseEquity;
  NSString* loan;
  NSString* car;
  NSString* asset;
  NSString* targetSource;
  NSString* targetIncome;
  NSString* targetEducation;
  NSString* targetMarriage;
  NSString* targetHouse;
  NSString* targetChild;
  NSString* targetZodiac;
  NSString* targetHeight;
  NSString* targetWeight;
  NSString* distance;
  NSString* nickname;
  NSString* letter;
  NSString* img;
  NSString* userid;
  NSString* createTime;
  NSString* id;
  NSString* viewId;
}
- (BOOL) hasId;
- (BOOL) hasUserid;
- (BOOL) hasImg;
- (BOOL) hasLetter;
- (BOOL) hasWhenMarry;
- (BOOL) hasParent;
- (BOOL) hasOnlyChild;
- (BOOL) hasSource;
- (BOOL) hasLocation;
- (BOOL) hasHeight;
- (BOOL) hasWeight;
- (BOOL) hasJob;
- (BOOL) hasIncome;
- (BOOL) hasEducation;
- (BOOL) hasHistory;
- (BOOL) hasMarriageHistory;
- (BOOL) hasChild;
- (BOOL) hasWine;
- (BOOL) hasHealth;
- (BOOL) hasMarriageHousing;
- (BOOL) hasZodiac;
- (BOOL) hasConstellation;
- (BOOL) hasBlood;
- (BOOL) hasNation;
- (BOOL) hasReligion;
- (BOOL) hasSchool;
- (BOOL) hasDriverLicense;
- (BOOL) hasSmoke;
- (BOOL) hasTrait;
- (BOOL) hasDisease;
- (BOOL) hasSport;
- (BOOL) hasTravel;
- (BOOL) hasHobby;
- (BOOL) hasHouseEquity;
- (BOOL) hasLoan;
- (BOOL) hasCar;
- (BOOL) hasAsset;
- (BOOL) hasTargetSource;
- (BOOL) hasTargetIncome;
- (BOOL) hasTargetEducation;
- (BOOL) hasTargetMarriage;
- (BOOL) hasTargetHouse;
- (BOOL) hasTargetChild;
- (BOOL) hasTargetZodiac;
- (BOOL) hasTargetHeight;
- (BOOL) hasTargetWeight;
- (BOOL) hasDistance;
- (BOOL) hasNickname;
- (BOOL) hasSex;
- (BOOL) hasAge;
- (BOOL) hasPhotoCnt;
- (BOOL) hasCreateTime;
- (BOOL) hasHasView;
- (BOOL) hasViewId;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* userid;
@property (readonly, retain) NSString* img;
@property (readonly, retain) NSString* letter;
@property (readonly, retain) NSString* whenMarry;
@property (readonly, retain) NSString* parent;
@property (readonly, retain) NSString* onlyChild;
@property (readonly, retain) NSString* source;
@property (readonly, retain) NSString* location;
@property (readonly, retain) NSString* height;
@property (readonly, retain) NSString* weight;
@property (readonly, retain) NSString* job;
@property (readonly, retain) NSString* income;
@property (readonly, retain) NSString* education;
@property (readonly, retain) NSString* history;
@property (readonly, retain) NSString* marriageHistory;
@property (readonly, retain) NSString* child;
@property (readonly, retain) NSString* wine;
@property (readonly, retain) NSString* health;
@property (readonly, retain) NSString* marriageHousing;
@property (readonly, retain) NSString* zodiac;
@property (readonly, retain) NSString* constellation;
@property (readonly, retain) NSString* blood;
@property (readonly, retain) NSString* nation;
@property (readonly, retain) NSString* religion;
@property (readonly, retain) NSString* school;
@property (readonly, retain) NSString* driverLicense;
@property (readonly, retain) NSString* smoke;
@property (readonly, retain) NSString* trait;
@property (readonly, retain) NSString* disease;
@property (readonly, retain) NSString* sport;
@property (readonly, retain) NSString* travel;
@property (readonly, retain) NSString* hobby;
@property (readonly, retain) NSString* houseEquity;
@property (readonly, retain) NSString* loan;
@property (readonly, retain) NSString* car;
@property (readonly, retain) NSString* asset;
@property (readonly, retain) NSString* targetSource;
@property (readonly, retain) NSString* targetIncome;
@property (readonly, retain) NSString* targetEducation;
@property (readonly, retain) NSString* targetMarriage;
@property (readonly, retain) NSString* targetHouse;
@property (readonly, retain) NSString* targetChild;
@property (readonly, retain) NSString* targetZodiac;
@property (readonly, retain) NSString* targetHeight;
@property (readonly, retain) NSString* targetWeight;
@property (readonly, retain) NSString* distance;
@property (readonly, retain) NSString* nickname;
@property (readonly) int32_t sex;
@property (readonly) int32_t age;
@property (readonly) int32_t photoCnt;
@property (readonly, retain) NSString* createTime;
@property (readonly) int32_t hasView;
@property (readonly, retain) NSString* viewId;

+ (MMarriage*) defaultInstance;
- (MMarriage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMarriage_Builder*) builder;
+ (MMarriage_Builder*) builder;
+ (MMarriage_Builder*) builderWithPrototype:(MMarriage*) prototype;

+ (MMarriage*) parseFromData:(NSData*) data;
+ (MMarriage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarriage*) parseFromInputStream:(NSInputStream*) input;
+ (MMarriage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarriage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMarriage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMarriage_Builder : PBGeneratedMessage_Builder {
@private
  MMarriage* protobufBuilderResult;
}

- (MMarriage*) defaultInstance;

- (MMarriage_Builder*) clear;
- (MMarriage_Builder*) clone;

- (MMarriage*) build;
- (MMarriage*) buildPartial;

- (MMarriage_Builder*) mergeFrom:(MMarriage*) other;
- (MMarriage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMarriage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MMarriage_Builder*) setId:(NSString*) _value;
- (MMarriage_Builder*) clearId;

- (BOOL) hasUserid;
- (NSString*) userid;
- (MMarriage_Builder*) setUserid:(NSString*) _value;
- (MMarriage_Builder*) clearUserid;

- (BOOL) hasImg;
- (NSString*) img;
- (MMarriage_Builder*) setImg:(NSString*) _value;
- (MMarriage_Builder*) clearImg;

- (BOOL) hasLetter;
- (NSString*) letter;
- (MMarriage_Builder*) setLetter:(NSString*) _value;
- (MMarriage_Builder*) clearLetter;

- (BOOL) hasWhenMarry;
- (NSString*) whenMarry;
- (MMarriage_Builder*) setWhenMarry:(NSString*) _value;
- (MMarriage_Builder*) clearWhenMarry;

- (BOOL) hasParent;
- (NSString*) parent;
- (MMarriage_Builder*) setParent:(NSString*) _value;
- (MMarriage_Builder*) clearParent;

- (BOOL) hasOnlyChild;
- (NSString*) onlyChild;
- (MMarriage_Builder*) setOnlyChild:(NSString*) _value;
- (MMarriage_Builder*) clearOnlyChild;

- (BOOL) hasSource;
- (NSString*) source;
- (MMarriage_Builder*) setSource:(NSString*) _value;
- (MMarriage_Builder*) clearSource;

- (BOOL) hasLocation;
- (NSString*) location;
- (MMarriage_Builder*) setLocation:(NSString*) _value;
- (MMarriage_Builder*) clearLocation;

- (BOOL) hasHeight;
- (NSString*) height;
- (MMarriage_Builder*) setHeight:(NSString*) _value;
- (MMarriage_Builder*) clearHeight;

- (BOOL) hasWeight;
- (NSString*) weight;
- (MMarriage_Builder*) setWeight:(NSString*) _value;
- (MMarriage_Builder*) clearWeight;

- (BOOL) hasJob;
- (NSString*) job;
- (MMarriage_Builder*) setJob:(NSString*) _value;
- (MMarriage_Builder*) clearJob;

- (BOOL) hasIncome;
- (NSString*) income;
- (MMarriage_Builder*) setIncome:(NSString*) _value;
- (MMarriage_Builder*) clearIncome;

- (BOOL) hasEducation;
- (NSString*) education;
- (MMarriage_Builder*) setEducation:(NSString*) _value;
- (MMarriage_Builder*) clearEducation;

- (BOOL) hasHistory;
- (NSString*) history;
- (MMarriage_Builder*) setHistory:(NSString*) _value;
- (MMarriage_Builder*) clearHistory;

- (BOOL) hasMarriageHistory;
- (NSString*) marriageHistory;
- (MMarriage_Builder*) setMarriageHistory:(NSString*) _value;
- (MMarriage_Builder*) clearMarriageHistory;

- (BOOL) hasChild;
- (NSString*) child;
- (MMarriage_Builder*) setChild:(NSString*) _value;
- (MMarriage_Builder*) clearChild;

- (BOOL) hasWine;
- (NSString*) wine;
- (MMarriage_Builder*) setWine:(NSString*) _value;
- (MMarriage_Builder*) clearWine;

- (BOOL) hasHealth;
- (NSString*) health;
- (MMarriage_Builder*) setHealth:(NSString*) _value;
- (MMarriage_Builder*) clearHealth;

- (BOOL) hasMarriageHousing;
- (NSString*) marriageHousing;
- (MMarriage_Builder*) setMarriageHousing:(NSString*) _value;
- (MMarriage_Builder*) clearMarriageHousing;

- (BOOL) hasZodiac;
- (NSString*) zodiac;
- (MMarriage_Builder*) setZodiac:(NSString*) _value;
- (MMarriage_Builder*) clearZodiac;

- (BOOL) hasConstellation;
- (NSString*) constellation;
- (MMarriage_Builder*) setConstellation:(NSString*) _value;
- (MMarriage_Builder*) clearConstellation;

- (BOOL) hasBlood;
- (NSString*) blood;
- (MMarriage_Builder*) setBlood:(NSString*) _value;
- (MMarriage_Builder*) clearBlood;

- (BOOL) hasNation;
- (NSString*) nation;
- (MMarriage_Builder*) setNation:(NSString*) _value;
- (MMarriage_Builder*) clearNation;

- (BOOL) hasReligion;
- (NSString*) religion;
- (MMarriage_Builder*) setReligion:(NSString*) _value;
- (MMarriage_Builder*) clearReligion;

- (BOOL) hasSchool;
- (NSString*) school;
- (MMarriage_Builder*) setSchool:(NSString*) _value;
- (MMarriage_Builder*) clearSchool;

- (BOOL) hasDriverLicense;
- (NSString*) driverLicense;
- (MMarriage_Builder*) setDriverLicense:(NSString*) _value;
- (MMarriage_Builder*) clearDriverLicense;

- (BOOL) hasSmoke;
- (NSString*) smoke;
- (MMarriage_Builder*) setSmoke:(NSString*) _value;
- (MMarriage_Builder*) clearSmoke;

- (BOOL) hasTrait;
- (NSString*) trait;
- (MMarriage_Builder*) setTrait:(NSString*) _value;
- (MMarriage_Builder*) clearTrait;

- (BOOL) hasDisease;
- (NSString*) disease;
- (MMarriage_Builder*) setDisease:(NSString*) _value;
- (MMarriage_Builder*) clearDisease;

- (BOOL) hasSport;
- (NSString*) sport;
- (MMarriage_Builder*) setSport:(NSString*) _value;
- (MMarriage_Builder*) clearSport;

- (BOOL) hasTravel;
- (NSString*) travel;
- (MMarriage_Builder*) setTravel:(NSString*) _value;
- (MMarriage_Builder*) clearTravel;

- (BOOL) hasHobby;
- (NSString*) hobby;
- (MMarriage_Builder*) setHobby:(NSString*) _value;
- (MMarriage_Builder*) clearHobby;

- (BOOL) hasHouseEquity;
- (NSString*) houseEquity;
- (MMarriage_Builder*) setHouseEquity:(NSString*) _value;
- (MMarriage_Builder*) clearHouseEquity;

- (BOOL) hasLoan;
- (NSString*) loan;
- (MMarriage_Builder*) setLoan:(NSString*) _value;
- (MMarriage_Builder*) clearLoan;

- (BOOL) hasCar;
- (NSString*) car;
- (MMarriage_Builder*) setCar:(NSString*) _value;
- (MMarriage_Builder*) clearCar;

- (BOOL) hasAsset;
- (NSString*) asset;
- (MMarriage_Builder*) setAsset:(NSString*) _value;
- (MMarriage_Builder*) clearAsset;

- (BOOL) hasTargetSource;
- (NSString*) targetSource;
- (MMarriage_Builder*) setTargetSource:(NSString*) _value;
- (MMarriage_Builder*) clearTargetSource;

- (BOOL) hasTargetIncome;
- (NSString*) targetIncome;
- (MMarriage_Builder*) setTargetIncome:(NSString*) _value;
- (MMarriage_Builder*) clearTargetIncome;

- (BOOL) hasTargetEducation;
- (NSString*) targetEducation;
- (MMarriage_Builder*) setTargetEducation:(NSString*) _value;
- (MMarriage_Builder*) clearTargetEducation;

- (BOOL) hasTargetMarriage;
- (NSString*) targetMarriage;
- (MMarriage_Builder*) setTargetMarriage:(NSString*) _value;
- (MMarriage_Builder*) clearTargetMarriage;

- (BOOL) hasTargetHouse;
- (NSString*) targetHouse;
- (MMarriage_Builder*) setTargetHouse:(NSString*) _value;
- (MMarriage_Builder*) clearTargetHouse;

- (BOOL) hasTargetChild;
- (NSString*) targetChild;
- (MMarriage_Builder*) setTargetChild:(NSString*) _value;
- (MMarriage_Builder*) clearTargetChild;

- (BOOL) hasTargetZodiac;
- (NSString*) targetZodiac;
- (MMarriage_Builder*) setTargetZodiac:(NSString*) _value;
- (MMarriage_Builder*) clearTargetZodiac;

- (BOOL) hasTargetHeight;
- (NSString*) targetHeight;
- (MMarriage_Builder*) setTargetHeight:(NSString*) _value;
- (MMarriage_Builder*) clearTargetHeight;

- (BOOL) hasTargetWeight;
- (NSString*) targetWeight;
- (MMarriage_Builder*) setTargetWeight:(NSString*) _value;
- (MMarriage_Builder*) clearTargetWeight;

- (BOOL) hasDistance;
- (NSString*) distance;
- (MMarriage_Builder*) setDistance:(NSString*) _value;
- (MMarriage_Builder*) clearDistance;

- (BOOL) hasNickname;
- (NSString*) nickname;
- (MMarriage_Builder*) setNickname:(NSString*) _value;
- (MMarriage_Builder*) clearNickname;

- (BOOL) hasSex;
- (int32_t) sex;
- (MMarriage_Builder*) setSex:(int32_t) _value;
- (MMarriage_Builder*) clearSex;

- (BOOL) hasAge;
- (int32_t) age;
- (MMarriage_Builder*) setAge:(int32_t) _value;
- (MMarriage_Builder*) clearAge;

- (BOOL) hasPhotoCnt;
- (int32_t) photoCnt;
- (MMarriage_Builder*) setPhotoCnt:(int32_t) _value;
- (MMarriage_Builder*) clearPhotoCnt;

- (BOOL) hasCreateTime;
- (NSString*) createTime;
- (MMarriage_Builder*) setCreateTime:(NSString*) _value;
- (MMarriage_Builder*) clearCreateTime;

- (BOOL) hasHasView;
- (int32_t) hasView;
- (MMarriage_Builder*) setHasView:(int32_t) _value;
- (MMarriage_Builder*) clearHasView;

- (BOOL) hasViewId;
- (NSString*) viewId;
- (MMarriage_Builder*) setViewId:(NSString*) _value;
- (MMarriage_Builder*) clearViewId;
@end

@interface MMarriageMini : PBGeneratedMessage {
@private
  BOOL hasSex_:1;
  BOOL hasAge_:1;
  BOOL hasUserCnt_:1;
  BOOL hasId_:1;
  BOOL hasUserid_:1;
  BOOL hasUserImg_:1;
  BOOL hasNickname_:1;
  BOOL hasHeight_:1;
  BOOL hasWeight_:1;
  BOOL hasJob_:1;
  BOOL hasLetter_:1;
  BOOL hasImg_:1;
  BOOL hasCreateTimeShow_:1;
  BOOL hasCreateTimeQuery_:1;
  BOOL hasDistanceShow_:1;
  BOOL hasDistanceQuery_:1;
  BOOL hasStatus_:1;
  int32_t sex;
  int32_t age;
  int32_t userCnt;
  NSString* id;
  NSString* userid;
  NSString* userImg;
  NSString* nickname;
  NSString* height;
  NSString* weight;
  NSString* job;
  NSString* letter;
  NSString* img;
  NSString* createTimeShow;
  NSString* createTimeQuery;
  NSString* distanceShow;
  NSString* distanceQuery;
  NSString* status;
}
- (BOOL) hasId;
- (BOOL) hasUserid;
- (BOOL) hasUserImg;
- (BOOL) hasNickname;
- (BOOL) hasSex;
- (BOOL) hasAge;
- (BOOL) hasHeight;
- (BOOL) hasWeight;
- (BOOL) hasJob;
- (BOOL) hasLetter;
- (BOOL) hasImg;
- (BOOL) hasCreateTimeShow;
- (BOOL) hasCreateTimeQuery;
- (BOOL) hasDistanceShow;
- (BOOL) hasDistanceQuery;
- (BOOL) hasUserCnt;
- (BOOL) hasStatus;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* userid;
@property (readonly, retain) NSString* userImg;
@property (readonly, retain) NSString* nickname;
@property (readonly) int32_t sex;
@property (readonly) int32_t age;
@property (readonly, retain) NSString* height;
@property (readonly, retain) NSString* weight;
@property (readonly, retain) NSString* job;
@property (readonly, retain) NSString* letter;
@property (readonly, retain) NSString* img;
@property (readonly, retain) NSString* createTimeShow;
@property (readonly, retain) NSString* createTimeQuery;
@property (readonly, retain) NSString* distanceShow;
@property (readonly, retain) NSString* distanceQuery;
@property (readonly) int32_t userCnt;
@property (readonly, retain) NSString* status;

+ (MMarriageMini*) defaultInstance;
- (MMarriageMini*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMarriageMini_Builder*) builder;
+ (MMarriageMini_Builder*) builder;
+ (MMarriageMini_Builder*) builderWithPrototype:(MMarriageMini*) prototype;

+ (MMarriageMini*) parseFromData:(NSData*) data;
+ (MMarriageMini*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarriageMini*) parseFromInputStream:(NSInputStream*) input;
+ (MMarriageMini*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarriageMini*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMarriageMini*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMarriageMini_Builder : PBGeneratedMessage_Builder {
@private
  MMarriageMini* protobufBuilderResult;
}

- (MMarriageMini*) defaultInstance;

- (MMarriageMini_Builder*) clear;
- (MMarriageMini_Builder*) clone;

- (MMarriageMini*) build;
- (MMarriageMini*) buildPartial;

- (MMarriageMini_Builder*) mergeFrom:(MMarriageMini*) other;
- (MMarriageMini_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMarriageMini_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MMarriageMini_Builder*) setId:(NSString*) _value;
- (MMarriageMini_Builder*) clearId;

- (BOOL) hasUserid;
- (NSString*) userid;
- (MMarriageMini_Builder*) setUserid:(NSString*) _value;
- (MMarriageMini_Builder*) clearUserid;

- (BOOL) hasUserImg;
- (NSString*) userImg;
- (MMarriageMini_Builder*) setUserImg:(NSString*) _value;
- (MMarriageMini_Builder*) clearUserImg;

- (BOOL) hasNickname;
- (NSString*) nickname;
- (MMarriageMini_Builder*) setNickname:(NSString*) _value;
- (MMarriageMini_Builder*) clearNickname;

- (BOOL) hasSex;
- (int32_t) sex;
- (MMarriageMini_Builder*) setSex:(int32_t) _value;
- (MMarriageMini_Builder*) clearSex;

- (BOOL) hasAge;
- (int32_t) age;
- (MMarriageMini_Builder*) setAge:(int32_t) _value;
- (MMarriageMini_Builder*) clearAge;

- (BOOL) hasHeight;
- (NSString*) height;
- (MMarriageMini_Builder*) setHeight:(NSString*) _value;
- (MMarriageMini_Builder*) clearHeight;

- (BOOL) hasWeight;
- (NSString*) weight;
- (MMarriageMini_Builder*) setWeight:(NSString*) _value;
- (MMarriageMini_Builder*) clearWeight;

- (BOOL) hasJob;
- (NSString*) job;
- (MMarriageMini_Builder*) setJob:(NSString*) _value;
- (MMarriageMini_Builder*) clearJob;

- (BOOL) hasLetter;
- (NSString*) letter;
- (MMarriageMini_Builder*) setLetter:(NSString*) _value;
- (MMarriageMini_Builder*) clearLetter;

- (BOOL) hasImg;
- (NSString*) img;
- (MMarriageMini_Builder*) setImg:(NSString*) _value;
- (MMarriageMini_Builder*) clearImg;

- (BOOL) hasCreateTimeShow;
- (NSString*) createTimeShow;
- (MMarriageMini_Builder*) setCreateTimeShow:(NSString*) _value;
- (MMarriageMini_Builder*) clearCreateTimeShow;

- (BOOL) hasCreateTimeQuery;
- (NSString*) createTimeQuery;
- (MMarriageMini_Builder*) setCreateTimeQuery:(NSString*) _value;
- (MMarriageMini_Builder*) clearCreateTimeQuery;

- (BOOL) hasDistanceShow;
- (NSString*) distanceShow;
- (MMarriageMini_Builder*) setDistanceShow:(NSString*) _value;
- (MMarriageMini_Builder*) clearDistanceShow;

- (BOOL) hasDistanceQuery;
- (NSString*) distanceQuery;
- (MMarriageMini_Builder*) setDistanceQuery:(NSString*) _value;
- (MMarriageMini_Builder*) clearDistanceQuery;

- (BOOL) hasUserCnt;
- (int32_t) userCnt;
- (MMarriageMini_Builder*) setUserCnt:(int32_t) _value;
- (MMarriageMini_Builder*) clearUserCnt;

- (BOOL) hasStatus;
- (NSString*) status;
- (MMarriageMini_Builder*) setStatus:(NSString*) _value;
- (MMarriageMini_Builder*) clearStatus;
@end

@interface MMarriageMiniList : PBGeneratedMessage {
@private
  BOOL hasList_:1;
  MMarriageMini* list;
}
- (BOOL) hasList;
@property (readonly, retain) MMarriageMini* list;

+ (MMarriageMiniList*) defaultInstance;
- (MMarriageMiniList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMarriageMiniList_Builder*) builder;
+ (MMarriageMiniList_Builder*) builder;
+ (MMarriageMiniList_Builder*) builderWithPrototype:(MMarriageMiniList*) prototype;

+ (MMarriageMiniList*) parseFromData:(NSData*) data;
+ (MMarriageMiniList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarriageMiniList*) parseFromInputStream:(NSInputStream*) input;
+ (MMarriageMiniList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMarriageMiniList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMarriageMiniList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMarriageMiniList_Builder : PBGeneratedMessage_Builder {
@private
  MMarriageMiniList* protobufBuilderResult;
}

- (MMarriageMiniList*) defaultInstance;

- (MMarriageMiniList_Builder*) clear;
- (MMarriageMiniList_Builder*) clone;

- (MMarriageMiniList*) build;
- (MMarriageMiniList*) buildPartial;

- (MMarriageMiniList_Builder*) mergeFrom:(MMarriageMiniList*) other;
- (MMarriageMiniList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMarriageMiniList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasList;
- (MMarriageMini*) list;
- (MMarriageMiniList_Builder*) setList:(MMarriageMini*) _value;
- (MMarriageMiniList_Builder*) setListBuilder:(MMarriageMini_Builder*) builderForValue;
- (MMarriageMiniList_Builder*) mergeList:(MMarriageMini*) _value;
- (MMarriageMiniList_Builder*) clearList;
@end

@interface MUserDatePage : PBGeneratedMessage {
@private
  NSMutableArray* mutableMarriageList;
  NSMutableArray* mutableDateList;
}
- (NSArray*) marriageList;
- (MMarriageMini*) marriageAtIndex:(int32_t) index;
- (NSArray*) dateList;
- (MDate*) dateAtIndex:(int32_t) index;

+ (MUserDatePage*) defaultInstance;
- (MUserDatePage*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MUserDatePage_Builder*) builder;
+ (MUserDatePage_Builder*) builder;
+ (MUserDatePage_Builder*) builderWithPrototype:(MUserDatePage*) prototype;

+ (MUserDatePage*) parseFromData:(NSData*) data;
+ (MUserDatePage*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MUserDatePage*) parseFromInputStream:(NSInputStream*) input;
+ (MUserDatePage*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MUserDatePage*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MUserDatePage*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MUserDatePage_Builder : PBGeneratedMessage_Builder {
@private
  MUserDatePage* protobufBuilderResult;
}

- (MUserDatePage*) defaultInstance;

- (MUserDatePage_Builder*) clear;
- (MUserDatePage_Builder*) clone;

- (MUserDatePage*) build;
- (MUserDatePage*) buildPartial;

- (MUserDatePage_Builder*) mergeFrom:(MUserDatePage*) other;
- (MUserDatePage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MUserDatePage_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) marriageList;
- (MMarriageMini*) marriageAtIndex:(int32_t) index;
- (MUserDatePage_Builder*) replaceMarriageAtIndex:(int32_t) index with:(MMarriageMini*) _value;
- (MUserDatePage_Builder*) addMarriage:(MMarriageMini*) _value;
- (MUserDatePage_Builder*) addAllMarriage:(NSArray*) values;
- (MUserDatePage_Builder*) clearMarriageList;

- (NSArray*) dateList;
- (MDate*) dateAtIndex:(int32_t) index;
- (MUserDatePage_Builder*) replaceDateAtIndex:(int32_t) index with:(MDate*) _value;
- (MUserDatePage_Builder*) addDate:(MDate*) _value;
- (MUserDatePage_Builder*) addAllDate:(NSArray*) values;
- (MUserDatePage_Builder*) clearDateList;
@end

