// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "ProtocolBuffers.h"

@class MChat;
@class MChatView;
@class MChatViewList;
@class MChatViewList_Builder;
@class MChatView_Builder;
@class MChat_Builder;
@class MMsg;
@class MMsg_Builder;
@class MNotify;
@class MNotifyList;
@class MNotifyList_Builder;
@class MNotify_Builder;

@interface UserChatRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

@interface MChat : PBGeneratedMessage {
@private
  BOOL hasType_:1;
  BOOL hasState_:1;
  BOOL hasFriend_:1;
  BOOL hasTitle_:1;
  BOOL hasStatus_:1;
  BOOL hasTargetId_:1;
  BOOL hasTargetImg_:1;
  BOOL hasFid_:1;
  BOOL hasViewId_:1;
  int32_t type;
  int32_t state;
  int32_t friend;
  NSString* title;
  NSString* status;
  NSString* targetId;
  NSString* targetImg;
  NSString* fid;
  NSString* viewId;
  NSMutableArray* mutableMsgList;
}
- (BOOL) hasType;
- (BOOL) hasTitle;
- (BOOL) hasState;
- (BOOL) hasStatus;
- (BOOL) hasTargetId;
- (BOOL) hasTargetImg;
- (BOOL) hasFid;
- (BOOL) hasFriend;
- (BOOL) hasViewId;
@property (readonly) int32_t type;
@property (readonly, retain) NSString* title;
@property (readonly) int32_t state;
@property (readonly, retain) NSString* status;
@property (readonly, retain) NSString* targetId;
@property (readonly, retain) NSString* targetImg;
@property (readonly, retain) NSString* fid;
@property (readonly) int32_t friend;
@property (readonly, retain) NSString* viewId;
- (NSArray*) msgList;
- (MMsg*) msgAtIndex:(int32_t) index;

+ (MChat*) defaultInstance;
- (MChat*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MChat_Builder*) builder;
+ (MChat_Builder*) builder;
+ (MChat_Builder*) builderWithPrototype:(MChat*) prototype;

+ (MChat*) parseFromData:(NSData*) data;
+ (MChat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MChat*) parseFromInputStream:(NSInputStream*) input;
+ (MChat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MChat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MChat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MChat_Builder : PBGeneratedMessage_Builder {
@private
  MChat* protobufBuilderResult;
}

- (MChat*) defaultInstance;

- (MChat_Builder*) clear;
- (MChat_Builder*) clone;

- (MChat*) build;
- (MChat*) buildPartial;

- (MChat_Builder*) mergeFrom:(MChat*) other;
- (MChat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MChat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (int32_t) type;
- (MChat_Builder*) setType:(int32_t) _value;
- (MChat_Builder*) clearType;

- (BOOL) hasTitle;
- (NSString*) title;
- (MChat_Builder*) setTitle:(NSString*) _value;
- (MChat_Builder*) clearTitle;

- (BOOL) hasState;
- (int32_t) state;
- (MChat_Builder*) setState:(int32_t) _value;
- (MChat_Builder*) clearState;

- (BOOL) hasStatus;
- (NSString*) status;
- (MChat_Builder*) setStatus:(NSString*) _value;
- (MChat_Builder*) clearStatus;

- (BOOL) hasTargetId;
- (NSString*) targetId;
- (MChat_Builder*) setTargetId:(NSString*) _value;
- (MChat_Builder*) clearTargetId;

- (BOOL) hasTargetImg;
- (NSString*) targetImg;
- (MChat_Builder*) setTargetImg:(NSString*) _value;
- (MChat_Builder*) clearTargetImg;

- (BOOL) hasFid;
- (NSString*) fid;
- (MChat_Builder*) setFid:(NSString*) _value;
- (MChat_Builder*) clearFid;

- (BOOL) hasFriend;
- (int32_t) friend;
- (MChat_Builder*) setFriend:(int32_t) _value;
- (MChat_Builder*) clearFriend;

- (NSArray*) msgList;
- (MMsg*) msgAtIndex:(int32_t) index;
- (MChat_Builder*) replaceMsgAtIndex:(int32_t) index with:(MMsg*) _value;
- (MChat_Builder*) addMsg:(MMsg*) _value;
- (MChat_Builder*) addAllMsg:(NSArray*) values;
- (MChat_Builder*) clearMsgList;

- (BOOL) hasViewId;
- (NSString*) viewId;
- (MChat_Builder*) setViewId:(NSString*) _value;
- (MChat_Builder*) clearViewId;
@end

@interface MMsg : PBGeneratedMessage {
@private
  BOOL hasType_:1;
  BOOL hasId_:1;
  BOOL hasUserid_:1;
  BOOL hasContent_:1;
  BOOL hasTime_:1;
  BOOL hasCreateTime_:1;
  BOOL hasArg_:1;
  int32_t type;
  NSString* id;
  NSString* userid;
  NSString* content;
  NSString* time;
  NSString* createTime;
  NSString* arg;
}
- (BOOL) hasId;
- (BOOL) hasUserid;
- (BOOL) hasType;
- (BOOL) hasContent;
- (BOOL) hasTime;
- (BOOL) hasCreateTime;
- (BOOL) hasArg;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* userid;
@property (readonly) int32_t type;
@property (readonly, retain) NSString* content;
@property (readonly, retain) NSString* time;
@property (readonly, retain) NSString* createTime;
@property (readonly, retain) NSString* arg;

+ (MMsg*) defaultInstance;
- (MMsg*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MMsg_Builder*) builder;
+ (MMsg_Builder*) builder;
+ (MMsg_Builder*) builderWithPrototype:(MMsg*) prototype;

+ (MMsg*) parseFromData:(NSData*) data;
+ (MMsg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMsg*) parseFromInputStream:(NSInputStream*) input;
+ (MMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MMsg_Builder : PBGeneratedMessage_Builder {
@private
  MMsg* protobufBuilderResult;
}

- (MMsg*) defaultInstance;

- (MMsg_Builder*) clear;
- (MMsg_Builder*) clone;

- (MMsg*) build;
- (MMsg*) buildPartial;

- (MMsg_Builder*) mergeFrom:(MMsg*) other;
- (MMsg_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MMsg_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MMsg_Builder*) setId:(NSString*) _value;
- (MMsg_Builder*) clearId;

- (BOOL) hasUserid;
- (NSString*) userid;
- (MMsg_Builder*) setUserid:(NSString*) _value;
- (MMsg_Builder*) clearUserid;

- (BOOL) hasType;
- (int32_t) type;
- (MMsg_Builder*) setType:(int32_t) _value;
- (MMsg_Builder*) clearType;

- (BOOL) hasContent;
- (NSString*) content;
- (MMsg_Builder*) setContent:(NSString*) _value;
- (MMsg_Builder*) clearContent;

- (BOOL) hasTime;
- (NSString*) time;
- (MMsg_Builder*) setTime:(NSString*) _value;
- (MMsg_Builder*) clearTime;

- (BOOL) hasCreateTime;
- (NSString*) createTime;
- (MMsg_Builder*) setCreateTime:(NSString*) _value;
- (MMsg_Builder*) clearCreateTime;

- (BOOL) hasArg;
- (NSString*) arg;
- (MMsg_Builder*) setArg:(NSString*) _value;
- (MMsg_Builder*) clearArg;
@end

@interface MChatView : PBGeneratedMessage {
@private
  BOOL hasType_:1;
  BOOL hasState_:1;
  BOOL hasTitle_:1;
  BOOL hasTargetId_:1;
  BOOL hasTargetImg_:1;
  BOOL hasTargetNickname_:1;
  BOOL hasId_:1;
  BOOL hasTime_:1;
  BOOL hasMsg_:1;
  BOOL hasMsgCnt_:1;
  int32_t type;
  int32_t state;
  NSString* title;
  NSString* targetId;
  NSString* targetImg;
  NSString* targetNickname;
  NSString* id;
  NSString* time;
  NSString* msg;
  NSString* msgCnt;
}
- (BOOL) hasType;
- (BOOL) hasTitle;
- (BOOL) hasState;
- (BOOL) hasTargetId;
- (BOOL) hasTargetImg;
- (BOOL) hasTargetNickname;
- (BOOL) hasId;
- (BOOL) hasTime;
- (BOOL) hasMsg;
- (BOOL) hasMsgCnt;
@property (readonly) int32_t type;
@property (readonly, retain) NSString* title;
@property (readonly) int32_t state;
@property (readonly, retain) NSString* targetId;
@property (readonly, retain) NSString* targetImg;
@property (readonly, retain) NSString* targetNickname;
@property (readonly, retain) NSString* id;
@property (readonly, retain) NSString* time;
@property (readonly, retain) NSString* msg;
@property (readonly, retain) NSString* msgCnt;

+ (MChatView*) defaultInstance;
- (MChatView*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MChatView_Builder*) builder;
+ (MChatView_Builder*) builder;
+ (MChatView_Builder*) builderWithPrototype:(MChatView*) prototype;

+ (MChatView*) parseFromData:(NSData*) data;
+ (MChatView*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MChatView*) parseFromInputStream:(NSInputStream*) input;
+ (MChatView*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MChatView*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MChatView*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MChatView_Builder : PBGeneratedMessage_Builder {
@private
  MChatView* protobufBuilderResult;
}

- (MChatView*) defaultInstance;

- (MChatView_Builder*) clear;
- (MChatView_Builder*) clone;

- (MChatView*) build;
- (MChatView*) buildPartial;

- (MChatView_Builder*) mergeFrom:(MChatView*) other;
- (MChatView_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MChatView_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (int32_t) type;
- (MChatView_Builder*) setType:(int32_t) _value;
- (MChatView_Builder*) clearType;

- (BOOL) hasTitle;
- (NSString*) title;
- (MChatView_Builder*) setTitle:(NSString*) _value;
- (MChatView_Builder*) clearTitle;

- (BOOL) hasState;
- (int32_t) state;
- (MChatView_Builder*) setState:(int32_t) _value;
- (MChatView_Builder*) clearState;

- (BOOL) hasTargetId;
- (NSString*) targetId;
- (MChatView_Builder*) setTargetId:(NSString*) _value;
- (MChatView_Builder*) clearTargetId;

- (BOOL) hasTargetImg;
- (NSString*) targetImg;
- (MChatView_Builder*) setTargetImg:(NSString*) _value;
- (MChatView_Builder*) clearTargetImg;

- (BOOL) hasTargetNickname;
- (NSString*) targetNickname;
- (MChatView_Builder*) setTargetNickname:(NSString*) _value;
- (MChatView_Builder*) clearTargetNickname;

- (BOOL) hasId;
- (NSString*) id;
- (MChatView_Builder*) setId:(NSString*) _value;
- (MChatView_Builder*) clearId;

- (BOOL) hasTime;
- (NSString*) time;
- (MChatView_Builder*) setTime:(NSString*) _value;
- (MChatView_Builder*) clearTime;

- (BOOL) hasMsg;
- (NSString*) msg;
- (MChatView_Builder*) setMsg:(NSString*) _value;
- (MChatView_Builder*) clearMsg;

- (BOOL) hasMsgCnt;
- (NSString*) msgCnt;
- (MChatView_Builder*) setMsgCnt:(NSString*) _value;
- (MChatView_Builder*) clearMsgCnt;
@end

@interface MChatViewList : PBGeneratedMessage {
@private
  NSMutableArray* mutableViewsList;
}
- (NSArray*) viewsList;
- (MChatView*) viewsAtIndex:(int32_t) index;

+ (MChatViewList*) defaultInstance;
- (MChatViewList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MChatViewList_Builder*) builder;
+ (MChatViewList_Builder*) builder;
+ (MChatViewList_Builder*) builderWithPrototype:(MChatViewList*) prototype;

+ (MChatViewList*) parseFromData:(NSData*) data;
+ (MChatViewList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MChatViewList*) parseFromInputStream:(NSInputStream*) input;
+ (MChatViewList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MChatViewList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MChatViewList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MChatViewList_Builder : PBGeneratedMessage_Builder {
@private
  MChatViewList* protobufBuilderResult;
}

- (MChatViewList*) defaultInstance;

- (MChatViewList_Builder*) clear;
- (MChatViewList_Builder*) clone;

- (MChatViewList*) build;
- (MChatViewList*) buildPartial;

- (MChatViewList_Builder*) mergeFrom:(MChatViewList*) other;
- (MChatViewList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MChatViewList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSArray*) viewsList;
- (MChatView*) viewsAtIndex:(int32_t) index;
- (MChatViewList_Builder*) replaceViewsAtIndex:(int32_t) index with:(MChatView*) _value;
- (MChatViewList_Builder*) addViews:(MChatView*) _value;
- (MChatViewList_Builder*) addAllViews:(NSArray*) values;
- (MChatViewList_Builder*) clearViewsList;
@end

@interface MNotify : PBGeneratedMessage {
@private
  BOOL hasType_:1;
  BOOL hasId_:1;
  BOOL hasImg_:1;
  BOOL hasContent_:1;
  BOOL hasCreateTime_:1;
  int32_t type;
  NSString* id;
  NSString* img;
  NSString* content;
  NSString* createTime;
}
- (BOOL) hasId;
- (BOOL) hasType;
- (BOOL) hasImg;
- (BOOL) hasContent;
- (BOOL) hasCreateTime;
@property (readonly, retain) NSString* id;
@property (readonly) int32_t type;
@property (readonly, retain) NSString* img;
@property (readonly, retain) NSString* content;
@property (readonly, retain) NSString* createTime;

+ (MNotify*) defaultInstance;
- (MNotify*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MNotify_Builder*) builder;
+ (MNotify_Builder*) builder;
+ (MNotify_Builder*) builderWithPrototype:(MNotify*) prototype;

+ (MNotify*) parseFromData:(NSData*) data;
+ (MNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MNotify*) parseFromInputStream:(NSInputStream*) input;
+ (MNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MNotify_Builder : PBGeneratedMessage_Builder {
@private
  MNotify* protobufBuilderResult;
}

- (MNotify*) defaultInstance;

- (MNotify_Builder*) clear;
- (MNotify_Builder*) clone;

- (MNotify*) build;
- (MNotify*) buildPartial;

- (MNotify_Builder*) mergeFrom:(MNotify*) other;
- (MNotify_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MNotify_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (NSString*) id;
- (MNotify_Builder*) setId:(NSString*) _value;
- (MNotify_Builder*) clearId;

- (BOOL) hasType;
- (int32_t) type;
- (MNotify_Builder*) setType:(int32_t) _value;
- (MNotify_Builder*) clearType;

- (BOOL) hasImg;
- (NSString*) img;
- (MNotify_Builder*) setImg:(NSString*) _value;
- (MNotify_Builder*) clearImg;

- (BOOL) hasContent;
- (NSString*) content;
- (MNotify_Builder*) setContent:(NSString*) _value;
- (MNotify_Builder*) clearContent;

- (BOOL) hasCreateTime;
- (NSString*) createTime;
- (MNotify_Builder*) setCreateTime:(NSString*) _value;
- (MNotify_Builder*) clearCreateTime;
@end

@interface MNotifyList : PBGeneratedMessage {
@private
  BOOL hasNotify_:1;
  MNotify* notify;
}
- (BOOL) hasNotify;
@property (readonly, retain) MNotify* notify;

+ (MNotifyList*) defaultInstance;
- (MNotifyList*) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MNotifyList_Builder*) builder;
+ (MNotifyList_Builder*) builder;
+ (MNotifyList_Builder*) builderWithPrototype:(MNotifyList*) prototype;

+ (MNotifyList*) parseFromData:(NSData*) data;
+ (MNotifyList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MNotifyList*) parseFromInputStream:(NSInputStream*) input;
+ (MNotifyList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (MNotifyList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (MNotifyList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MNotifyList_Builder : PBGeneratedMessage_Builder {
@private
  MNotifyList* protobufBuilderResult;
}

- (MNotifyList*) defaultInstance;

- (MNotifyList_Builder*) clear;
- (MNotifyList_Builder*) clone;

- (MNotifyList*) build;
- (MNotifyList*) buildPartial;

- (MNotifyList_Builder*) mergeFrom:(MNotifyList*) other;
- (MNotifyList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MNotifyList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNotify;
- (MNotify*) notify;
- (MNotifyList_Builder*) setNotify:(MNotify*) _value;
- (MNotifyList_Builder*) setNotifyBuilder:(MNotify_Builder*) builderForValue;
- (MNotifyList_Builder*) mergeNotify:(MNotify*) _value;
- (MNotifyList_Builder*) clearNotify;
@end

