// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "UserChat.pb.h"

@implementation UserChatRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [UserChatRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface MChat ()
@property int32_t type;
@property (retain) NSString* title;
@property int32_t state;
@property (retain) NSString* status;
@property (retain) NSString* targetId;
@property (retain) NSString* targetImg;
@property (retain) NSString* fid;
@property int32_t friend;
@property (retain) NSMutableArray* mutableMsgList;
@property (retain) NSString* viewId;
@end

@implementation MChat

- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) _value {
  hasType_ = !!_value;
}
@synthesize type;
- (BOOL) hasTitle {
  return !!hasTitle_;
}
- (void) setHasTitle:(BOOL) _value {
  hasTitle_ = !!_value;
}
@synthesize title;
- (BOOL) hasState {
  return !!hasState_;
}
- (void) setHasState:(BOOL) _value {
  hasState_ = !!_value;
}
@synthesize state;
- (BOOL) hasStatus {
  return !!hasStatus_;
}
- (void) setHasStatus:(BOOL) _value {
  hasStatus_ = !!_value;
}
@synthesize status;
- (BOOL) hasTargetId {
  return !!hasTargetId_;
}
- (void) setHasTargetId:(BOOL) _value {
  hasTargetId_ = !!_value;
}
@synthesize targetId;
- (BOOL) hasTargetImg {
  return !!hasTargetImg_;
}
- (void) setHasTargetImg:(BOOL) _value {
  hasTargetImg_ = !!_value;
}
@synthesize targetImg;
- (BOOL) hasFid {
  return !!hasFid_;
}
- (void) setHasFid:(BOOL) _value {
  hasFid_ = !!_value;
}
@synthesize fid;
- (BOOL) hasFriend {
  return !!hasFriend_;
}
- (void) setHasFriend:(BOOL) _value {
  hasFriend_ = !!_value;
}
@synthesize friend;
@synthesize mutableMsgList;
- (BOOL) hasViewId {
  return !!hasViewId_;
}
- (void) setHasViewId:(BOOL) _value {
  hasViewId_ = !!_value;
}
@synthesize viewId;
- (void) dealloc {
  self.title = nil;
  self.status = nil;
  self.targetId = nil;
  self.targetImg = nil;
  self.fid = nil;
  self.mutableMsgList = nil;
  self.viewId = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.type = 0;
    self.title = @"";
    self.state = 0;
    self.status = @"";
    self.targetId = @"";
    self.targetImg = @"";
    self.fid = @"";
    self.friend = 0;
    self.viewId = @"";
  }
  return self;
}
static MChat* defaultMChatInstance = nil;
+ (void) initialize {
  if (self == [MChat class]) {
    defaultMChatInstance = [[MChat alloc] init];
  }
}
+ (MChat*) defaultInstance {
  return defaultMChatInstance;
}
- (MChat*) defaultInstance {
  return defaultMChatInstance;
}
- (NSArray*) msgList {
  return mutableMsgList;
}
- (MMsg*) msgAtIndex:(int32_t) index {
  id _value = [mutableMsgList objectAtIndex:index];
  return _value;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasType) {
    [output writeInt32:1 value:self.type];
  }
  if (self.hasTitle) {
    [output writeString:2 value:self.title];
  }
  if (self.hasState) {
    [output writeInt32:3 value:self.state];
  }
  if (self.hasStatus) {
    [output writeString:4 value:self.status];
  }
  if (self.hasTargetId) {
    [output writeString:5 value:self.targetId];
  }
  if (self.hasTargetImg) {
    [output writeString:6 value:self.targetImg];
  }
  if (self.hasFid) {
    [output writeString:7 value:self.fid];
  }
  if (self.hasFriend) {
    [output writeInt32:8 value:self.friend];
  }
  for (MMsg* element in self.msgList) {
    [output writeMessage:9 value:element];
  }
  if (self.hasViewId) {
    [output writeString:10 value:self.viewId];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasType) {
    size += computeInt32Size(1, self.type);
  }
  if (self.hasTitle) {
    size += computeStringSize(2, self.title);
  }
  if (self.hasState) {
    size += computeInt32Size(3, self.state);
  }
  if (self.hasStatus) {
    size += computeStringSize(4, self.status);
  }
  if (self.hasTargetId) {
    size += computeStringSize(5, self.targetId);
  }
  if (self.hasTargetImg) {
    size += computeStringSize(6, self.targetImg);
  }
  if (self.hasFid) {
    size += computeStringSize(7, self.fid);
  }
  if (self.hasFriend) {
    size += computeInt32Size(8, self.friend);
  }
  for (MMsg* element in self.msgList) {
    size += computeMessageSize(9, element);
  }
  if (self.hasViewId) {
    size += computeStringSize(10, self.viewId);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MChat*) parseFromData:(NSData*) data {
  return (MChat*)[[[MChat builder] mergeFromData:data] build];
}
+ (MChat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MChat*)[[[MChat builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MChat*) parseFromInputStream:(NSInputStream*) input {
  return (MChat*)[[[MChat builder] mergeFromInputStream:input] build];
}
+ (MChat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MChat*)[[[MChat builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MChat*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MChat*)[[[MChat builder] mergeFromCodedInputStream:input] build];
}
+ (MChat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MChat*)[[[MChat builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MChat_Builder*) builder {
  return [[[MChat_Builder alloc] init] autorelease];
}
+ (MChat_Builder*) builderWithPrototype:(MChat*) prototype {
  return [[MChat builder] mergeFrom:prototype];
}
- (MChat_Builder*) builder {
  return [MChat builder];
}
@end

@interface MChat_Builder()
@property (retain) MChat* protobufBuilderResult;
@end

@implementation MChat_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MChat alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MChat_Builder*) clear {
  self.protobufBuilderResult = [[[MChat alloc] init] autorelease];
  return self;
}
- (MChat_Builder*) clone {
  return [MChat builderWithPrototype:protobufBuilderResult];
}
- (MChat*) defaultInstance {
  return [MChat defaultInstance];
}
- (MChat*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MChat*) buildPartial {
  MChat* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MChat_Builder*) mergeFrom:(MChat*) other {
  if (other == [MChat defaultInstance]) {
    return self;
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  if (other.hasTitle) {
    [self setTitle:other.title];
  }
  if (other.hasState) {
    [self setState:other.state];
  }
  if (other.hasStatus) {
    [self setStatus:other.status];
  }
  if (other.hasTargetId) {
    [self setTargetId:other.targetId];
  }
  if (other.hasTargetImg) {
    [self setTargetImg:other.targetImg];
  }
  if (other.hasFid) {
    [self setFid:other.fid];
  }
  if (other.hasFriend) {
    [self setFriend:other.friend];
  }
  if (other.mutableMsgList.count > 0) {
    if (protobufBuilderResult.mutableMsgList == nil) {
      protobufBuilderResult.mutableMsgList = [NSMutableArray array];
    }
    [protobufBuilderResult.mutableMsgList addObjectsFromArray:other.mutableMsgList];
  }
  if (other.hasViewId) {
    [self setViewId:other.viewId];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MChat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MChat_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setType:[input readInt32]];
        break;
      }
      case 18: {
        [self setTitle:[input readString]];
        break;
      }
      case 24: {
        [self setState:[input readInt32]];
        break;
      }
      case 34: {
        [self setStatus:[input readString]];
        break;
      }
      case 42: {
        [self setTargetId:[input readString]];
        break;
      }
      case 50: {
        [self setTargetImg:[input readString]];
        break;
      }
      case 58: {
        [self setFid:[input readString]];
        break;
      }
      case 64: {
        [self setFriend:[input readInt32]];
        break;
      }
      case 74: {
        MMsg_Builder* subBuilder = [MMsg builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addMsg:[subBuilder buildPartial]];
        break;
      }
      case 82: {
        [self setViewId:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasType {
  return protobufBuilderResult.hasType;
}
- (int32_t) type {
  return protobufBuilderResult.type;
}
- (MChat_Builder*) setType:(int32_t) _value {
  protobufBuilderResult.hasType = YES;
  protobufBuilderResult.type = _value;
  return self;
}
- (MChat_Builder*) clearType {
  protobufBuilderResult.hasType = NO;
  protobufBuilderResult.type = 0;
  return self;
}
- (BOOL) hasTitle {
  return protobufBuilderResult.hasTitle;
}
- (NSString*) title {
  return protobufBuilderResult.title;
}
- (MChat_Builder*) setTitle:(NSString*) _value {
  protobufBuilderResult.hasTitle = YES;
  protobufBuilderResult.title = _value;
  return self;
}
- (MChat_Builder*) clearTitle {
  protobufBuilderResult.hasTitle = NO;
  protobufBuilderResult.title = @"";
  return self;
}
- (BOOL) hasState {
  return protobufBuilderResult.hasState;
}
- (int32_t) state {
  return protobufBuilderResult.state;
}
- (MChat_Builder*) setState:(int32_t) _value {
  protobufBuilderResult.hasState = YES;
  protobufBuilderResult.state = _value;
  return self;
}
- (MChat_Builder*) clearState {
  protobufBuilderResult.hasState = NO;
  protobufBuilderResult.state = 0;
  return self;
}
- (BOOL) hasStatus {
  return protobufBuilderResult.hasStatus;
}
- (NSString*) status {
  return protobufBuilderResult.status;
}
- (MChat_Builder*) setStatus:(NSString*) _value {
  protobufBuilderResult.hasStatus = YES;
  protobufBuilderResult.status = _value;
  return self;
}
- (MChat_Builder*) clearStatus {
  protobufBuilderResult.hasStatus = NO;
  protobufBuilderResult.status = @"";
  return self;
}
- (BOOL) hasTargetId {
  return protobufBuilderResult.hasTargetId;
}
- (NSString*) targetId {
  return protobufBuilderResult.targetId;
}
- (MChat_Builder*) setTargetId:(NSString*) _value {
  protobufBuilderResult.hasTargetId = YES;
  protobufBuilderResult.targetId = _value;
  return self;
}
- (MChat_Builder*) clearTargetId {
  protobufBuilderResult.hasTargetId = NO;
  protobufBuilderResult.targetId = @"";
  return self;
}
- (BOOL) hasTargetImg {
  return protobufBuilderResult.hasTargetImg;
}
- (NSString*) targetImg {
  return protobufBuilderResult.targetImg;
}
- (MChat_Builder*) setTargetImg:(NSString*) _value {
  protobufBuilderResult.hasTargetImg = YES;
  protobufBuilderResult.targetImg = _value;
  return self;
}
- (MChat_Builder*) clearTargetImg {
  protobufBuilderResult.hasTargetImg = NO;
  protobufBuilderResult.targetImg = @"";
  return self;
}
- (BOOL) hasFid {
  return protobufBuilderResult.hasFid;
}
- (NSString*) fid {
  return protobufBuilderResult.fid;
}
- (MChat_Builder*) setFid:(NSString*) _value {
  protobufBuilderResult.hasFid = YES;
  protobufBuilderResult.fid = _value;
  return self;
}
- (MChat_Builder*) clearFid {
  protobufBuilderResult.hasFid = NO;
  protobufBuilderResult.fid = @"";
  return self;
}
- (BOOL) hasFriend {
  return protobufBuilderResult.hasFriend;
}
- (int32_t) friend {
  return protobufBuilderResult.friend;
}
- (MChat_Builder*) setFriend:(int32_t) _value {
  protobufBuilderResult.hasFriend = YES;
  protobufBuilderResult.friend = _value;
  return self;
}
- (MChat_Builder*) clearFriend {
  protobufBuilderResult.hasFriend = NO;
  protobufBuilderResult.friend = 0;
  return self;
}
- (NSArray*) msgList {
  if (protobufBuilderResult.mutableMsgList == nil) { return [NSArray array]; }
  return protobufBuilderResult.mutableMsgList;
}
- (MMsg*) msgAtIndex:(int32_t) index {
  return [protobufBuilderResult msgAtIndex:index];
}
- (MChat_Builder*) replaceMsgAtIndex:(int32_t) index with:(MMsg*) _value {
  [protobufBuilderResult.mutableMsgList replaceObjectAtIndex:index withObject:_value];
  return self;
}
- (MChat_Builder*) addAllMsg:(NSArray*) values {
  if (protobufBuilderResult.mutableMsgList == nil) {
    protobufBuilderResult.mutableMsgList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableMsgList addObjectsFromArray:values];
  return self;
}
- (MChat_Builder*) clearMsgList {
  protobufBuilderResult.mutableMsgList = nil;
  return self;
}
- (MChat_Builder*) addMsg:(MMsg*) _value {
  if (protobufBuilderResult.mutableMsgList == nil) {
    protobufBuilderResult.mutableMsgList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableMsgList addObject:_value];
  return self;
}
- (BOOL) hasViewId {
  return protobufBuilderResult.hasViewId;
}
- (NSString*) viewId {
  return protobufBuilderResult.viewId;
}
- (MChat_Builder*) setViewId:(NSString*) _value {
  protobufBuilderResult.hasViewId = YES;
  protobufBuilderResult.viewId = _value;
  return self;
}
- (MChat_Builder*) clearViewId {
  protobufBuilderResult.hasViewId = NO;
  protobufBuilderResult.viewId = @"";
  return self;
}
@end

@interface MMsg ()
@property (retain) NSString* id;
@property (retain) NSString* userid;
@property int32_t type;
@property (retain) NSString* content;
@property (retain) NSString* time;
@property (retain) NSString* createTime;
@property (retain) NSString* arg;
@end

@implementation MMsg

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value {
  hasId_ = !!_value;
}
@synthesize id;
- (BOOL) hasUserid {
  return !!hasUserid_;
}
- (void) setHasUserid:(BOOL) _value {
  hasUserid_ = !!_value;
}
@synthesize userid;
- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) _value {
  hasType_ = !!_value;
}
@synthesize type;
- (BOOL) hasContent {
  return !!hasContent_;
}
- (void) setHasContent:(BOOL) _value {
  hasContent_ = !!_value;
}
@synthesize content;
- (BOOL) hasTime {
  return !!hasTime_;
}
- (void) setHasTime:(BOOL) _value {
  hasTime_ = !!_value;
}
@synthesize time;
- (BOOL) hasCreateTime {
  return !!hasCreateTime_;
}
- (void) setHasCreateTime:(BOOL) _value {
  hasCreateTime_ = !!_value;
}
@synthesize createTime;
- (BOOL) hasArg {
  return !!hasArg_;
}
- (void) setHasArg:(BOOL) _value {
  hasArg_ = !!_value;
}
@synthesize arg;
- (void) dealloc {
  self.id = nil;
  self.userid = nil;
  self.content = nil;
  self.time = nil;
  self.createTime = nil;
  self.arg = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = @"";
    self.userid = @"";
    self.type = 0;
    self.content = @"";
    self.time = @"";
    self.createTime = @"";
    self.arg = @"";
  }
  return self;
}
static MMsg* defaultMMsgInstance = nil;
+ (void) initialize {
  if (self == [MMsg class]) {
    defaultMMsgInstance = [[MMsg alloc] init];
  }
}
+ (MMsg*) defaultInstance {
  return defaultMMsgInstance;
}
- (MMsg*) defaultInstance {
  return defaultMMsgInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeString:1 value:self.id];
  }
  if (self.hasUserid) {
    [output writeString:2 value:self.userid];
  }
  if (self.hasType) {
    [output writeInt32:3 value:self.type];
  }
  if (self.hasContent) {
    [output writeString:4 value:self.content];
  }
  if (self.hasTime) {
    [output writeString:5 value:self.time];
  }
  if (self.hasCreateTime) {
    [output writeString:6 value:self.createTime];
  }
  if (self.hasArg) {
    [output writeString:7 value:self.arg];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasId) {
    size += computeStringSize(1, self.id);
  }
  if (self.hasUserid) {
    size += computeStringSize(2, self.userid);
  }
  if (self.hasType) {
    size += computeInt32Size(3, self.type);
  }
  if (self.hasContent) {
    size += computeStringSize(4, self.content);
  }
  if (self.hasTime) {
    size += computeStringSize(5, self.time);
  }
  if (self.hasCreateTime) {
    size += computeStringSize(6, self.createTime);
  }
  if (self.hasArg) {
    size += computeStringSize(7, self.arg);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MMsg*) parseFromData:(NSData*) data {
  return (MMsg*)[[[MMsg builder] mergeFromData:data] build];
}
+ (MMsg*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MMsg*)[[[MMsg builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MMsg*) parseFromInputStream:(NSInputStream*) input {
  return (MMsg*)[[[MMsg builder] mergeFromInputStream:input] build];
}
+ (MMsg*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MMsg*)[[[MMsg builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MMsg*)[[[MMsg builder] mergeFromCodedInputStream:input] build];
}
+ (MMsg*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MMsg*)[[[MMsg builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MMsg_Builder*) builder {
  return [[[MMsg_Builder alloc] init] autorelease];
}
+ (MMsg_Builder*) builderWithPrototype:(MMsg*) prototype {
  return [[MMsg builder] mergeFrom:prototype];
}
- (MMsg_Builder*) builder {
  return [MMsg builder];
}
@end

@interface MMsg_Builder()
@property (retain) MMsg* protobufBuilderResult;
@end

@implementation MMsg_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MMsg alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MMsg_Builder*) clear {
  self.protobufBuilderResult = [[[MMsg alloc] init] autorelease];
  return self;
}
- (MMsg_Builder*) clone {
  return [MMsg builderWithPrototype:protobufBuilderResult];
}
- (MMsg*) defaultInstance {
  return [MMsg defaultInstance];
}
- (MMsg*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MMsg*) buildPartial {
  MMsg* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MMsg_Builder*) mergeFrom:(MMsg*) other {
  if (other == [MMsg defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasUserid) {
    [self setUserid:other.userid];
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  if (other.hasContent) {
    [self setContent:other.content];
  }
  if (other.hasTime) {
    [self setTime:other.time];
  }
  if (other.hasCreateTime) {
    [self setCreateTime:other.createTime];
  }
  if (other.hasArg) {
    [self setArg:other.arg];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MMsg_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MMsg_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setId:[input readString]];
        break;
      }
      case 18: {
        [self setUserid:[input readString]];
        break;
      }
      case 24: {
        [self setType:[input readInt32]];
        break;
      }
      case 34: {
        [self setContent:[input readString]];
        break;
      }
      case 42: {
        [self setTime:[input readString]];
        break;
      }
      case 50: {
        [self setCreateTime:[input readString]];
        break;
      }
      case 58: {
        [self setArg:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return protobufBuilderResult.hasId;
}
- (NSString*) id {
  return protobufBuilderResult.id;
}
- (MMsg_Builder*) setId:(NSString*) _value {
  protobufBuilderResult.hasId = YES;
  protobufBuilderResult.id = _value;
  return self;
}
- (MMsg_Builder*) clearId {
  protobufBuilderResult.hasId = NO;
  protobufBuilderResult.id = @"";
  return self;
}
- (BOOL) hasUserid {
  return protobufBuilderResult.hasUserid;
}
- (NSString*) userid {
  return protobufBuilderResult.userid;
}
- (MMsg_Builder*) setUserid:(NSString*) _value {
  protobufBuilderResult.hasUserid = YES;
  protobufBuilderResult.userid = _value;
  return self;
}
- (MMsg_Builder*) clearUserid {
  protobufBuilderResult.hasUserid = NO;
  protobufBuilderResult.userid = @"";
  return self;
}
- (BOOL) hasType {
  return protobufBuilderResult.hasType;
}
- (int32_t) type {
  return protobufBuilderResult.type;
}
- (MMsg_Builder*) setType:(int32_t) _value {
  protobufBuilderResult.hasType = YES;
  protobufBuilderResult.type = _value;
  return self;
}
- (MMsg_Builder*) clearType {
  protobufBuilderResult.hasType = NO;
  protobufBuilderResult.type = 0;
  return self;
}
- (BOOL) hasContent {
  return protobufBuilderResult.hasContent;
}
- (NSString*) content {
  return protobufBuilderResult.content;
}
- (MMsg_Builder*) setContent:(NSString*) _value {
  protobufBuilderResult.hasContent = YES;
  protobufBuilderResult.content = _value;
  return self;
}
- (MMsg_Builder*) clearContent {
  protobufBuilderResult.hasContent = NO;
  protobufBuilderResult.content = @"";
  return self;
}
- (BOOL) hasTime {
  return protobufBuilderResult.hasTime;
}
- (NSString*) time {
  return protobufBuilderResult.time;
}
- (MMsg_Builder*) setTime:(NSString*) _value {
  protobufBuilderResult.hasTime = YES;
  protobufBuilderResult.time = _value;
  return self;
}
- (MMsg_Builder*) clearTime {
  protobufBuilderResult.hasTime = NO;
  protobufBuilderResult.time = @"";
  return self;
}
- (BOOL) hasCreateTime {
  return protobufBuilderResult.hasCreateTime;
}
- (NSString*) createTime {
  return protobufBuilderResult.createTime;
}
- (MMsg_Builder*) setCreateTime:(NSString*) _value {
  protobufBuilderResult.hasCreateTime = YES;
  protobufBuilderResult.createTime = _value;
  return self;
}
- (MMsg_Builder*) clearCreateTime {
  protobufBuilderResult.hasCreateTime = NO;
  protobufBuilderResult.createTime = @"";
  return self;
}
- (BOOL) hasArg {
  return protobufBuilderResult.hasArg;
}
- (NSString*) arg {
  return protobufBuilderResult.arg;
}
- (MMsg_Builder*) setArg:(NSString*) _value {
  protobufBuilderResult.hasArg = YES;
  protobufBuilderResult.arg = _value;
  return self;
}
- (MMsg_Builder*) clearArg {
  protobufBuilderResult.hasArg = NO;
  protobufBuilderResult.arg = @"";
  return self;
}
@end

@interface MChatView ()
@property int32_t type;
@property (retain) NSString* title;
@property int32_t state;
@property (retain) NSString* targetId;
@property (retain) NSString* targetImg;
@property (retain) NSString* targetNickname;
@property (retain) NSString* id;
@property (retain) NSString* time;
@property (retain) NSString* msg;
@property (retain) NSString* msgCnt;
@end

@implementation MChatView

- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) _value {
  hasType_ = !!_value;
}
@synthesize type;
- (BOOL) hasTitle {
  return !!hasTitle_;
}
- (void) setHasTitle:(BOOL) _value {
  hasTitle_ = !!_value;
}
@synthesize title;
- (BOOL) hasState {
  return !!hasState_;
}
- (void) setHasState:(BOOL) _value {
  hasState_ = !!_value;
}
@synthesize state;
- (BOOL) hasTargetId {
  return !!hasTargetId_;
}
- (void) setHasTargetId:(BOOL) _value {
  hasTargetId_ = !!_value;
}
@synthesize targetId;
- (BOOL) hasTargetImg {
  return !!hasTargetImg_;
}
- (void) setHasTargetImg:(BOOL) _value {
  hasTargetImg_ = !!_value;
}
@synthesize targetImg;
- (BOOL) hasTargetNickname {
  return !!hasTargetNickname_;
}
- (void) setHasTargetNickname:(BOOL) _value {
  hasTargetNickname_ = !!_value;
}
@synthesize targetNickname;
- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value {
  hasId_ = !!_value;
}
@synthesize id;
- (BOOL) hasTime {
  return !!hasTime_;
}
- (void) setHasTime:(BOOL) _value {
  hasTime_ = !!_value;
}
@synthesize time;
- (BOOL) hasMsg {
  return !!hasMsg_;
}
- (void) setHasMsg:(BOOL) _value {
  hasMsg_ = !!_value;
}
@synthesize msg;
- (BOOL) hasMsgCnt {
  return !!hasMsgCnt_;
}
- (void) setHasMsgCnt:(BOOL) _value {
  hasMsgCnt_ = !!_value;
}
@synthesize msgCnt;
- (void) dealloc {
  self.title = nil;
  self.targetId = nil;
  self.targetImg = nil;
  self.targetNickname = nil;
  self.id = nil;
  self.time = nil;
  self.msg = nil;
  self.msgCnt = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.type = 0;
    self.title = @"";
    self.state = 0;
    self.targetId = @"";
    self.targetImg = @"";
    self.targetNickname = @"";
    self.id = @"";
    self.time = @"";
    self.msg = @"";
    self.msgCnt = @"";
  }
  return self;
}
static MChatView* defaultMChatViewInstance = nil;
+ (void) initialize {
  if (self == [MChatView class]) {
    defaultMChatViewInstance = [[MChatView alloc] init];
  }
}
+ (MChatView*) defaultInstance {
  return defaultMChatViewInstance;
}
- (MChatView*) defaultInstance {
  return defaultMChatViewInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasType) {
    [output writeInt32:1 value:self.type];
  }
  if (self.hasTitle) {
    [output writeString:2 value:self.title];
  }
  if (self.hasState) {
    [output writeInt32:3 value:self.state];
  }
  if (self.hasTargetId) {
    [output writeString:4 value:self.targetId];
  }
  if (self.hasTargetImg) {
    [output writeString:5 value:self.targetImg];
  }
  if (self.hasTargetNickname) {
    [output writeString:6 value:self.targetNickname];
  }
  if (self.hasId) {
    [output writeString:7 value:self.id];
  }
  if (self.hasTime) {
    [output writeString:8 value:self.time];
  }
  if (self.hasMsg) {
    [output writeString:9 value:self.msg];
  }
  if (self.hasMsgCnt) {
    [output writeString:10 value:self.msgCnt];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasType) {
    size += computeInt32Size(1, self.type);
  }
  if (self.hasTitle) {
    size += computeStringSize(2, self.title);
  }
  if (self.hasState) {
    size += computeInt32Size(3, self.state);
  }
  if (self.hasTargetId) {
    size += computeStringSize(4, self.targetId);
  }
  if (self.hasTargetImg) {
    size += computeStringSize(5, self.targetImg);
  }
  if (self.hasTargetNickname) {
    size += computeStringSize(6, self.targetNickname);
  }
  if (self.hasId) {
    size += computeStringSize(7, self.id);
  }
  if (self.hasTime) {
    size += computeStringSize(8, self.time);
  }
  if (self.hasMsg) {
    size += computeStringSize(9, self.msg);
  }
  if (self.hasMsgCnt) {
    size += computeStringSize(10, self.msgCnt);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MChatView*) parseFromData:(NSData*) data {
  return (MChatView*)[[[MChatView builder] mergeFromData:data] build];
}
+ (MChatView*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MChatView*)[[[MChatView builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MChatView*) parseFromInputStream:(NSInputStream*) input {
  return (MChatView*)[[[MChatView builder] mergeFromInputStream:input] build];
}
+ (MChatView*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MChatView*)[[[MChatView builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MChatView*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MChatView*)[[[MChatView builder] mergeFromCodedInputStream:input] build];
}
+ (MChatView*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MChatView*)[[[MChatView builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MChatView_Builder*) builder {
  return [[[MChatView_Builder alloc] init] autorelease];
}
+ (MChatView_Builder*) builderWithPrototype:(MChatView*) prototype {
  return [[MChatView builder] mergeFrom:prototype];
}
- (MChatView_Builder*) builder {
  return [MChatView builder];
}
@end

@interface MChatView_Builder()
@property (retain) MChatView* protobufBuilderResult;
@end

@implementation MChatView_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MChatView alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MChatView_Builder*) clear {
  self.protobufBuilderResult = [[[MChatView alloc] init] autorelease];
  return self;
}
- (MChatView_Builder*) clone {
  return [MChatView builderWithPrototype:protobufBuilderResult];
}
- (MChatView*) defaultInstance {
  return [MChatView defaultInstance];
}
- (MChatView*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MChatView*) buildPartial {
  MChatView* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MChatView_Builder*) mergeFrom:(MChatView*) other {
  if (other == [MChatView defaultInstance]) {
    return self;
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  if (other.hasTitle) {
    [self setTitle:other.title];
  }
  if (other.hasState) {
    [self setState:other.state];
  }
  if (other.hasTargetId) {
    [self setTargetId:other.targetId];
  }
  if (other.hasTargetImg) {
    [self setTargetImg:other.targetImg];
  }
  if (other.hasTargetNickname) {
    [self setTargetNickname:other.targetNickname];
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasTime) {
    [self setTime:other.time];
  }
  if (other.hasMsg) {
    [self setMsg:other.msg];
  }
  if (other.hasMsgCnt) {
    [self setMsgCnt:other.msgCnt];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MChatView_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MChatView_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setType:[input readInt32]];
        break;
      }
      case 18: {
        [self setTitle:[input readString]];
        break;
      }
      case 24: {
        [self setState:[input readInt32]];
        break;
      }
      case 34: {
        [self setTargetId:[input readString]];
        break;
      }
      case 42: {
        [self setTargetImg:[input readString]];
        break;
      }
      case 50: {
        [self setTargetNickname:[input readString]];
        break;
      }
      case 58: {
        [self setId:[input readString]];
        break;
      }
      case 66: {
        [self setTime:[input readString]];
        break;
      }
      case 74: {
        [self setMsg:[input readString]];
        break;
      }
      case 82: {
        [self setMsgCnt:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasType {
  return protobufBuilderResult.hasType;
}
- (int32_t) type {
  return protobufBuilderResult.type;
}
- (MChatView_Builder*) setType:(int32_t) _value {
  protobufBuilderResult.hasType = YES;
  protobufBuilderResult.type = _value;
  return self;
}
- (MChatView_Builder*) clearType {
  protobufBuilderResult.hasType = NO;
  protobufBuilderResult.type = 0;
  return self;
}
- (BOOL) hasTitle {
  return protobufBuilderResult.hasTitle;
}
- (NSString*) title {
  return protobufBuilderResult.title;
}
- (MChatView_Builder*) setTitle:(NSString*) _value {
  protobufBuilderResult.hasTitle = YES;
  protobufBuilderResult.title = _value;
  return self;
}
- (MChatView_Builder*) clearTitle {
  protobufBuilderResult.hasTitle = NO;
  protobufBuilderResult.title = @"";
  return self;
}
- (BOOL) hasState {
  return protobufBuilderResult.hasState;
}
- (int32_t) state {
  return protobufBuilderResult.state;
}
- (MChatView_Builder*) setState:(int32_t) _value {
  protobufBuilderResult.hasState = YES;
  protobufBuilderResult.state = _value;
  return self;
}
- (MChatView_Builder*) clearState {
  protobufBuilderResult.hasState = NO;
  protobufBuilderResult.state = 0;
  return self;
}
- (BOOL) hasTargetId {
  return protobufBuilderResult.hasTargetId;
}
- (NSString*) targetId {
  return protobufBuilderResult.targetId;
}
- (MChatView_Builder*) setTargetId:(NSString*) _value {
  protobufBuilderResult.hasTargetId = YES;
  protobufBuilderResult.targetId = _value;
  return self;
}
- (MChatView_Builder*) clearTargetId {
  protobufBuilderResult.hasTargetId = NO;
  protobufBuilderResult.targetId = @"";
  return self;
}
- (BOOL) hasTargetImg {
  return protobufBuilderResult.hasTargetImg;
}
- (NSString*) targetImg {
  return protobufBuilderResult.targetImg;
}
- (MChatView_Builder*) setTargetImg:(NSString*) _value {
  protobufBuilderResult.hasTargetImg = YES;
  protobufBuilderResult.targetImg = _value;
  return self;
}
- (MChatView_Builder*) clearTargetImg {
  protobufBuilderResult.hasTargetImg = NO;
  protobufBuilderResult.targetImg = @"";
  return self;
}
- (BOOL) hasTargetNickname {
  return protobufBuilderResult.hasTargetNickname;
}
- (NSString*) targetNickname {
  return protobufBuilderResult.targetNickname;
}
- (MChatView_Builder*) setTargetNickname:(NSString*) _value {
  protobufBuilderResult.hasTargetNickname = YES;
  protobufBuilderResult.targetNickname = _value;
  return self;
}
- (MChatView_Builder*) clearTargetNickname {
  protobufBuilderResult.hasTargetNickname = NO;
  protobufBuilderResult.targetNickname = @"";
  return self;
}
- (BOOL) hasId {
  return protobufBuilderResult.hasId;
}
- (NSString*) id {
  return protobufBuilderResult.id;
}
- (MChatView_Builder*) setId:(NSString*) _value {
  protobufBuilderResult.hasId = YES;
  protobufBuilderResult.id = _value;
  return self;
}
- (MChatView_Builder*) clearId {
  protobufBuilderResult.hasId = NO;
  protobufBuilderResult.id = @"";
  return self;
}
- (BOOL) hasTime {
  return protobufBuilderResult.hasTime;
}
- (NSString*) time {
  return protobufBuilderResult.time;
}
- (MChatView_Builder*) setTime:(NSString*) _value {
  protobufBuilderResult.hasTime = YES;
  protobufBuilderResult.time = _value;
  return self;
}
- (MChatView_Builder*) clearTime {
  protobufBuilderResult.hasTime = NO;
  protobufBuilderResult.time = @"";
  return self;
}
- (BOOL) hasMsg {
  return protobufBuilderResult.hasMsg;
}
- (NSString*) msg {
  return protobufBuilderResult.msg;
}
- (MChatView_Builder*) setMsg:(NSString*) _value {
  protobufBuilderResult.hasMsg = YES;
  protobufBuilderResult.msg = _value;
  return self;
}
- (MChatView_Builder*) clearMsg {
  protobufBuilderResult.hasMsg = NO;
  protobufBuilderResult.msg = @"";
  return self;
}
- (BOOL) hasMsgCnt {
  return protobufBuilderResult.hasMsgCnt;
}
- (NSString*) msgCnt {
  return protobufBuilderResult.msgCnt;
}
- (MChatView_Builder*) setMsgCnt:(NSString*) _value {
  protobufBuilderResult.hasMsgCnt = YES;
  protobufBuilderResult.msgCnt = _value;
  return self;
}
- (MChatView_Builder*) clearMsgCnt {
  protobufBuilderResult.hasMsgCnt = NO;
  protobufBuilderResult.msgCnt = @"";
  return self;
}
@end

@interface MChatViewList ()
@property (retain) NSMutableArray* mutableViewsList;
@end

@implementation MChatViewList

@synthesize mutableViewsList;
- (void) dealloc {
  self.mutableViewsList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static MChatViewList* defaultMChatViewListInstance = nil;
+ (void) initialize {
  if (self == [MChatViewList class]) {
    defaultMChatViewListInstance = [[MChatViewList alloc] init];
  }
}
+ (MChatViewList*) defaultInstance {
  return defaultMChatViewListInstance;
}
- (MChatViewList*) defaultInstance {
  return defaultMChatViewListInstance;
}
- (NSArray*) viewsList {
  return mutableViewsList;
}
- (MChatView*) viewsAtIndex:(int32_t) index {
  id _value = [mutableViewsList objectAtIndex:index];
  return _value;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (MChatView* element in self.viewsList) {
    [output writeMessage:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  for (MChatView* element in self.viewsList) {
    size += computeMessageSize(1, element);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MChatViewList*) parseFromData:(NSData*) data {
  return (MChatViewList*)[[[MChatViewList builder] mergeFromData:data] build];
}
+ (MChatViewList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MChatViewList*)[[[MChatViewList builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MChatViewList*) parseFromInputStream:(NSInputStream*) input {
  return (MChatViewList*)[[[MChatViewList builder] mergeFromInputStream:input] build];
}
+ (MChatViewList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MChatViewList*)[[[MChatViewList builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MChatViewList*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MChatViewList*)[[[MChatViewList builder] mergeFromCodedInputStream:input] build];
}
+ (MChatViewList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MChatViewList*)[[[MChatViewList builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MChatViewList_Builder*) builder {
  return [[[MChatViewList_Builder alloc] init] autorelease];
}
+ (MChatViewList_Builder*) builderWithPrototype:(MChatViewList*) prototype {
  return [[MChatViewList builder] mergeFrom:prototype];
}
- (MChatViewList_Builder*) builder {
  return [MChatViewList builder];
}
@end

@interface MChatViewList_Builder()
@property (retain) MChatViewList* protobufBuilderResult;
@end

@implementation MChatViewList_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MChatViewList alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MChatViewList_Builder*) clear {
  self.protobufBuilderResult = [[[MChatViewList alloc] init] autorelease];
  return self;
}
- (MChatViewList_Builder*) clone {
  return [MChatViewList builderWithPrototype:protobufBuilderResult];
}
- (MChatViewList*) defaultInstance {
  return [MChatViewList defaultInstance];
}
- (MChatViewList*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MChatViewList*) buildPartial {
  MChatViewList* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MChatViewList_Builder*) mergeFrom:(MChatViewList*) other {
  if (other == [MChatViewList defaultInstance]) {
    return self;
  }
  if (other.mutableViewsList.count > 0) {
    if (protobufBuilderResult.mutableViewsList == nil) {
      protobufBuilderResult.mutableViewsList = [NSMutableArray array];
    }
    [protobufBuilderResult.mutableViewsList addObjectsFromArray:other.mutableViewsList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MChatViewList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MChatViewList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        MChatView_Builder* subBuilder = [MChatView builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addViews:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSArray*) viewsList {
  if (protobufBuilderResult.mutableViewsList == nil) { return [NSArray array]; }
  return protobufBuilderResult.mutableViewsList;
}
- (MChatView*) viewsAtIndex:(int32_t) index {
  return [protobufBuilderResult viewsAtIndex:index];
}
- (MChatViewList_Builder*) replaceViewsAtIndex:(int32_t) index with:(MChatView*) _value {
  [protobufBuilderResult.mutableViewsList replaceObjectAtIndex:index withObject:_value];
  return self;
}
- (MChatViewList_Builder*) addAllViews:(NSArray*) values {
  if (protobufBuilderResult.mutableViewsList == nil) {
    protobufBuilderResult.mutableViewsList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableViewsList addObjectsFromArray:values];
  return self;
}
- (MChatViewList_Builder*) clearViewsList {
  protobufBuilderResult.mutableViewsList = nil;
  return self;
}
- (MChatViewList_Builder*) addViews:(MChatView*) _value {
  if (protobufBuilderResult.mutableViewsList == nil) {
    protobufBuilderResult.mutableViewsList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableViewsList addObject:_value];
  return self;
}
@end

@interface MNotify ()
@property (retain) NSString* id;
@property int32_t type;
@property (retain) NSString* img;
@property (retain) NSString* content;
@property (retain) NSString* createTime;
@end

@implementation MNotify

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value {
  hasId_ = !!_value;
}
@synthesize id;
- (BOOL) hasType {
  return !!hasType_;
}
- (void) setHasType:(BOOL) _value {
  hasType_ = !!_value;
}
@synthesize type;
- (BOOL) hasImg {
  return !!hasImg_;
}
- (void) setHasImg:(BOOL) _value {
  hasImg_ = !!_value;
}
@synthesize img;
- (BOOL) hasContent {
  return !!hasContent_;
}
- (void) setHasContent:(BOOL) _value {
  hasContent_ = !!_value;
}
@synthesize content;
- (BOOL) hasCreateTime {
  return !!hasCreateTime_;
}
- (void) setHasCreateTime:(BOOL) _value {
  hasCreateTime_ = !!_value;
}
@synthesize createTime;
- (void) dealloc {
  self.id = nil;
  self.img = nil;
  self.content = nil;
  self.createTime = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = @"";
    self.type = 0;
    self.img = @"";
    self.content = @"";
    self.createTime = @"";
  }
  return self;
}
static MNotify* defaultMNotifyInstance = nil;
+ (void) initialize {
  if (self == [MNotify class]) {
    defaultMNotifyInstance = [[MNotify alloc] init];
  }
}
+ (MNotify*) defaultInstance {
  return defaultMNotifyInstance;
}
- (MNotify*) defaultInstance {
  return defaultMNotifyInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeString:1 value:self.id];
  }
  if (self.hasType) {
    [output writeInt32:2 value:self.type];
  }
  if (self.hasImg) {
    [output writeString:3 value:self.img];
  }
  if (self.hasContent) {
    [output writeString:4 value:self.content];
  }
  if (self.hasCreateTime) {
    [output writeString:6 value:self.createTime];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasId) {
    size += computeStringSize(1, self.id);
  }
  if (self.hasType) {
    size += computeInt32Size(2, self.type);
  }
  if (self.hasImg) {
    size += computeStringSize(3, self.img);
  }
  if (self.hasContent) {
    size += computeStringSize(4, self.content);
  }
  if (self.hasCreateTime) {
    size += computeStringSize(6, self.createTime);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MNotify*) parseFromData:(NSData*) data {
  return (MNotify*)[[[MNotify builder] mergeFromData:data] build];
}
+ (MNotify*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MNotify*)[[[MNotify builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MNotify*) parseFromInputStream:(NSInputStream*) input {
  return (MNotify*)[[[MNotify builder] mergeFromInputStream:input] build];
}
+ (MNotify*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MNotify*)[[[MNotify builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MNotify*)[[[MNotify builder] mergeFromCodedInputStream:input] build];
}
+ (MNotify*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MNotify*)[[[MNotify builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MNotify_Builder*) builder {
  return [[[MNotify_Builder alloc] init] autorelease];
}
+ (MNotify_Builder*) builderWithPrototype:(MNotify*) prototype {
  return [[MNotify builder] mergeFrom:prototype];
}
- (MNotify_Builder*) builder {
  return [MNotify builder];
}
@end

@interface MNotify_Builder()
@property (retain) MNotify* protobufBuilderResult;
@end

@implementation MNotify_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MNotify alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MNotify_Builder*) clear {
  self.protobufBuilderResult = [[[MNotify alloc] init] autorelease];
  return self;
}
- (MNotify_Builder*) clone {
  return [MNotify builderWithPrototype:protobufBuilderResult];
}
- (MNotify*) defaultInstance {
  return [MNotify defaultInstance];
}
- (MNotify*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MNotify*) buildPartial {
  MNotify* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MNotify_Builder*) mergeFrom:(MNotify*) other {
  if (other == [MNotify defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasType) {
    [self setType:other.type];
  }
  if (other.hasImg) {
    [self setImg:other.img];
  }
  if (other.hasContent) {
    [self setContent:other.content];
  }
  if (other.hasCreateTime) {
    [self setCreateTime:other.createTime];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MNotify_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MNotify_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setId:[input readString]];
        break;
      }
      case 16: {
        [self setType:[input readInt32]];
        break;
      }
      case 26: {
        [self setImg:[input readString]];
        break;
      }
      case 34: {
        [self setContent:[input readString]];
        break;
      }
      case 50: {
        [self setCreateTime:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return protobufBuilderResult.hasId;
}
- (NSString*) id {
  return protobufBuilderResult.id;
}
- (MNotify_Builder*) setId:(NSString*) _value {
  protobufBuilderResult.hasId = YES;
  protobufBuilderResult.id = _value;
  return self;
}
- (MNotify_Builder*) clearId {
  protobufBuilderResult.hasId = NO;
  protobufBuilderResult.id = @"";
  return self;
}
- (BOOL) hasType {
  return protobufBuilderResult.hasType;
}
- (int32_t) type {
  return protobufBuilderResult.type;
}
- (MNotify_Builder*) setType:(int32_t) _value {
  protobufBuilderResult.hasType = YES;
  protobufBuilderResult.type = _value;
  return self;
}
- (MNotify_Builder*) clearType {
  protobufBuilderResult.hasType = NO;
  protobufBuilderResult.type = 0;
  return self;
}
- (BOOL) hasImg {
  return protobufBuilderResult.hasImg;
}
- (NSString*) img {
  return protobufBuilderResult.img;
}
- (MNotify_Builder*) setImg:(NSString*) _value {
  protobufBuilderResult.hasImg = YES;
  protobufBuilderResult.img = _value;
  return self;
}
- (MNotify_Builder*) clearImg {
  protobufBuilderResult.hasImg = NO;
  protobufBuilderResult.img = @"";
  return self;
}
- (BOOL) hasContent {
  return protobufBuilderResult.hasContent;
}
- (NSString*) content {
  return protobufBuilderResult.content;
}
- (MNotify_Builder*) setContent:(NSString*) _value {
  protobufBuilderResult.hasContent = YES;
  protobufBuilderResult.content = _value;
  return self;
}
- (MNotify_Builder*) clearContent {
  protobufBuilderResult.hasContent = NO;
  protobufBuilderResult.content = @"";
  return self;
}
- (BOOL) hasCreateTime {
  return protobufBuilderResult.hasCreateTime;
}
- (NSString*) createTime {
  return protobufBuilderResult.createTime;
}
- (MNotify_Builder*) setCreateTime:(NSString*) _value {
  protobufBuilderResult.hasCreateTime = YES;
  protobufBuilderResult.createTime = _value;
  return self;
}
- (MNotify_Builder*) clearCreateTime {
  protobufBuilderResult.hasCreateTime = NO;
  protobufBuilderResult.createTime = @"";
  return self;
}
@end

@interface MNotifyList ()
@property (retain) MNotify* notify;
@end

@implementation MNotifyList

- (BOOL) hasNotify {
  return !!hasNotify_;
}
- (void) setHasNotify:(BOOL) _value {
  hasNotify_ = !!_value;
}
@synthesize notify;
- (void) dealloc {
  self.notify = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.notify = [MNotify defaultInstance];
  }
  return self;
}
static MNotifyList* defaultMNotifyListInstance = nil;
+ (void) initialize {
  if (self == [MNotifyList class]) {
    defaultMNotifyListInstance = [[MNotifyList alloc] init];
  }
}
+ (MNotifyList*) defaultInstance {
  return defaultMNotifyListInstance;
}
- (MNotifyList*) defaultInstance {
  return defaultMNotifyListInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasNotify) {
    [output writeMessage:1 value:self.notify];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasNotify) {
    size += computeMessageSize(1, self.notify);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MNotifyList*) parseFromData:(NSData*) data {
  return (MNotifyList*)[[[MNotifyList builder] mergeFromData:data] build];
}
+ (MNotifyList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MNotifyList*)[[[MNotifyList builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MNotifyList*) parseFromInputStream:(NSInputStream*) input {
  return (MNotifyList*)[[[MNotifyList builder] mergeFromInputStream:input] build];
}
+ (MNotifyList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MNotifyList*)[[[MNotifyList builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MNotifyList*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MNotifyList*)[[[MNotifyList builder] mergeFromCodedInputStream:input] build];
}
+ (MNotifyList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MNotifyList*)[[[MNotifyList builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MNotifyList_Builder*) builder {
  return [[[MNotifyList_Builder alloc] init] autorelease];
}
+ (MNotifyList_Builder*) builderWithPrototype:(MNotifyList*) prototype {
  return [[MNotifyList builder] mergeFrom:prototype];
}
- (MNotifyList_Builder*) builder {
  return [MNotifyList builder];
}
@end

@interface MNotifyList_Builder()
@property (retain) MNotifyList* protobufBuilderResult;
@end

@implementation MNotifyList_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MNotifyList alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MNotifyList_Builder*) clear {
  self.protobufBuilderResult = [[[MNotifyList alloc] init] autorelease];
  return self;
}
- (MNotifyList_Builder*) clone {
  return [MNotifyList builderWithPrototype:protobufBuilderResult];
}
- (MNotifyList*) defaultInstance {
  return [MNotifyList defaultInstance];
}
- (MNotifyList*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MNotifyList*) buildPartial {
  MNotifyList* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MNotifyList_Builder*) mergeFrom:(MNotifyList*) other {
  if (other == [MNotifyList defaultInstance]) {
    return self;
  }
  if (other.hasNotify) {
    [self mergeNotify:other.notify];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MNotifyList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MNotifyList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        MNotify_Builder* subBuilder = [MNotify builder];
        if (self.hasNotify) {
          [subBuilder mergeFrom:self.notify];
        }
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self setNotify:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (BOOL) hasNotify {
  return protobufBuilderResult.hasNotify;
}
- (MNotify*) notify {
  return protobufBuilderResult.notify;
}
- (MNotifyList_Builder*) setNotify:(MNotify*) _value {
  protobufBuilderResult.hasNotify = YES;
  protobufBuilderResult.notify = _value;
  return self;
}
- (MNotifyList_Builder*) setNotifyBuilder:(MNotify_Builder*) builderForValue {
  return [self setNotify:[builderForValue build]];
}
- (MNotifyList_Builder*) mergeNotify:(MNotify*) _value {
  if (protobufBuilderResult.hasNotify &&
      protobufBuilderResult.notify != [MNotify defaultInstance]) {
    protobufBuilderResult.notify =
      [[[MNotify builderWithPrototype:protobufBuilderResult.notify] mergeFrom:_value] buildPartial];
  } else {
    protobufBuilderResult.notify = _value;
  }
  protobufBuilderResult.hasNotify = YES;
  return self;
}
- (MNotifyList_Builder*) clearNotify {
  protobufBuilderResult.hasNotify = NO;
  protobufBuilderResult.notify = [MNotify defaultInstance];
  return self;
}
@end

