// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "UserTopic.pb.h"

@implementation UserTopicRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [UserTopicRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = [registry retain];
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface MTopic ()
@property (retain) NSString* id;
@property (retain) NSString* userid;
@property (retain) NSString* headImg;
@property (retain) NSString* content;
@property (retain) NSMutableArray* mutableImgsList;
@property (retain) NSString* location;
@property int32_t praiseCnt;
@property int32_t commentCnt;
@property (retain) NSString* time;
@property (retain) NSString* createTime;
@property (retain) NSMutableArray* mutableCommentsList;
@property (retain) NSMutableArray* mutablePraisesList;
@property int32_t hasPraise;
@end

@implementation MTopic

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value {
  hasId_ = !!_value;
}
@synthesize id;
- (BOOL) hasUserid {
  return !!hasUserid_;
}
- (void) setHasUserid:(BOOL) _value {
  hasUserid_ = !!_value;
}
@synthesize userid;
- (BOOL) hasHeadImg {
  return !!hasHeadImg_;
}
- (void) setHasHeadImg:(BOOL) _value {
  hasHeadImg_ = !!_value;
}
@synthesize headImg;
- (BOOL) hasContent {
  return !!hasContent_;
}
- (void) setHasContent:(BOOL) _value {
  hasContent_ = !!_value;
}
@synthesize content;
@synthesize mutableImgsList;
- (BOOL) hasLocation {
  return !!hasLocation_;
}
- (void) setHasLocation:(BOOL) _value {
  hasLocation_ = !!_value;
}
@synthesize location;
- (BOOL) hasPraiseCnt {
  return !!hasPraiseCnt_;
}
- (void) setHasPraiseCnt:(BOOL) _value {
  hasPraiseCnt_ = !!_value;
}
@synthesize praiseCnt;
- (BOOL) hasCommentCnt {
  return !!hasCommentCnt_;
}
- (void) setHasCommentCnt:(BOOL) _value {
  hasCommentCnt_ = !!_value;
}
@synthesize commentCnt;
- (BOOL) hasTime {
  return !!hasTime_;
}
- (void) setHasTime:(BOOL) _value {
  hasTime_ = !!_value;
}
@synthesize time;
- (BOOL) hasCreateTime {
  return !!hasCreateTime_;
}
- (void) setHasCreateTime:(BOOL) _value {
  hasCreateTime_ = !!_value;
}
@synthesize createTime;
@synthesize mutableCommentsList;
@synthesize mutablePraisesList;
- (BOOL) hasHasPraise {
  return !!hasHasPraise_;
}
- (void) setHasHasPraise:(BOOL) _value {
  hasHasPraise_ = !!_value;
}
@synthesize hasPraise;
- (void) dealloc {
  self.id = nil;
  self.userid = nil;
  self.headImg = nil;
  self.content = nil;
  self.mutableImgsList = nil;
  self.location = nil;
  self.time = nil;
  self.createTime = nil;
  self.mutableCommentsList = nil;
  self.mutablePraisesList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = @"";
    self.userid = @"";
    self.headImg = @"";
    self.content = @"";
    self.location = @"";
    self.praiseCnt = 0;
    self.commentCnt = 0;
    self.time = @"";
    self.createTime = @"";
    self.hasPraise = 0;
  }
  return self;
}
static MTopic* defaultMTopicInstance = nil;
+ (void) initialize {
  if (self == [MTopic class]) {
    defaultMTopicInstance = [[MTopic alloc] init];
  }
}
+ (MTopic*) defaultInstance {
  return defaultMTopicInstance;
}
- (MTopic*) defaultInstance {
  return defaultMTopicInstance;
}
- (NSArray*) imgsList {
  return mutableImgsList;
}
- (NSString*) imgsAtIndex:(int32_t) index {
  id _value = [mutableImgsList objectAtIndex:index];
  return _value;
}
- (NSArray*) commentsList {
  return mutableCommentsList;
}
- (MComment*) commentsAtIndex:(int32_t) index {
  id _value = [mutableCommentsList objectAtIndex:index];
  return _value;
}
- (NSArray*) praisesList {
  return mutablePraisesList;
}
- (MPraise*) praisesAtIndex:(int32_t) index {
  id _value = [mutablePraisesList objectAtIndex:index];
  return _value;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeString:1 value:self.id];
  }
  if (self.hasUserid) {
    [output writeString:2 value:self.userid];
  }
  if (self.hasHeadImg) {
    [output writeString:3 value:self.headImg];
  }
  if (self.hasContent) {
    [output writeString:4 value:self.content];
  }
  for (NSString* element in self.mutableImgsList) {
    [output writeString:5 value:element];
  }
  if (self.hasLocation) {
    [output writeString:6 value:self.location];
  }
  if (self.hasPraiseCnt) {
    [output writeInt32:7 value:self.praiseCnt];
  }
  if (self.hasCommentCnt) {
    [output writeInt32:8 value:self.commentCnt];
  }
  if (self.hasTime) {
    [output writeString:9 value:self.time];
  }
  if (self.hasCreateTime) {
    [output writeString:10 value:self.createTime];
  }
  for (MComment* element in self.commentsList) {
    [output writeMessage:11 value:element];
  }
  for (MPraise* element in self.praisesList) {
    [output writeMessage:12 value:element];
  }
  if (self.hasHasPraise) {
    [output writeInt32:13 value:self.hasPraise];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasId) {
    size += computeStringSize(1, self.id);
  }
  if (self.hasUserid) {
    size += computeStringSize(2, self.userid);
  }
  if (self.hasHeadImg) {
    size += computeStringSize(3, self.headImg);
  }
  if (self.hasContent) {
    size += computeStringSize(4, self.content);
  }
  {
    int32_t dataSize = 0;
    for (NSString* element in self.mutableImgsList) {
      dataSize += computeStringSizeNoTag(element);
    }
    size += dataSize;
    size += 1 * self.mutableImgsList.count;
  }
  if (self.hasLocation) {
    size += computeStringSize(6, self.location);
  }
  if (self.hasPraiseCnt) {
    size += computeInt32Size(7, self.praiseCnt);
  }
  if (self.hasCommentCnt) {
    size += computeInt32Size(8, self.commentCnt);
  }
  if (self.hasTime) {
    size += computeStringSize(9, self.time);
  }
  if (self.hasCreateTime) {
    size += computeStringSize(10, self.createTime);
  }
  for (MComment* element in self.commentsList) {
    size += computeMessageSize(11, element);
  }
  for (MPraise* element in self.praisesList) {
    size += computeMessageSize(12, element);
  }
  if (self.hasHasPraise) {
    size += computeInt32Size(13, self.hasPraise);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MTopic*) parseFromData:(NSData*) data {
  return (MTopic*)[[[MTopic builder] mergeFromData:data] build];
}
+ (MTopic*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MTopic*)[[[MTopic builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MTopic*) parseFromInputStream:(NSInputStream*) input {
  return (MTopic*)[[[MTopic builder] mergeFromInputStream:input] build];
}
+ (MTopic*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MTopic*)[[[MTopic builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MTopic*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MTopic*)[[[MTopic builder] mergeFromCodedInputStream:input] build];
}
+ (MTopic*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MTopic*)[[[MTopic builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MTopic_Builder*) builder {
  return [[[MTopic_Builder alloc] init] autorelease];
}
+ (MTopic_Builder*) builderWithPrototype:(MTopic*) prototype {
  return [[MTopic builder] mergeFrom:prototype];
}
- (MTopic_Builder*) builder {
  return [MTopic builder];
}
@end

@interface MTopic_Builder()
@property (retain) MTopic* protobufBuilderResult;
@end

@implementation MTopic_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MTopic alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MTopic_Builder*) clear {
  self.protobufBuilderResult = [[[MTopic alloc] init] autorelease];
  return self;
}
- (MTopic_Builder*) clone {
  return [MTopic builderWithPrototype:protobufBuilderResult];
}
- (MTopic*) defaultInstance {
  return [MTopic defaultInstance];
}
- (MTopic*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MTopic*) buildPartial {
  MTopic* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MTopic_Builder*) mergeFrom:(MTopic*) other {
  if (other == [MTopic defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasUserid) {
    [self setUserid:other.userid];
  }
  if (other.hasHeadImg) {
    [self setHeadImg:other.headImg];
  }
  if (other.hasContent) {
    [self setContent:other.content];
  }
  if (other.mutableImgsList.count > 0) {
    if (protobufBuilderResult.mutableImgsList == nil) {
      protobufBuilderResult.mutableImgsList = [NSMutableArray array];
    }
    [protobufBuilderResult.mutableImgsList addObjectsFromArray:other.mutableImgsList];
  }
  if (other.hasLocation) {
    [self setLocation:other.location];
  }
  if (other.hasPraiseCnt) {
    [self setPraiseCnt:other.praiseCnt];
  }
  if (other.hasCommentCnt) {
    [self setCommentCnt:other.commentCnt];
  }
  if (other.hasTime) {
    [self setTime:other.time];
  }
  if (other.hasCreateTime) {
    [self setCreateTime:other.createTime];
  }
  if (other.mutableCommentsList.count > 0) {
    if (protobufBuilderResult.mutableCommentsList == nil) {
      protobufBuilderResult.mutableCommentsList = [NSMutableArray array];
    }
    [protobufBuilderResult.mutableCommentsList addObjectsFromArray:other.mutableCommentsList];
  }
  if (other.mutablePraisesList.count > 0) {
    if (protobufBuilderResult.mutablePraisesList == nil) {
      protobufBuilderResult.mutablePraisesList = [NSMutableArray array];
    }
    [protobufBuilderResult.mutablePraisesList addObjectsFromArray:other.mutablePraisesList];
  }
  if (other.hasHasPraise) {
    [self setHasPraise:other.hasPraise];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MTopic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MTopic_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setId:[input readString]];
        break;
      }
      case 18: {
        [self setUserid:[input readString]];
        break;
      }
      case 26: {
        [self setHeadImg:[input readString]];
        break;
      }
      case 34: {
        [self setContent:[input readString]];
        break;
      }
      case 42: {
        [self addImgs:[input readString]];
        break;
      }
      case 50: {
        [self setLocation:[input readString]];
        break;
      }
      case 56: {
        [self setPraiseCnt:[input readInt32]];
        break;
      }
      case 64: {
        [self setCommentCnt:[input readInt32]];
        break;
      }
      case 74: {
        [self setTime:[input readString]];
        break;
      }
      case 82: {
        [self setCreateTime:[input readString]];
        break;
      }
      case 90: {
        MComment_Builder* subBuilder = [MComment builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addComments:[subBuilder buildPartial]];
        break;
      }
      case 98: {
        MPraise_Builder* subBuilder = [MPraise builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addPraises:[subBuilder buildPartial]];
        break;
      }
      case 104: {
        [self setHasPraise:[input readInt32]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return protobufBuilderResult.hasId;
}
- (NSString*) id {
  return protobufBuilderResult.id;
}
- (MTopic_Builder*) setId:(NSString*) _value {
  protobufBuilderResult.hasId = YES;
  protobufBuilderResult.id = _value;
  return self;
}
- (MTopic_Builder*) clearId {
  protobufBuilderResult.hasId = NO;
  protobufBuilderResult.id = @"";
  return self;
}
- (BOOL) hasUserid {
  return protobufBuilderResult.hasUserid;
}
- (NSString*) userid {
  return protobufBuilderResult.userid;
}
- (MTopic_Builder*) setUserid:(NSString*) _value {
  protobufBuilderResult.hasUserid = YES;
  protobufBuilderResult.userid = _value;
  return self;
}
- (MTopic_Builder*) clearUserid {
  protobufBuilderResult.hasUserid = NO;
  protobufBuilderResult.userid = @"";
  return self;
}
- (BOOL) hasHeadImg {
  return protobufBuilderResult.hasHeadImg;
}
- (NSString*) headImg {
  return protobufBuilderResult.headImg;
}
- (MTopic_Builder*) setHeadImg:(NSString*) _value {
  protobufBuilderResult.hasHeadImg = YES;
  protobufBuilderResult.headImg = _value;
  return self;
}
- (MTopic_Builder*) clearHeadImg {
  protobufBuilderResult.hasHeadImg = NO;
  protobufBuilderResult.headImg = @"";
  return self;
}
- (BOOL) hasContent {
  return protobufBuilderResult.hasContent;
}
- (NSString*) content {
  return protobufBuilderResult.content;
}
- (MTopic_Builder*) setContent:(NSString*) _value {
  protobufBuilderResult.hasContent = YES;
  protobufBuilderResult.content = _value;
  return self;
}
- (MTopic_Builder*) clearContent {
  protobufBuilderResult.hasContent = NO;
  protobufBuilderResult.content = @"";
  return self;
}
- (NSArray*) imgsList {
  if (protobufBuilderResult.mutableImgsList == nil) {
    return [NSArray array];
  }
  return protobufBuilderResult.mutableImgsList;
}
- (NSString*) imgsAtIndex:(int32_t) index {
  return [protobufBuilderResult imgsAtIndex:index];
}
- (MTopic_Builder*) replaceImgsAtIndex:(int32_t) index with:(NSString*) _value {
  [protobufBuilderResult.mutableImgsList replaceObjectAtIndex:index withObject:_value];
  return self;
}
- (MTopic_Builder*) addImgs:(NSString*) _value {
  if (protobufBuilderResult.mutableImgsList == nil) {
    protobufBuilderResult.mutableImgsList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableImgsList addObject:_value];
  return self;
}
- (MTopic_Builder*) addAllImgs:(NSArray*) values {
  if (protobufBuilderResult.mutableImgsList == nil) {
    protobufBuilderResult.mutableImgsList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableImgsList addObjectsFromArray:values];
  return self;
}
- (MTopic_Builder*) clearImgsList {
  protobufBuilderResult.mutableImgsList = nil;
  return self;
}
- (BOOL) hasLocation {
  return protobufBuilderResult.hasLocation;
}
- (NSString*) location {
  return protobufBuilderResult.location;
}
- (MTopic_Builder*) setLocation:(NSString*) _value {
  protobufBuilderResult.hasLocation = YES;
  protobufBuilderResult.location = _value;
  return self;
}
- (MTopic_Builder*) clearLocation {
  protobufBuilderResult.hasLocation = NO;
  protobufBuilderResult.location = @"";
  return self;
}
- (BOOL) hasPraiseCnt {
  return protobufBuilderResult.hasPraiseCnt;
}
- (int32_t) praiseCnt {
  return protobufBuilderResult.praiseCnt;
}
- (MTopic_Builder*) setPraiseCnt:(int32_t) _value {
  protobufBuilderResult.hasPraiseCnt = YES;
  protobufBuilderResult.praiseCnt = _value;
  return self;
}
- (MTopic_Builder*) clearPraiseCnt {
  protobufBuilderResult.hasPraiseCnt = NO;
  protobufBuilderResult.praiseCnt = 0;
  return self;
}
- (BOOL) hasCommentCnt {
  return protobufBuilderResult.hasCommentCnt;
}
- (int32_t) commentCnt {
  return protobufBuilderResult.commentCnt;
}
- (MTopic_Builder*) setCommentCnt:(int32_t) _value {
  protobufBuilderResult.hasCommentCnt = YES;
  protobufBuilderResult.commentCnt = _value;
  return self;
}
- (MTopic_Builder*) clearCommentCnt {
  protobufBuilderResult.hasCommentCnt = NO;
  protobufBuilderResult.commentCnt = 0;
  return self;
}
- (BOOL) hasTime {
  return protobufBuilderResult.hasTime;
}
- (NSString*) time {
  return protobufBuilderResult.time;
}
- (MTopic_Builder*) setTime:(NSString*) _value {
  protobufBuilderResult.hasTime = YES;
  protobufBuilderResult.time = _value;
  return self;
}
- (MTopic_Builder*) clearTime {
  protobufBuilderResult.hasTime = NO;
  protobufBuilderResult.time = @"";
  return self;
}
- (BOOL) hasCreateTime {
  return protobufBuilderResult.hasCreateTime;
}
- (NSString*) createTime {
  return protobufBuilderResult.createTime;
}
- (MTopic_Builder*) setCreateTime:(NSString*) _value {
  protobufBuilderResult.hasCreateTime = YES;
  protobufBuilderResult.createTime = _value;
  return self;
}
- (MTopic_Builder*) clearCreateTime {
  protobufBuilderResult.hasCreateTime = NO;
  protobufBuilderResult.createTime = @"";
  return self;
}
- (NSArray*) commentsList {
  if (protobufBuilderResult.mutableCommentsList == nil) { return [NSArray array]; }
  return protobufBuilderResult.mutableCommentsList;
}
- (MComment*) commentsAtIndex:(int32_t) index {
  return [protobufBuilderResult commentsAtIndex:index];
}
- (MTopic_Builder*) replaceCommentsAtIndex:(int32_t) index with:(MComment*) _value {
  [protobufBuilderResult.mutableCommentsList replaceObjectAtIndex:index withObject:_value];
  return self;
}
- (MTopic_Builder*) addAllComments:(NSArray*) values {
  if (protobufBuilderResult.mutableCommentsList == nil) {
    protobufBuilderResult.mutableCommentsList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableCommentsList addObjectsFromArray:values];
  return self;
}
- (MTopic_Builder*) clearCommentsList {
  protobufBuilderResult.mutableCommentsList = nil;
  return self;
}
- (MTopic_Builder*) addComments:(MComment*) _value {
  if (protobufBuilderResult.mutableCommentsList == nil) {
    protobufBuilderResult.mutableCommentsList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableCommentsList addObject:_value];
  return self;
}
- (NSArray*) praisesList {
  if (protobufBuilderResult.mutablePraisesList == nil) { return [NSArray array]; }
  return protobufBuilderResult.mutablePraisesList;
}
- (MPraise*) praisesAtIndex:(int32_t) index {
  return [protobufBuilderResult praisesAtIndex:index];
}
- (MTopic_Builder*) replacePraisesAtIndex:(int32_t) index with:(MPraise*) _value {
  [protobufBuilderResult.mutablePraisesList replaceObjectAtIndex:index withObject:_value];
  return self;
}
- (MTopic_Builder*) addAllPraises:(NSArray*) values {
  if (protobufBuilderResult.mutablePraisesList == nil) {
    protobufBuilderResult.mutablePraisesList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutablePraisesList addObjectsFromArray:values];
  return self;
}
- (MTopic_Builder*) clearPraisesList {
  protobufBuilderResult.mutablePraisesList = nil;
  return self;
}
- (MTopic_Builder*) addPraises:(MPraise*) _value {
  if (protobufBuilderResult.mutablePraisesList == nil) {
    protobufBuilderResult.mutablePraisesList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutablePraisesList addObject:_value];
  return self;
}
- (BOOL) hasHasPraise {
  return protobufBuilderResult.hasHasPraise;
}
- (int32_t) hasPraise {
  return protobufBuilderResult.hasPraise;
}
- (MTopic_Builder*) setHasPraise:(int32_t) _value {
  protobufBuilderResult.hasHasPraise = YES;
  protobufBuilderResult.hasPraise = _value;
  return self;
}
- (MTopic_Builder*) clearHasPraise {
  protobufBuilderResult.hasHasPraise = NO;
  protobufBuilderResult.hasPraise = 0;
  return self;
}
@end

@interface MTopicList ()
@property (retain) NSMutableArray* mutableListList;
@end

@implementation MTopicList

@synthesize mutableListList;
- (void) dealloc {
  self.mutableListList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static MTopicList* defaultMTopicListInstance = nil;
+ (void) initialize {
  if (self == [MTopicList class]) {
    defaultMTopicListInstance = [[MTopicList alloc] init];
  }
}
+ (MTopicList*) defaultInstance {
  return defaultMTopicListInstance;
}
- (MTopicList*) defaultInstance {
  return defaultMTopicListInstance;
}
- (NSArray*) listList {
  return mutableListList;
}
- (MTopic*) listAtIndex:(int32_t) index {
  id _value = [mutableListList objectAtIndex:index];
  return _value;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (MTopic* element in self.listList) {
    [output writeMessage:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  for (MTopic* element in self.listList) {
    size += computeMessageSize(1, element);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MTopicList*) parseFromData:(NSData*) data {
  return (MTopicList*)[[[MTopicList builder] mergeFromData:data] build];
}
+ (MTopicList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MTopicList*)[[[MTopicList builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MTopicList*) parseFromInputStream:(NSInputStream*) input {
  return (MTopicList*)[[[MTopicList builder] mergeFromInputStream:input] build];
}
+ (MTopicList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MTopicList*)[[[MTopicList builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MTopicList*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MTopicList*)[[[MTopicList builder] mergeFromCodedInputStream:input] build];
}
+ (MTopicList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MTopicList*)[[[MTopicList builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MTopicList_Builder*) builder {
  return [[[MTopicList_Builder alloc] init] autorelease];
}
+ (MTopicList_Builder*) builderWithPrototype:(MTopicList*) prototype {
  return [[MTopicList builder] mergeFrom:prototype];
}
- (MTopicList_Builder*) builder {
  return [MTopicList builder];
}
@end

@interface MTopicList_Builder()
@property (retain) MTopicList* protobufBuilderResult;
@end

@implementation MTopicList_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MTopicList alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MTopicList_Builder*) clear {
  self.protobufBuilderResult = [[[MTopicList alloc] init] autorelease];
  return self;
}
- (MTopicList_Builder*) clone {
  return [MTopicList builderWithPrototype:protobufBuilderResult];
}
- (MTopicList*) defaultInstance {
  return [MTopicList defaultInstance];
}
- (MTopicList*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MTopicList*) buildPartial {
  MTopicList* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MTopicList_Builder*) mergeFrom:(MTopicList*) other {
  if (other == [MTopicList defaultInstance]) {
    return self;
  }
  if (other.mutableListList.count > 0) {
    if (protobufBuilderResult.mutableListList == nil) {
      protobufBuilderResult.mutableListList = [NSMutableArray array];
    }
    [protobufBuilderResult.mutableListList addObjectsFromArray:other.mutableListList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MTopicList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MTopicList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        MTopic_Builder* subBuilder = [MTopic builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addList:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSArray*) listList {
  if (protobufBuilderResult.mutableListList == nil) { return [NSArray array]; }
  return protobufBuilderResult.mutableListList;
}
- (MTopic*) listAtIndex:(int32_t) index {
  return [protobufBuilderResult listAtIndex:index];
}
- (MTopicList_Builder*) replaceListAtIndex:(int32_t) index with:(MTopic*) _value {
  [protobufBuilderResult.mutableListList replaceObjectAtIndex:index withObject:_value];
  return self;
}
- (MTopicList_Builder*) addAllList:(NSArray*) values {
  if (protobufBuilderResult.mutableListList == nil) {
    protobufBuilderResult.mutableListList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableListList addObjectsFromArray:values];
  return self;
}
- (MTopicList_Builder*) clearListList {
  protobufBuilderResult.mutableListList = nil;
  return self;
}
- (MTopicList_Builder*) addList:(MTopic*) _value {
  if (protobufBuilderResult.mutableListList == nil) {
    protobufBuilderResult.mutableListList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableListList addObject:_value];
  return self;
}
@end

@interface MPraise ()
@property (retain) NSString* id;
@property (retain) NSString* userid;
@property (retain) NSString* headImg;
@end

@implementation MPraise

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value {
  hasId_ = !!_value;
}
@synthesize id;
- (BOOL) hasUserid {
  return !!hasUserid_;
}
- (void) setHasUserid:(BOOL) _value {
  hasUserid_ = !!_value;
}
@synthesize userid;
- (BOOL) hasHeadImg {
  return !!hasHeadImg_;
}
- (void) setHasHeadImg:(BOOL) _value {
  hasHeadImg_ = !!_value;
}
@synthesize headImg;
- (void) dealloc {
  self.id = nil;
  self.userid = nil;
  self.headImg = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = @"";
    self.userid = @"";
    self.headImg = @"";
  }
  return self;
}
static MPraise* defaultMPraiseInstance = nil;
+ (void) initialize {
  if (self == [MPraise class]) {
    defaultMPraiseInstance = [[MPraise alloc] init];
  }
}
+ (MPraise*) defaultInstance {
  return defaultMPraiseInstance;
}
- (MPraise*) defaultInstance {
  return defaultMPraiseInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeString:1 value:self.id];
  }
  if (self.hasUserid) {
    [output writeString:2 value:self.userid];
  }
  if (self.hasHeadImg) {
    [output writeString:3 value:self.headImg];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasId) {
    size += computeStringSize(1, self.id);
  }
  if (self.hasUserid) {
    size += computeStringSize(2, self.userid);
  }
  if (self.hasHeadImg) {
    size += computeStringSize(3, self.headImg);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MPraise*) parseFromData:(NSData*) data {
  return (MPraise*)[[[MPraise builder] mergeFromData:data] build];
}
+ (MPraise*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MPraise*)[[[MPraise builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MPraise*) parseFromInputStream:(NSInputStream*) input {
  return (MPraise*)[[[MPraise builder] mergeFromInputStream:input] build];
}
+ (MPraise*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MPraise*)[[[MPraise builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MPraise*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MPraise*)[[[MPraise builder] mergeFromCodedInputStream:input] build];
}
+ (MPraise*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MPraise*)[[[MPraise builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MPraise_Builder*) builder {
  return [[[MPraise_Builder alloc] init] autorelease];
}
+ (MPraise_Builder*) builderWithPrototype:(MPraise*) prototype {
  return [[MPraise builder] mergeFrom:prototype];
}
- (MPraise_Builder*) builder {
  return [MPraise builder];
}
@end

@interface MPraise_Builder()
@property (retain) MPraise* protobufBuilderResult;
@end

@implementation MPraise_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MPraise alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MPraise_Builder*) clear {
  self.protobufBuilderResult = [[[MPraise alloc] init] autorelease];
  return self;
}
- (MPraise_Builder*) clone {
  return [MPraise builderWithPrototype:protobufBuilderResult];
}
- (MPraise*) defaultInstance {
  return [MPraise defaultInstance];
}
- (MPraise*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MPraise*) buildPartial {
  MPraise* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MPraise_Builder*) mergeFrom:(MPraise*) other {
  if (other == [MPraise defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasUserid) {
    [self setUserid:other.userid];
  }
  if (other.hasHeadImg) {
    [self setHeadImg:other.headImg];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MPraise_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MPraise_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setId:[input readString]];
        break;
      }
      case 18: {
        [self setUserid:[input readString]];
        break;
      }
      case 26: {
        [self setHeadImg:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return protobufBuilderResult.hasId;
}
- (NSString*) id {
  return protobufBuilderResult.id;
}
- (MPraise_Builder*) setId:(NSString*) _value {
  protobufBuilderResult.hasId = YES;
  protobufBuilderResult.id = _value;
  return self;
}
- (MPraise_Builder*) clearId {
  protobufBuilderResult.hasId = NO;
  protobufBuilderResult.id = @"";
  return self;
}
- (BOOL) hasUserid {
  return protobufBuilderResult.hasUserid;
}
- (NSString*) userid {
  return protobufBuilderResult.userid;
}
- (MPraise_Builder*) setUserid:(NSString*) _value {
  protobufBuilderResult.hasUserid = YES;
  protobufBuilderResult.userid = _value;
  return self;
}
- (MPraise_Builder*) clearUserid {
  protobufBuilderResult.hasUserid = NO;
  protobufBuilderResult.userid = @"";
  return self;
}
- (BOOL) hasHeadImg {
  return protobufBuilderResult.hasHeadImg;
}
- (NSString*) headImg {
  return protobufBuilderResult.headImg;
}
- (MPraise_Builder*) setHeadImg:(NSString*) _value {
  protobufBuilderResult.hasHeadImg = YES;
  protobufBuilderResult.headImg = _value;
  return self;
}
- (MPraise_Builder*) clearHeadImg {
  protobufBuilderResult.hasHeadImg = NO;
  protobufBuilderResult.headImg = @"";
  return self;
}
@end

@interface MComment ()
@property (retain) NSString* id;
@property (retain) NSString* userid;
@property (retain) NSString* headImg;
@property (retain) NSString* nickname;
@property (retain) NSString* targetId;
@property (retain) NSString* targetNickname;
@property (retain) NSString* content;
@property (retain) NSString* time;
@property (retain) NSString* createTime;
@end

@implementation MComment

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value {
  hasId_ = !!_value;
}
@synthesize id;
- (BOOL) hasUserid {
  return !!hasUserid_;
}
- (void) setHasUserid:(BOOL) _value {
  hasUserid_ = !!_value;
}
@synthesize userid;
- (BOOL) hasHeadImg {
  return !!hasHeadImg_;
}
- (void) setHasHeadImg:(BOOL) _value {
  hasHeadImg_ = !!_value;
}
@synthesize headImg;
- (BOOL) hasNickname {
  return !!hasNickname_;
}
- (void) setHasNickname:(BOOL) _value {
  hasNickname_ = !!_value;
}
@synthesize nickname;
- (BOOL) hasTargetId {
  return !!hasTargetId_;
}
- (void) setHasTargetId:(BOOL) _value {
  hasTargetId_ = !!_value;
}
@synthesize targetId;
- (BOOL) hasTargetNickname {
  return !!hasTargetNickname_;
}
- (void) setHasTargetNickname:(BOOL) _value {
  hasTargetNickname_ = !!_value;
}
@synthesize targetNickname;
- (BOOL) hasContent {
  return !!hasContent_;
}
- (void) setHasContent:(BOOL) _value {
  hasContent_ = !!_value;
}
@synthesize content;
- (BOOL) hasTime {
  return !!hasTime_;
}
- (void) setHasTime:(BOOL) _value {
  hasTime_ = !!_value;
}
@synthesize time;
- (BOOL) hasCreateTime {
  return !!hasCreateTime_;
}
- (void) setHasCreateTime:(BOOL) _value {
  hasCreateTime_ = !!_value;
}
@synthesize createTime;
- (void) dealloc {
  self.id = nil;
  self.userid = nil;
  self.headImg = nil;
  self.nickname = nil;
  self.targetId = nil;
  self.targetNickname = nil;
  self.content = nil;
  self.time = nil;
  self.createTime = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.id = @"";
    self.userid = @"";
    self.headImg = @"";
    self.nickname = @"";
    self.targetId = @"";
    self.targetNickname = @"";
    self.content = @"";
    self.time = @"";
    self.createTime = @"";
  }
  return self;
}
static MComment* defaultMCommentInstance = nil;
+ (void) initialize {
  if (self == [MComment class]) {
    defaultMCommentInstance = [[MComment alloc] init];
  }
}
+ (MComment*) defaultInstance {
  return defaultMCommentInstance;
}
- (MComment*) defaultInstance {
  return defaultMCommentInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeString:1 value:self.id];
  }
  if (self.hasUserid) {
    [output writeString:2 value:self.userid];
  }
  if (self.hasHeadImg) {
    [output writeString:3 value:self.headImg];
  }
  if (self.hasNickname) {
    [output writeString:4 value:self.nickname];
  }
  if (self.hasTargetId) {
    [output writeString:5 value:self.targetId];
  }
  if (self.hasTargetNickname) {
    [output writeString:6 value:self.targetNickname];
  }
  if (self.hasContent) {
    [output writeString:7 value:self.content];
  }
  if (self.hasTime) {
    [output writeString:8 value:self.time];
  }
  if (self.hasCreateTime) {
    [output writeString:9 value:self.createTime];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  if (self.hasId) {
    size += computeStringSize(1, self.id);
  }
  if (self.hasUserid) {
    size += computeStringSize(2, self.userid);
  }
  if (self.hasHeadImg) {
    size += computeStringSize(3, self.headImg);
  }
  if (self.hasNickname) {
    size += computeStringSize(4, self.nickname);
  }
  if (self.hasTargetId) {
    size += computeStringSize(5, self.targetId);
  }
  if (self.hasTargetNickname) {
    size += computeStringSize(6, self.targetNickname);
  }
  if (self.hasContent) {
    size += computeStringSize(7, self.content);
  }
  if (self.hasTime) {
    size += computeStringSize(8, self.time);
  }
  if (self.hasCreateTime) {
    size += computeStringSize(9, self.createTime);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MComment*) parseFromData:(NSData*) data {
  return (MComment*)[[[MComment builder] mergeFromData:data] build];
}
+ (MComment*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MComment*)[[[MComment builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MComment*) parseFromInputStream:(NSInputStream*) input {
  return (MComment*)[[[MComment builder] mergeFromInputStream:input] build];
}
+ (MComment*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MComment*)[[[MComment builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MComment*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MComment*)[[[MComment builder] mergeFromCodedInputStream:input] build];
}
+ (MComment*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MComment*)[[[MComment builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MComment_Builder*) builder {
  return [[[MComment_Builder alloc] init] autorelease];
}
+ (MComment_Builder*) builderWithPrototype:(MComment*) prototype {
  return [[MComment builder] mergeFrom:prototype];
}
- (MComment_Builder*) builder {
  return [MComment builder];
}
@end

@interface MComment_Builder()
@property (retain) MComment* protobufBuilderResult;
@end

@implementation MComment_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MComment alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MComment_Builder*) clear {
  self.protobufBuilderResult = [[[MComment alloc] init] autorelease];
  return self;
}
- (MComment_Builder*) clone {
  return [MComment builderWithPrototype:protobufBuilderResult];
}
- (MComment*) defaultInstance {
  return [MComment defaultInstance];
}
- (MComment*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MComment*) buildPartial {
  MComment* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MComment_Builder*) mergeFrom:(MComment*) other {
  if (other == [MComment defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasUserid) {
    [self setUserid:other.userid];
  }
  if (other.hasHeadImg) {
    [self setHeadImg:other.headImg];
  }
  if (other.hasNickname) {
    [self setNickname:other.nickname];
  }
  if (other.hasTargetId) {
    [self setTargetId:other.targetId];
  }
  if (other.hasTargetNickname) {
    [self setTargetNickname:other.targetNickname];
  }
  if (other.hasContent) {
    [self setContent:other.content];
  }
  if (other.hasTime) {
    [self setTime:other.time];
  }
  if (other.hasCreateTime) {
    [self setCreateTime:other.createTime];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MComment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MComment_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setId:[input readString]];
        break;
      }
      case 18: {
        [self setUserid:[input readString]];
        break;
      }
      case 26: {
        [self setHeadImg:[input readString]];
        break;
      }
      case 34: {
        [self setNickname:[input readString]];
        break;
      }
      case 42: {
        [self setTargetId:[input readString]];
        break;
      }
      case 50: {
        [self setTargetNickname:[input readString]];
        break;
      }
      case 58: {
        [self setContent:[input readString]];
        break;
      }
      case 66: {
        [self setTime:[input readString]];
        break;
      }
      case 74: {
        [self setCreateTime:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return protobufBuilderResult.hasId;
}
- (NSString*) id {
  return protobufBuilderResult.id;
}
- (MComment_Builder*) setId:(NSString*) _value {
  protobufBuilderResult.hasId = YES;
  protobufBuilderResult.id = _value;
  return self;
}
- (MComment_Builder*) clearId {
  protobufBuilderResult.hasId = NO;
  protobufBuilderResult.id = @"";
  return self;
}
- (BOOL) hasUserid {
  return protobufBuilderResult.hasUserid;
}
- (NSString*) userid {
  return protobufBuilderResult.userid;
}
- (MComment_Builder*) setUserid:(NSString*) _value {
  protobufBuilderResult.hasUserid = YES;
  protobufBuilderResult.userid = _value;
  return self;
}
- (MComment_Builder*) clearUserid {
  protobufBuilderResult.hasUserid = NO;
  protobufBuilderResult.userid = @"";
  return self;
}
- (BOOL) hasHeadImg {
  return protobufBuilderResult.hasHeadImg;
}
- (NSString*) headImg {
  return protobufBuilderResult.headImg;
}
- (MComment_Builder*) setHeadImg:(NSString*) _value {
  protobufBuilderResult.hasHeadImg = YES;
  protobufBuilderResult.headImg = _value;
  return self;
}
- (MComment_Builder*) clearHeadImg {
  protobufBuilderResult.hasHeadImg = NO;
  protobufBuilderResult.headImg = @"";
  return self;
}
- (BOOL) hasNickname {
  return protobufBuilderResult.hasNickname;
}
- (NSString*) nickname {
  return protobufBuilderResult.nickname;
}
- (MComment_Builder*) setNickname:(NSString*) _value {
  protobufBuilderResult.hasNickname = YES;
  protobufBuilderResult.nickname = _value;
  return self;
}
- (MComment_Builder*) clearNickname {
  protobufBuilderResult.hasNickname = NO;
  protobufBuilderResult.nickname = @"";
  return self;
}
- (BOOL) hasTargetId {
  return protobufBuilderResult.hasTargetId;
}
- (NSString*) targetId {
  return protobufBuilderResult.targetId;
}
- (MComment_Builder*) setTargetId:(NSString*) _value {
  protobufBuilderResult.hasTargetId = YES;
  protobufBuilderResult.targetId = _value;
  return self;
}
- (MComment_Builder*) clearTargetId {
  protobufBuilderResult.hasTargetId = NO;
  protobufBuilderResult.targetId = @"";
  return self;
}
- (BOOL) hasTargetNickname {
  return protobufBuilderResult.hasTargetNickname;
}
- (NSString*) targetNickname {
  return protobufBuilderResult.targetNickname;
}
- (MComment_Builder*) setTargetNickname:(NSString*) _value {
  protobufBuilderResult.hasTargetNickname = YES;
  protobufBuilderResult.targetNickname = _value;
  return self;
}
- (MComment_Builder*) clearTargetNickname {
  protobufBuilderResult.hasTargetNickname = NO;
  protobufBuilderResult.targetNickname = @"";
  return self;
}
- (BOOL) hasContent {
  return protobufBuilderResult.hasContent;
}
- (NSString*) content {
  return protobufBuilderResult.content;
}
- (MComment_Builder*) setContent:(NSString*) _value {
  protobufBuilderResult.hasContent = YES;
  protobufBuilderResult.content = _value;
  return self;
}
- (MComment_Builder*) clearContent {
  protobufBuilderResult.hasContent = NO;
  protobufBuilderResult.content = @"";
  return self;
}
- (BOOL) hasTime {
  return protobufBuilderResult.hasTime;
}
- (NSString*) time {
  return protobufBuilderResult.time;
}
- (MComment_Builder*) setTime:(NSString*) _value {
  protobufBuilderResult.hasTime = YES;
  protobufBuilderResult.time = _value;
  return self;
}
- (MComment_Builder*) clearTime {
  protobufBuilderResult.hasTime = NO;
  protobufBuilderResult.time = @"";
  return self;
}
- (BOOL) hasCreateTime {
  return protobufBuilderResult.hasCreateTime;
}
- (NSString*) createTime {
  return protobufBuilderResult.createTime;
}
- (MComment_Builder*) setCreateTime:(NSString*) _value {
  protobufBuilderResult.hasCreateTime = YES;
  protobufBuilderResult.createTime = _value;
  return self;
}
- (MComment_Builder*) clearCreateTime {
  protobufBuilderResult.hasCreateTime = NO;
  protobufBuilderResult.createTime = @"";
  return self;
}
@end

@interface MCommentList ()
@property (retain) NSMutableArray* mutableCommentsList;
@end

@implementation MCommentList

@synthesize mutableCommentsList;
- (void) dealloc {
  self.mutableCommentsList = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
  }
  return self;
}
static MCommentList* defaultMCommentListInstance = nil;
+ (void) initialize {
  if (self == [MCommentList class]) {
    defaultMCommentListInstance = [[MCommentList alloc] init];
  }
}
+ (MCommentList*) defaultInstance {
  return defaultMCommentListInstance;
}
- (MCommentList*) defaultInstance {
  return defaultMCommentListInstance;
}
- (NSArray*) commentsList {
  return mutableCommentsList;
}
- (MComment*) commentsAtIndex:(int32_t) index {
  id _value = [mutableCommentsList objectAtIndex:index];
  return _value;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  for (MComment* element in self.commentsList) {
    [output writeMessage:1 value:element];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (int32_t) serializedSize {
  int32_t size = memoizedSerializedSize;
  if (size != -1) {
    return size;
  }

  size = 0;
  for (MComment* element in self.commentsList) {
    size += computeMessageSize(1, element);
  }
  size += self.unknownFields.serializedSize;
  memoizedSerializedSize = size;
  return size;
}
+ (MCommentList*) parseFromData:(NSData*) data {
  return (MCommentList*)[[[MCommentList builder] mergeFromData:data] build];
}
+ (MCommentList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MCommentList*)[[[MCommentList builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (MCommentList*) parseFromInputStream:(NSInputStream*) input {
  return (MCommentList*)[[[MCommentList builder] mergeFromInputStream:input] build];
}
+ (MCommentList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MCommentList*)[[[MCommentList builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MCommentList*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (MCommentList*)[[[MCommentList builder] mergeFromCodedInputStream:input] build];
}
+ (MCommentList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (MCommentList*)[[[MCommentList builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (MCommentList_Builder*) builder {
  return [[[MCommentList_Builder alloc] init] autorelease];
}
+ (MCommentList_Builder*) builderWithPrototype:(MCommentList*) prototype {
  return [[MCommentList builder] mergeFrom:prototype];
}
- (MCommentList_Builder*) builder {
  return [MCommentList builder];
}
@end

@interface MCommentList_Builder()
@property (retain) MCommentList* protobufBuilderResult;
@end

@implementation MCommentList_Builder
@synthesize protobufBuilderResult;
- (void) dealloc {
  self.protobufBuilderResult = nil;
  [super dealloc];
}
- (id) init {
  if ((self = [super init])) {
    self.protobufBuilderResult = [[[MCommentList alloc] init] autorelease];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return protobufBuilderResult;
}
- (MCommentList_Builder*) clear {
  self.protobufBuilderResult = [[[MCommentList alloc] init] autorelease];
  return self;
}
- (MCommentList_Builder*) clone {
  return [MCommentList builderWithPrototype:protobufBuilderResult];
}
- (MCommentList*) defaultInstance {
  return [MCommentList defaultInstance];
}
- (MCommentList*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (MCommentList*) buildPartial {
  MCommentList* returnMe = [[protobufBuilderResult retain] autorelease];
  self.protobufBuilderResult = nil;
  return returnMe;
}
- (MCommentList_Builder*) mergeFrom:(MCommentList*) other {
  if (other == [MCommentList defaultInstance]) {
    return self;
  }
  if (other.mutableCommentsList.count > 0) {
    if (protobufBuilderResult.mutableCommentsList == nil) {
      protobufBuilderResult.mutableCommentsList = [NSMutableArray array];
    }
    [protobufBuilderResult.mutableCommentsList addObjectsFromArray:other.mutableCommentsList];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (MCommentList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (MCommentList_Builder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSet_Builder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    int32_t tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        MComment_Builder* subBuilder = [MComment builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addComments:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSArray*) commentsList {
  if (protobufBuilderResult.mutableCommentsList == nil) { return [NSArray array]; }
  return protobufBuilderResult.mutableCommentsList;
}
- (MComment*) commentsAtIndex:(int32_t) index {
  return [protobufBuilderResult commentsAtIndex:index];
}
- (MCommentList_Builder*) replaceCommentsAtIndex:(int32_t) index with:(MComment*) _value {
  [protobufBuilderResult.mutableCommentsList replaceObjectAtIndex:index withObject:_value];
  return self;
}
- (MCommentList_Builder*) addAllComments:(NSArray*) values {
  if (protobufBuilderResult.mutableCommentsList == nil) {
    protobufBuilderResult.mutableCommentsList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableCommentsList addObjectsFromArray:values];
  return self;
}
- (MCommentList_Builder*) clearCommentsList {
  protobufBuilderResult.mutableCommentsList = nil;
  return self;
}
- (MCommentList_Builder*) addComments:(MComment*) _value {
  if (protobufBuilderResult.mutableCommentsList == nil) {
    protobufBuilderResult.mutableCommentsList = [NSMutableArray array];
  }
  [protobufBuilderResult.mutableCommentsList addObject:_value];
  return self;
}
@end

